### DISCUSSION TITLE
Is there a way to interact with bare git repos, say for a dotfiles repo?

### DISCUSSION THREAD

**Discussion by jtrv** [jesseduffield/lazygit#1201] [Q&A]
Is there a way to use lazygit to interact with a `--bare` repo? I would like to interact with my `/dotfiles` repo given [this common configuration](https://www.youtube.com/watch?v=tBoLDpTWVOM)

**Comment by jesseduffield** [comment]
I'm not fully across bare repos and all the edge cases but you should be able to go `lazygit --git-dir=$HOME/.myconf --work-tree=$HOME` (substituting the right directories)

**Reply by jtrv** [reply]
Awesome, thanks!

**Reply by joshgummersall** [reply]
I use `lazygit` with `yadm` (which manages dotfiles in this way) and can confirm - I alias `ly` to `lazygit -ucd ~/.local/share/yadm/lazygit -w ~ -g ~/.local/share/yadm/repo.git`. The reason for `ucd` is that I've found that accidentally triggering "Add all files" makes lazygit hang, so I disable it in a custom configuration file. Otherwise it works great!

**Reply by Mellbourn** [reply]
Additional tip: `-ucd` takes an array of configs, so you can have just the keybinding in the yadm-specific file

`~/.config/yadm/lazygit.yml`:
```yaml
keybinding:
  files:
    toggleStagedAll: '<c-a>' # avoid "stage/unstage all" since it hangs lazygit, cause I guess it tries to list all files
```
alias:
```shell
alias yl='lazygit --use-config-file "$HOME/.config/yadm/lazygit.yml,$HOME/Library/Application Support/lazygit/config.yml" --work-tree ~ --git-dir ~/.local/share/yadm/repo.git'
```
