### DISCUSSION TITLE
Any chance to have something like git-absorb?

### DISCUSSION THREAD

**Discussion by folago** [jesseduffield/lazygit#1626] [Ideas]
As the tittle say, git absorb is [this](https://github.com/tummychow/git-absorb).

**Comment by jesseduffield** [comment]
very cool. This would be a good candidate for a custom command. See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md

**Reply by folago** [reply]
Ah nice!!!

**Comment by pricci1** [comment]
This is my custom command for git absorb

<img width="837" height="224" alt="image" src="https://github.com/user-attachments/assets/63e061c4-0392-40c5-a453-cd1e7f68b6c1" />


```yaml
customCommands:
  - key: '<c-a>'
    description: 'Git absorb menu'
    commandMenu:
      - key: 'a'
        command: 'git absorb'
        context: 'files'
        description: 'Absorb staged changes'
        output: 'popup'
        loadingText: 'Absorbing staged changes...'
      - key: 'r'
        context: 'files'
        description: 'Absorb staged and then auto-rebase'
        prompts:
          - type: 'confirm'
            title: 'Absorb and Rebase'
            body: 'This will absorb staged changes and automatically rebase. This modifies git history. Continue?'
        command: 'git absorb --and-rebase'
        loadingText: 'Absorbing and rebasing...'
        output: 'popup'
      - key: 'd'
        command: 'git absorb --dry-run'
        context: 'files'
        description: 'Dry run (preview changes)'
        output: 'popup'
        loadingText: 'Running dry-run...'
      - key: 'f'
        context: 'files'
        description: 'Force absorb (skip all safety checks)'
        prompts:
          - type: 'confirm'
            title: 'Force Absorb'
            body: 'WARNING: This skips all safety checks. Are you sure you want to force absorb?'
        command: 'git absorb --force'
        loadingText: 'Force absorbing...'
        output: 'popup'
      - key: 'a'
        context: 'commits'
        description: 'Absorb with selected commit as base'
        prompts:
          - type: 'confirm'
            title: 'Absorb with Base'
            body: 'Absorb staged changes up to the selected commit. Continue?'
        command: 'git absorb --base {{.SelectedLocalCommit.Hash}}'
        loadingText: 'Absorbing with base...'
        output: 'popup'
      - key: 'r'
        context: 'commits'
        description: 'Absorb with base and then auto-rebase'
        prompts:
          - type: 'confirm'
            title: 'Absorb with Base and Rebase'
            body: 'This will absorb up to {{.SelectedLocalCommit.Hash}} and rebase. This rewrites history. Continue?'
        command: 'git absorb --base {{.SelectedLocalCommit.Hash}} --and-rebase'
        loadingText: 'Absorbing and rebasing with base...'
        output: 'popup'
      - key: 'd'
        command: 'git absorb --base {{.SelectedLocalCommit.Hash}} --dry-run'
        context: 'commits'
        description: 'Dry run with selected base'
        output: 'popup'
        loadingText: 'Running dry-run with base...'
      - key: 'f'
        context: 'commits'
        description: 'Force absorb with base (skip all safety checks)'
        prompts:
          - type: 'confirm'
            title: 'Force Absorb with Base'
            body: 'WARNING: This forces absorb up to the selected commit with no safety checks. Continue?'
        command: 'git absorb --base {{.SelectedLocalCommit.Hash}} --force'
        loadingText: 'Force absorbing with base...'
        output: 'popup'
      - key: 'h'
        command: 'git absorb --help'
        description: 'Show git absorb help'
        output: 'popup'
```
