### DISCUSSION TITLE
How to make this custom command work

### DISCUSSION THREAD

**Discussion by bryant-the-coder** [jesseduffield/lazygit#1776] [Q&A]
`git commit -m "This is a blank commit" --allow-empty`

```yml
customCommands:
  - key: X
    command: 'git commit -m "This is a blank commit" --allow-empty'
    context: global
    description: Empty commit
    loadingText: Pushing...
```

I cant seem to make this work. it keep saying this is a blank commit when it should be empty
