### DISCUSSION TITLE
Regex for matching git repo names for `git.commitPrefixes`

### DISCUSSION THREAD

**Discussion by harsilspatel** [jesseduffield/lazygit#1941] [Ideas]
This feature request stems from my git workflow which warrants prefixing the commits, in all the repositories, with relevant Jira issue ID. So, every new repo has to be added to the `git.commitPrefixes` with the same `pattern` and `replace` config.

A solution that I could think of was matching the project names by regular expressions. And perhaps we could define precedence, say the last entry that matches repo name is used, if multiple regexes match the project name.

For instance, let's say our repo name is `kramerica_industries_api` and if our config involves the following (snippet):
```yaml
git:
  commitPrefixes:
    kramerica_industries.*: # this matches
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '🥨: ' # these pretzels are making me thirsty!
    vandelay_industries.*: # does not match
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '🥖: ' # _schnitzer's marble rye_, all the way!
    .*api$: # this also matches and has higher precedence so this config will be applied
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] '
```
then the entry `.*api$` will be used for the commit prefix.

My example assumes that the order of the object keys is maintained when the yaml config is parsed. If not we'll have to impose precedence some other way but hopefully the example articulates my thoughts well enough to spark a discussion on the topic!
