### DISCUSSION TITLE
Jump to specific window and maximize it~

### DISCUSSION THREAD

**Discussion by LintaoAmons** [jesseduffield/lazygit#1998] [General]
I know I can use numbers `1, 2, 3, 4, 5` to jump to some window quickly.

But I wonder if I can maximize it to full screen? like `btop`~

**Comment by venkateshdi** [comment]
There is a keybinding to switch between window sizes (default, two pane, full screen). 

```
keybinding:
  universal:
    nextScreenMode: '+'
    prevScreenMode: '_'
```
