### DISCUSSION TITLE
Is that possible to quit lazygit after run commands in subprocess?

### DISCUSSION THREAD

**Discussion by Tim-Cao** [jesseduffield/lazygit#2253] [Q&A] [answered]
*Issues:*
It is back to lazygit by default after executing custom command in subprocess.
For example,
Add this custom comand to config.yml
```
customCommands:
  - key: '<c-s>'
    description: 'search commits by keywords'
    command: "git log --oneline --grep='{{index .PromptResponses 0}}'"
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Keywords'
        initialValue: ''
    subprocess: true
```
Is that possible to quit lazygit after printing the output in terminal?
