### DISCUSSION TITLE
Ability to add custom commands with no keybind?

### DISCUSSION THREAD

**Discussion by DominickVale** [jesseduffield/lazygit#2283] [Ideas]
Considering the fact that as far as I understand there's no way to add ALT and differentiate between lowercase and uppercase keybinds, would it be possible to make the -key option either optional or add a null key so that it shows up in the help menu and I can just press enter on it to execute?

**Comment by Ryooooooga** [comment]
`null` key binding is supported in 0.36.0.

```yaml
customCommands:
  - key: null
    command: git cz
    context: files
    subprocess: true
```

or simply

```yaml
customCommands:
  - command: git cz
    context: files
    subprocess: true
```
