### DISCUSSION TITLE
git diff --color-words custom command

### DISCUSSION THREAD

**Discussion by mafsi** [jesseduffield/lazygit#2305] [Q&A] [answered]
I tried this but nothing happened. It shows in menu but just that.
```
customCommands:
  - key: '<c-space>'
    command: 'git diff --color-words {{.SelectedFile.Name}}'
    context: 'global'
```
