### DISCUSSION TITLE
Possible to run a custom command with a pipe without `subprocess: yes`?

### DISCUSSION THREAD

**Discussion by bdach** [jesseduffield/lazygit#2446] [Q&A]
I have the following custom command definition:

```yml
customCommands:
  - key: y
    context: files
    command: "echo \"\\`\\`\\`diff\n`git diff`\n\\`\\`\\`\" | xclip -sel clipboard"
    description: yank pending changes as markdown diff code block
    subprocess: yes
```

The use case is to take all of the pending changes in the current index and put them into the X clipboard for pasting elsewhere (like github review comments). As it stands, the command takes two keypresses to complete: the initial <kbd>Y</kbd>, and then a <kbd>Return</kbd> because of `subprocess: yes`. I would like to get rid of the subprocess, but not doing so causes the command to seemingly spin endlessly, even though the code block is available in the system clipboard:

![1676662879](https://user-images.githubusercontent.com/20418176/219773915-59fe73b5-cf43-43f9-8d71-de08edd4d1e5.png)

I suspect this is because of the pipe redirection. Is there an easy lazygit-config-only way I can make this work in only the one <kbd>Y</kbd> keypress?
