### DISCUSSION TITLE
How to do I do git pull with autostash enabled?

### DISCUSSION THREAD

**Discussion by akbarsha03** [jesseduffield/lazygit#2487] [Q&A]
I used to do `git pull --rebase --autostash origin main` most of the time. I'm not sure how to achieve this in LazyGit. Thanks for your help.

**Comment by mark2185** [comment]
`lazygit` will read the `.gitconfig` options so if you've got `pull.rebase=true` and `rebase.autoStash=true` it will automatically do that when you press `p` on a branch.

In case you do not have those options set, you can create a custom command under a different keymap just for that, something like this in your `lazygit/config.yml`:
```
customCommands:
  - key: 'F'
    command: 'git pull --rebase --autostash {{ SelectedLocalBranch.Name }}'
    context: 'localBranches'
    stream: true
```

Source: [docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md).
