### DISCUSSION TITLE
Is it possible to delete remote tags?

### DISCUSSION THREAD

**Discussion by AndrewSav** [jesseduffield/lazygit#2633] [General]
I was able to figure out how to create local tags and push them, but I don't seem to be able to push a deleted local tag. Is this possible?

Also it seems deleting tags locally is futile anyway, they come back from the remote in a minute anyway... Is it possible to make it stick?

**Comment by mark2185** [comment]
Currently there isn't, so I guess a custom command is what I'd advise.

Something like this:
```
  - key: 'D'
    command: "git push --delete {{ .SelectedTag.FullRefName }}"
    context: 'tags'
    stream: true
    prompts:
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to delete the tag {{.SelectedTag}}?"

```

**Reply by AndrewSav** [reply]
Thanks, is there an issue for this? If not I'm happy to open one.

**Reply by mark2185** [reply]
I don't remember seeing one so I've turned this discussion into #2635 .

**Reply by AndrewSav** [reply]
@mark2185 I just tried the above, and it seems we also need to pass a remote to `git push --delete` is there a template var for that?

**Reply by mark2185** [reply]
Based on [tag.go](https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/models/tag.go), nothing indicates its remote.

I guess you could prompt for it, something like this (again, just eyeballing it). 
```
  - key: 'D'
    context: 'tags'
    stream: true
    prompts:
      - type: 'input'
        title: 'Remote:'
        initialValue: "origin"
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to delete the tag {{.SelectedTag}} on {{index .PromptResponses 0}}?"
        command: 'git push --delete {{ index.PromptResponses 0 }} {{ .SelectedTag.FullRefName }}'
``` 

Feel free to take a stab at it yourself, [`Config.md`](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) is a good starting point.

**Reply by AndrewSav** [reply]
`{{ .SelectedRemote.Name }}` works. Thank you for your guidance.

```
  - key: 'D'
    command: "git push --delete {{ .SelectedRemote.Name }} {{ .SelectedTag.FullRefName }}"
    context: 'tags'
    stream: true
    prompts:
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to delete the tag {{.SelectedTag}} on {{ .SelectedRemote.Name }}?"
```
