### DISCUSSION TITLE
I need help with commitPrefixes

### DISCUSSION THREAD

**Discussion by inaki6martinez** [jesseduffield/lazygit#2722] [Q&A]
Hello,

I am trying to add the branch name as a prefix for my commits, but for some reason it is not working. I'm triying to add fixed string and doesn't work neither.
```
git:
  commitPrefixes:
    meter_esmr5: # This is repository folder name
      pattern: "^\\w+.*"
      replace: 'bug'
```
![image](https://github.com/jesseduffield/lazygit/assets/12186402/da31ff6a-93dc-4e93-a6de-33c5139f7f1a)

Could someone tell me if I'm doing something wrong?
Thank you!
