### DISCUSSION TITLE
Direct keymap for stash staged?

### DISCUSSION THREAD

**Discussion by danielo515** [jesseduffield/lazygit#2724] [Q&A] [answered]
Hello.
I want to be able to configure a keybind in the files pane to stash all staged files (or ideally, the current file). Is that possible? In the config I don't see any option to do that, only to stash all or to go to stash options.

**Comment by mark2185** [comment, marked as answer]
Currently the only way of doing it is writing a [custom command](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) and mapping it to whichever key you want.

Or if you'd rather an easier solution - you could try getting used to `Ss` which opens up a menu and stashes staged changes.

**Reply by danielo515** [reply]
Custom command is almost perfect for my use-case. I added this:

```yaml
customCommands:
  - key: 's'
    context: 'files'
    command: "git stash push {{if .SelectedFile.HasStagedChanges}} --staged {{else}} --include-untracked {{end}} -m '{{.Form.Msg}}'"
    description: 'Stash staged or everything'
    prompts:
      - type: 'input'
        title: 'Stash message'
        key: 'Msg'
        initialValue: ''
```

Works like a charm, but it forces me to work using SelectedFile, while what I wanted in reality was current branch, but the current branch does not have the HasStagedChanges field
