### DISCUSSION TITLE
Is it possible to have a default commitPrefixes without specifying the directory

### DISCUSSION THREAD

**Discussion by rg4115** [jesseduffield/lazygit#2758] [Q&A]
- right now we need to specify a directory where the commitPrefixes applies (like 'my_project' in the example below)
```yaml
  commitPrefixes:
    my_project: # This is repository folder name
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] '
```
- But I have tons of repos which follow the same pattern, so specifying them for every repo is tedious
- Is it possible to have a default commitPrefixes which applies to all directories
