### DISCUSSION TITLE
Help with commit Prefixes

### DISCUSSION THREAD

**Discussion by GianniBYoung** [jesseduffield/lazygit#2770] [Q&A]
Hello, I am looking for help setting up commit prefixes.

I have the following directory structure:

icon
├── repo1
└── repo2

The branches are named `repo1/ICON-01` and I would like to be able to have commit messages in the format `ICON-01 - commitmessage`

Here is what I have in my config and I havent been able to successfully add the prefix to any commits. What am I missing?

```
git:
  commitPrefixes:
   repo1: # This is repository folder name
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] - '
```
