### DISCUSSION TITLE
Is it possible to save custom patch to a file?

### DISCUSSION THREAD

**Discussion by antosha417** [jesseduffield/lazygit#2934] [Q&A] [answered]
Hey! I love using lazy git a lot and grateful to people that spend time working on it!

I was wondering is it possible to save custom patch to a file? I want to share this patch with another person.

**Comment by stefanhaller** [comment, marked as answer]
You can copy the patch to the clipboard (`<c-p>`, `y`), and then paste it into a file. Is that good enough?

**Reply by antosha417** [reply]
Yeah, this is just what I need!
Initially I installed lazygit from source and have not updated it for about a year, so could not find this option 🤦 

Thank you for your help @stefanhaller

**Reply by DusanLesan** [reply]
@antosha417  You can also easily create a custom command that would handle file creation on its own
I have one letting me choose between copying changes in clipboard and making a file:
```
customCommands:
  - key: '<c-y>'
    description: 'Create Patch'
    context: 'files'
    command: 'send_text {{index .PromptResponses 0}} {{index .PromptResponses 1}} "$(git diff --cached)"'
    prompts:
      - type: 'menu'
        title: 'Where to save?'
        options:
          - value: 'drop'
          - value: 'file'
      - type: 'input'
        title: 'File Name:'
```
After that create simple script (`send_text` in this example) to handles all the rest
