### DISCUSSION TITLE
can I map command to an alias?

### DISCUSSION THREAD

**Discussion by madelaney** [jesseduffield/lazygit#3045] [Q&A]
All,

When I tell lazygit to commit, can I overwrite the default command `git commit`, and instead use something like `git ci` (where `ci` is an alias in my global git config) ?

Do I just add a value to `customCommands` to do this, like:
```yaml
---
customCommands:
  - key: 'C'
    context: 'global'
    command: "git ci"
    subprocess: true
```
