### DISCUSSION TITLE
There was an error pushing to a specific remote repository

### DISCUSSION THREAD

**Discussion by morynth** [jesseduffield/lazygit#3098] [Q&A]
I followed the wiki's tutorial and added a custom command to `config.yml`, which is used to push to the specified remote repository. I followed the menu options and eventually the push failed and the log output authentication failed because it did not let me enter the username and password.

config.yml

```
customCommands:
  - key: '<c-P>'
    description: "Push to a specific remote repository"
    context: 'global'
    loadingText: 'Pushing ...'
    prompts:
      - type: 'menuFromCommand'
        title: 'Which remote repository to push to?'
        command: bash -c "git remote --verbose | grep '/.* (push)'"
        filter: '(?P<remote>.*)\s+(?P<url>.*) \(push\)'
        valueFormat: '{{ .remote }}'
        labelFormat: '{{ .remote | bold | cyan }} {{ .url }}'
      - type: 'menu'
        title: 'How to push?'
        options:
          - value: 'push'
          - value: 'push --force-with-lease'
          - value: 'push --force'
```

Command log

How to correct it？
