### DISCUSSION TITLE
Panel for Unchanged Changes Is Behaving Weird

### DISCUSSION THREAD

**Discussion by eeriemyxi** [jesseduffield/lazygit#3127] [Q&A] [answered]
![image](https://github.com/jesseduffield/lazygit/assets/86738916/cc015d7a-9bc6-43d2-b8ff-5e494c6a15a6)

My unstaged view panel shows changes of multiple files when I scroll through them. It is covering the whitespaces with content from another file where the whitespaces are filed with source code. How to fix this? I want to see per-file changes rather than some merged mess like this.

**Comment by mark2185** [comment]
Could you please post your `config.yml`? Does it happen with other files as well? Does it happen if you switch to the zoomed mode with `+`?

**Reply by eeriemyxi** [reply]
I think the best way to describe the behaviour would be some screen recording: https://files.catbox.moe/rjnijj.mp4 (I have tried the zoom mode in the video).

I have brought the contents of my `config.yml` here:
```yml
gui:
  showIcons: true
git:
  paging:
    useConfig: true
```

**Reply by mark2185** [reply, marked as answer]
Does it happen in other terminals as well?

Does it happen if you set `git.paging.useConfig` to `false`?

**Reply by eeriemyxi** [reply]
Somehow it works perfectly fine when I remove everything in the `git` section of my config file. This is my git config file: 
```toml
[user]
	email = eeriemyxi@proton.me
	name = eeriemyxi
[init]
	defaultBranch = main
[core]
	excludesFile = ~/.gitignore_global
	editor = nvim
[alias]
        usw = update-index --skip-worktree
	unsw = update-index --no-skip-worktree
	com = commit -m
	sw = switch
	al = add .
````

My terminal is Alacritty.

With my `git` section uncommented, in Kitty terminal, I can reproduce this behaviour: 
![image](https://github.com/jesseduffield/lazygit/assets/86738916/25177416-44d3-4a4e-855b-beac045fb21f)
