### DISCUSSION TITLE
Is this normal for a "first use"?

### DISCUSSION THREAD

**Discussion by PhoenixWyllow** [jesseduffield/lazygit#3339] [Q&A] [answered]
I don't feel like this is a bug, but a "skill issue" on my part.
This is what I see when I run lazyvim:
![image](https://github.com/jesseduffield/lazygit/assets/54237626/fd35ee92-1461-4738-b55b-bc5a4b884825)

I can navigate ok, but I was expecting the panels to show together (as seen in the readme), not full-window. I have also tried making my terminal full screen, but nothing. I did find the `+` keybind which helps, but I'd like it to show up immediately.

I tried pasting the dafault config into mine, but lazygit fails to open and returns to the prompt immediately. After a little playing around, this is my current config: 
```yaml
gui:
  windowSize: 'full' # one of 'normal' | 'half' | 'full' default is 'normal'
  sidePanelWidth: 0.3333 # number from 0 to 1
  expandFocusedSidePanel: true
  mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
  enlargedSideViewLocation: 'left' # one of 'left' | 'top'
  timeFormat: '2006-02-25' # https://pkg.go.dev/time#Time.Format
  shortTimeFormat: '15:04'
```
but nothing seems to have changed...
I have a few other issues (like hanging on "stage all"), but I'll search more myself before asking (also going off-track for this Q&A).

I'm using Windows and have manually set `$env:XDG_CONFIG_HOME = "$HOME/.config"` in my profile (so my nvim and lazygit configs follow linux paths (for my own sanity since I use both Linux and Windows and keep my dotfiles the same between them)
