### DISCUSSION TITLE
How to change default keybinding?

### DISCUSSION THREAD

**Discussion by wojciech-kulik** [jesseduffield/lazygit#3359] [Q&A] [answered]
I need to run action `View filter-by-path...` but it's using `<c-s>` binding which causes conflict with my tmux prefix key. 

Is there any way to change this binding?

**Comment by mark2185** [comment, marked as answer]
If you search for `<c-s>` in the docs markdown you'll find the key `filteringMenu` and you can replace it with e.g. `<c-b>` in your `config.yml`:
```yml
keybinding:
  universal:
    filteringMenu: '<c-b>'
```
