### DISCUSSION TITLE
How to add these git graph elements on lazygit interface?

### DISCUSSION THREAD

**Discussion by hopezh** [jesseduffield/lazygit#3417] [Q&A] [answered]
May I ask how to config `lazygit` to show those `git graph` icons as highlighted by the arrows in the image below?

![2024-03-23 18 53 17](https://github.com/jesseduffield/lazygit/assets/23435810/cce3d844-d94f-4670-b8ce-1f7a195fdaf8)

**Comment by hasecilu** [comment, marked as answer]
Add
```yml
gui:
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
```
to your config file and be sure to have a compatible NerdFont installed.

**Reply by hopezh** [reply]
Thanks a lot, @hasecilu. Previously, I accidentally put the config you suggested under "gui -> theme" section. Now, it works perfectly.

**Comment by hopezh** [comment]
Btw, the last three lines also need to be added to the config to show the git graph: 

```
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - reverse
    inactiveBorderColor:
      - "#3a3a3a"
  border: 'rounded' # one of 'single' | 'double' | 'rounded' | 'hidden'

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
    useConfig: false
  commit:
    signOff: false
  merging:
    # only applicable to unix users
    manualCommit: false
    # extra args passed to `git merge`, e.g. --no-ff
    args: "--no-ff"
  log:
    showGraph: always
    showWholeGraph: true
```
