### DISCUSSION TITLE
Theming options and decluttering

### DISCUSSION THREAD

**Discussion by adriangalilea** [jesseduffield/lazygit#3428] [Q&A]
Hello,

Loving lazygit but feeling it's a bit harsh on my eyes,

I'd love to:
- Customise it beyond the options I see in the config
```
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
```
There's no more options, right?
- Offer my help to re-design the defaults or alternative themes (if this is welcomed)

Let me know,

Adrian.
