### DISCUSSION TITLE
would be nice if i could remap s for local branch sort order ...

### DISCUSSION THREAD

**Discussion by tg0h** [jesseduffield/lazygit#3440] [General]
currently, pressing 's' in the branches view brings up the sort order view ...

I am unable to remap this key to something else (I use s to go to the next block)

**Comment by stefanhaller** [comment]
Works for me:
```yaml
keybinding:
  branches:
    sortOrder: "<disabled>"
```
