### DISCUSSION TITLE
auto update submodule when checkout

### DISCUSSION THREAD

**Discussion by cathaysia** [jesseduffield/lazygit#3455] [Q&A] [answered]
If it's possbile auto update submodule when checkout to a new branch?

**Comment by stk-ableton** [comment, marked as answer]
Not right now. I have the following custom command that makes it easy to update submodules with a single keystroke (I find it too cumbersome to navigate to the submodules tab to do it there):

```yaml
customCommands:
  - key: "U"
    command: "git submodule update --init --recursive"
    context: "global"
    description: "Update submodules"
    loadingText: "Updating Submodules..."
    stream: true
```
