### DISCUSSION TITLE
Custom command to edit selected commit

### DISCUSSION THREAD

**Discussion by enzosterro** [jesseduffield/lazygit#3737] [Q&A]
Hi all,

I'm trying a custom command so that I can select a commit, press control-e and it will start the interactive rebase, reset the commit to HEAD and give control back to lazygit. The problem is that it runs the command indefinitely, I think because the command itself spawns a new process waiting for user input.

Here is the command
```
customCommands:
  - key: '<c-e>'
    description: 'Edit commit'
    command: 'git rebase --interactive --autostash --keep-empty --no-autosquash --rebase-merges {{.SelectedLocalCommit.Sha}} && git reset ^HEAD'
    context: 'commits'
    loadingText: 'Editing...'
```

I would appreciate any advice. Thank you!
