### DISCUSSION TITLE
Most configurations are not working in Lazygit WSL OR if Lazygit is launched in Windows Console

### DISCUSSION THREAD

**Discussion by samaursa** [jesseduffield/lazygit#3844] [General]
For example, here's my config file where I have commented on the lines that do not work:

```
git:
  paging:
    # not sure if this works
    colorArg: always
    # does not seem to work (I have diff-so-fancy installed and working from command line in WSL: see bug here: https://github.com/jesseduffield/lazygit/issues/3833)
    useConfig: true
  # does not seem to work
  defaultLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  # does not seem to work
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  # I _think_ this works
  mainBranches:
    - master
    - main
    - dev

notARepository: quit
# does not seem to work
splitDiff: always
# does not seem to work
filterMode: fuzzy
# not sure if this works or not
showDivergenceFromBaseBranch: arrowAndNumber
# does not seem to work
statusPanelView: allBranchesLog

gui:
  branchColors:
    'dev': '#f6ff33' # works
    'bugfix': '#ff3333' # works

quitOnTopLevelReturn: false # works
```

Any help would be greatly appreciated!
