### DISCUSSION TITLE
How to change this color?

### DISCUSSION THREAD

**Discussion by cofeek-codes** [jesseduffield/lazygit#3877] [Q&A]
i am using lazygit in lazyvim, so it sets  theme automatically, but in range selection mode added lines become gray, but i'd like them to be bold green. How can i achieve  it?
![image](https://github.com/user-attachments/assets/142bd535-0123-495e-8315-dc70877967dd)
`lazygit-theme.yml`:

```yaml
os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: 3
  theme:
   selectedLineBgColor:
     - "#073642"
   searchingActiveBorderColor:
     - "#fdf6e3"
     - "bold"
   optionsTextColor:
     - "#268bd2"
   inactiveBorderColor:
     - "#93a1a1"
   defaultFgColor:
     - "#93a1a1"
   cherryPickedCommitFgColor:
     - "#268bd2"
   cherryPickedCommitBgColor:
     - "#268bd2"
   activeBorderColor:
     - "#fdf6e3"
     - "bold"
   unstagedChangesColor:
     - "#dc322f"

```
