### DISCUSSION TITLE
XDG config file doesn't seem to be read on macOS

### DISCUSSION THREAD

**Discussion by shamindras** [jesseduffield/lazygit#3884] [Q&A] [answered]
Thank you for this fantastic software. 

I've recently been updating my dotfiles, and am having issues importing my lazygit config. Specifically it looks like this when I call lazygit on my current repo using alacritty:

![image](https://github.com/user-attachments/assets/a0f82287-da80-44fe-bd1d-27943f990ca4)

<details><summary>macOS specs</summary>

```bash
OS: macOS 14.4.1 23E224 x86_64 
Host: MacBookPro16,1 
Kernel: 23.4.0 
Uptime: 2 days, 22 hours, 10 mins 
Packages: 274 (brew) 
Shell: zsh 5.9 
Resolution: 1792x1120@2x 
DE: Aqua 
WM: yabai 
Terminal: alacritty 
CPU: Intel i9-9980HK (16) @ 2.40GHz 
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M 
Memory: 20862MiB / 65536MiB 
```
</details>

<details><summary>lazygit version details</summary>

```bash
➜ lazygit --version
commit=, build date=, build source=homebrew, version=0.43.1, os=darwin, arch=amd64, git version=2.46.0
```
</details>

Now I've read [these instructions](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#user-config) also set my `XDG_CONFIG_HOME` to `~/.config`, which can be seen here
 
<details><summary>Setting XDG_CONFIG_HOME here</summary>

```bash
➜ echo $XDG_CONFIG_HOME
/Users/shamindras/.config
```
</details>

And importantly, I have linked my preferred lazygit `config.yml` file to `$XDG_CONFIG_HOME/lazygit/config.yml`. Which can be seen here:

<details><summary>Snippet of symlink of <code>.config.yml</code> in <code>XDG_CONFIG_HOME</code></summary>

```bash
~/.config/lazygit ss-zsh-04
➜ cat config.yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  # showFileIcons: true
  # showIcons: true
  # use the mocha catpuccin theme
  # see: https://github.com/catppuccin/lazygit#usage
  theme:
    # lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
```
</details>

The full `config.yml` file is pasted below for reference.

<details><summary>config.yml</summary>

```bash
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  # showFileIcons: true
  # showIcons: true
  # use the mocha catpuccin theme
  # see: https://github.com/catppuccin/lazygit#usage
  theme:
    # lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: rounded
  authorColors: # in case you're not happy with the randomly assigned colour
    "shamindras": "#9db5bf"
    "SS": "#9db5bf"
  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: true # stuff relating to the UI

# use delta for git diffs
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers --paging=never
    useConfig: false

# use conventional commits via commitizen
# source: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#committing-via-commitizen-cz-c
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

# TODO switch from `vim` to `nvim`
os:
  editCommand: "vim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"
```

</details>

It is clear that my preferred JetBrainsMono Nerd Font icons (`nerdFontsVersion: "3"`) or other settings (e.g., `border: rounded`) are not being displayed despite the above. 

I can confirm that `JetBrainsMono Nerd Font` and the Nerd Font icons are being displayed in alacritty, where I'm launching lazygit from:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/7c7b8e92-880f-4a4f-beef-ccacdab087a5">

I also ensured that `~/Library/Application\ Support/lazygit/config.yml` was deleted, to avoid it being read in by default. I've restarted both my Alacritty terminal and also my entire computer to check if that fixed the issue, but it didn't.

It looks like the **default** config.yml settings are being used by `lazygit`. Could anyone please guide me to allow lazygit to use my preferred `config.yml` settings as above?

**Comment by mgray88** [comment]
You mention setting `XDG_CONFIG_HOME` via the linked instructions, but have you set it in your `.zshenv` file so that it is available in a new shell session?

For example here is my `.zshenv` file:
<details><summary>.zshenv</summary>

```
#!/bin/zsh

# Zsh startup order:
# /etc/zshenv
#   Always run for every zsh.
# ~/.zshenv
#   Usually run for every zsh (see below).
# /etc/zprofile
#   Run for login shells.
# ~/.zprofile
#   Run for login shells.
# /etc/zshrc
#   Run for interactive shells.
# ~/.zshrc
#   Run for interactive shells.
# /etc/zlogin
#   Run for login shells.
# ~/.zlogin
#   Run for login shells.

export ZDOTDIR=${ZDOTDIR:-$HOME/.config/zsh}

# XDG
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}

# Ensure Zsh directories exist.
() {
  local zdir
  for zdir in $@; do
    [[ -d "${(P)zdir}" ]] || mkdir -p -- "${(P)zdir}"
  done
} XDG_{CONFIG,CACHE,DATA,STATE}_HOME

# Locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
</details>

> [!NOTE]
> My particular setup also assumes `$ZDOTDIR` is set in `/etc/zshenv`:
<details><summary>/etc/zshenv</summary>

```
if [[ ! -o norcs ]]; then
  export ZDOTDIR="$HOME/.config/zsh"
fi
```
</details>

**Reply by shamindras** [reply]
Thanks @mgray88 for your response.

> You mention setting `XDG_CONFIG_HOME` via the linked instructions, but have you set it in your .zshenv file so that it is available in a new shell session?

Yes, I do. In fact, I set just `$ZDOTDIR` in my `~/.zshnenv` as per [here](https://github.com/shamindras/dotfiles/blob/main/config/zsh/.zshenv#L9). And the `XDG` variables in my linked `$ZDOTDIR/zsh/.zshrc` as per [here](https://github.com/shamindras/dotfiles/blob/main/config/zsh/.zshrc#L13-L32). The code is very similar to yours.

This is the output from a completely new terminal session for `$XDG_CONFIG_HOME`:

<img width="355" alt="image" src="https://github.com/user-attachments/assets/9a836988-c9da-475e-ba97-6961f2052b18">

So it is definitely being picked up. And as per the above, my lazygit config in `$XDG_CONFIG_HOME/lazygit/config.yml` (full details [here](https://github.com/shamindras/dotfiles/blob/main/config/lazygit/config.yml)) is also non-empty.

It's quite strange, when I open up lazygit on a repo, click on the [1] bar, and then click `o` to open config, it takes me to my custom `XDG` config, however the settings are not being applied. See this screenshot:

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/bc09db6d-d283-4648-b815-86ee6750d240">

Is there something wrong with my [`config.yml`](https://github.com/shamindras/dotfiles/blob/main/config/lazygit/config.yml)?

**Reply by mgray88** [reply]
Hmm. I tried your config.yml and it loaded just fine.

I don't know how lazygit works under the hood, but maybe it's running a non-interactive shell session when starting up? Which means it wouldn't load the `.zshrc` file, maybe try moving the `XDG...` declarations to the `.zshenv` file?

**Reply by shamindras** [reply]
Thanks @mgray88 - for trying out the `config.yml` and your follow up. Appreciate it.

It is interesting. It appears that my `config.yml` _**is**_ largely working,  apart from the two options I noted in my original post. Namely, the [NerdFontIcons](https://github.com/shamindras/dotfiles/blob/main/config/lazygit/config.yml#L4) are not working, and the [rounded borders](https://github.com/shamindras/dotfiles/blob/main/config/lazygit/config.yml#L43) are not working when changing the borders to `"rounded"`.

Are these working for you? As noted above, I'm using Alacritty with the `JetBrainsMono Nerd Font`, and icons are working with say `eza`. Also `"single"` borders work, but not `"rounded"`. I get the `+` sign effect shown in my screenshots above. The same issues occur when I use `lazygit` in the vscode terminal. So it is not related to the terminal used or NerdFonts showing in the terminal, but for `lazygit` itself. 

Are you seeing NerdFont icons and rounded corners?

**Reply by mgray88** [reply]
Yep, icons and rounded borders are all working fine. I'm also in alacritty with the same font. I just noticed in your original post your lazygit version is a minor release behind than mine, maybe try upgrading that? This is mine:
```
❯ lazygit --version
commit=2d0c7cb0fc85e3c262837eb9691813fa97e00e80, build date=2024-09-07T02:26:26Z, build source=binaryRelease, version=0.44.0, os=darwin, arch=arm64, git version=2.39.3 (Apple Git-146)
```

**Reply by shamindras** [reply]
Thanks for confirming @mgray88. Really appreciate your help.

I've been regularly updating the lazygit version since my first post, and have been relying on homebrew.

```bash
➜ lazygit --version
commit=, build date=, build source=homebrew, version=0.44.1, os=darwin, arch=amd64, git version=2.46.1
```

This is the most recent version (using `brew`) at `0.44.1`, though it appears that you are buiding from source(?). I may now file an issue for this, may be an issue for macOS set up I have.


<details>
	<summary>macOS specs</summary>

```bash
shamindras@Shamindras-MacBook-Pro-2
-----------------------------------
OS: macOS Sonoma 14.6.1 x86_64
Host: MacBook Pro (16-inch, 2019)
Kernel: Darwin 23.6.0
Uptime: 7 hours, 40 mins
Packages: 283 (brew), 43 (brew-cask)
Shell: tac
Display (Color LCD): 3584x2240 @ 60 Hz (as 1792x1120) in 16‚Ä≥ [Built-in]
DE: Aqua
WM: Quartz Compositor
WM Theme: Multicolor (Dark)
Font: .AppleSystemUIFont [System], Helvetica [User]
Cursor: Fill - Black, Outline - White (32px)
Terminal: WezTerm 20240203-110809-5046fc22
Terminal Font: JetBrainsMono Nerd Font
CPU: Intel(R) Core(TM) i9-9980HK (16) @ 2.40 GHz
GPU 1: Intel UHD Graphics 630 [Integrated]
GPU 2: AMD Radeon Pro 5500M [Discrete]
Memory: 18.24 GiB / 64.00 GiB (28%)
Swap: Disabled
Disk (/): 320.06 GiB / 1.82 TiB (17%) - apfs [Read-only]
Local IP (utun4): 10.5.0.2/16
Battery (bq40z651): 81% [AC connected, Charging]
Power Adapter: 60W
Locale: C
```

</details>

**Comment by shamindras** [comment, marked as answer]
After returning to this issue for several months, I recently found a fix. Just need to ensure that the zsh is set up to handle unicode characters in the terminal. To do that just include the following in your `zshrc`:

```zsh
# Encodings, languges and misc settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=UTF-8

export TERM=xterm-256color
```

Then the [above config](https://github.com/jesseduffield/lazygit/discussions/3884#discussion-7122483) with `nerdFontsVersion: "3"` (and additional settings) should work.

Very happy to have this resolved. For transparency I did use [claude.ai](https://claude.ai/) to assist with the debugging and it suggested this fix.

Hope this helps others resolve this issue!

**Reply by giovuddu** [reply]
can you please explain the additional settings? and the current config you have for lazygit?

**Reply by shamindras** [reply]
@giovuddu - per my previous post, the main changes needed to solve my original icon rendering issue is as follows.

I basically added these three lines to my `~/.zshrc`:

```bash
# Encodings, languges and misc settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=UTF-8

export TERM=xterm-256color
```

This makes the required lazygit unicode icons appear in the terminal. In my case, I was missing the line `export LC_CTYPE=UTF-8`.

And my lazygit `config.yml` is as follows:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  # showFileIcons: true
  # showIcons: true
  # use the mocha catpuccin theme
  # see: https://github.com/catppuccin/lazygit#usage
  theme:
    # lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: rounded
  authorColors: # in case you're not happy with the randomly assigned colour
    "shamindras": "#9db5bf"
    "SS": "#9db5bf"
  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: true # stuff relating to the UI

# use delta for git diffs
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers --paging=never
    useConfig: false

# use conventional commits via commitizen
# source: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#committing-via-commitizen-cz-c
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

# TODO switch from `vim` to `nvim`
os:
  editCommand: "vim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"
```

Since I tweak my dotfiles frequently, [here](https://github.com/shamindras/dotfiles) is a full link to them for your reference. Here is the [lazygit config](https://github.com/shamindras/dotfiles/blob/main/config/lazygit/config.yml) and here is the [zshrc](https://github.com/shamindras/dotfiles/tree/main/config/zsh).

Hope that helps!
