### DISCUSSION TITLE
Push only some commit

### DISCUSSION THREAD

**Discussion by noahfraiture** [jesseduffield/lazygit#4081] [Q&A] [answered]
Hello,
I've done that with git anyway, but I know it is possible from that https://stackoverflow.com/questions/604399/how-do-you-push-only-some-of-your-local-git-commits
Does lazygit allow to do that ? If no, could I make a PR and wouldn't that be too hard considering how is the code organized

**Comment by stefanhaller** [comment, marked as answer]
This is not currently possible. As for making a PR, I'd say the challenge is not so much "how the code is organized", but rather how the UX is designed. Have you thought about that? If you were thinking that you would select a commit in the Commits panel and then hit shift-P to push that commit, then that's not an option. This would be a breaking change, since currently you can hit shift-P anywhere to push the current branch without having to pay attention to what is selected. So it would have to be a different keybinding; however, I'm not convinced the feature is important enough to spend a keybinding on it.

You can approximate the behavior with a custom command like this:
```yaml
    - key: (whatever)
      command: 'git push `git for-each-ref --format="%(upstream:remotename)" "$(git symbolic-ref -q HEAD)"` {{.SelectedCommit.Hash}}:`git for-each-ref --format="%(upstream:remoteref)" "$(git symbolic-ref -q HEAD)"`'
      context: "commits"
      description: "Push selected commit"
      stream: true
```
