### DISCUSSION TITLE
A simple way to generate AI commit messages, implemented purely in shell without the need to install any language runtime.

### DISCUSSION THREAD

**Discussion by tbxark** [jesseduffield/lazygit#4100] [Ideas]
1. Install [`shell-ask`](https://github.com/TBXark/shell-ask), a pure bash script AI tools
2. Set OpenAI API key `ask set-config api_key sk-xxxx`, If you are using other AI providers, please check the document.
3. Install `ask install-plugin https://raw.githubusercontent.com/TBXark/shell-ask/master/plugins/commit.sh`
4. Add custom command for **lazygit** 
```yaml
customCommands:
  - key: "<c-a>"
    command: "ask -p commit | tr -d '\n' | tee >(pbcopy)"
    context: "files"
    loadingText: "Generating commit message..."
    description: "Generated commit message by AI"
    stream: false
    subprocess: false
    showOutput: true
    outputTitle: "Commit Message (Copied)"
    background: true
```
![preview](https://github.com/user-attachments/assets/59321314-a6f7-4ec9-b7f4-8f102929860f)

When you press `Control + a` in the `Files` area, it will automatically request the AI to obtain a commit message, copy it to the clipboard, and then display it in a pop-up window.

Of course, the `pbcopy` here only works on macOS, if you are using another system, you may need to replace it with the corresponding clipboard tool.
