### DISCUSSION TITLE
Custom commit command

### DISCUSSION THREAD

**Discussion by rodhash** [jesseduffield/lazygit#4139] [General]
Hi

Hope this isn't duplicated, couldn't find one already.

I'm working to create a custom command and so far I got this:
```yaml
  - key: 'C'
    description: "custom Commit"
    prompts:
      - type: 'input'
        title: 'Commit message'
        initialValue: ''
      - type: 'input'
        title: 'Description'
        initialValue: ''
    command: "git commit xxxxxxx"
    context: 'files'
    loadingText: 'committing..'
```

Which works fine but here I get the 2nd input field after I enter the data in the 1st one.

How can I show both at the same time similarly to what "c" does?

"c" key shows two input at the same time, `Commit summary` and `Commit description` which has a larger height .. couldn't find in the docs how to mimic this layout with two inputs and one having a larger height value.

Any suggestion?

Thanks and kudos for this great project!
