### DISCUSSION TITLE
How can I remap the Scroll up/down main window keys?

### DISCUSSION THREAD

**Discussion by David-Else** [jesseduffield/lazygit#4173] [Q&A]
Hi. I found https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md, but I can't find a list of commands that I can call using the custom keybinds.

How can I remap Scroll up/down main windows to use ctrl+j/k instead of shift+j/k? Thanks!

**Comment by jesseduffield** [comment]
Remapping keys is different to adding custom commands. Check out the config docs for keybinding keys that you can override: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md.

I believe this should do the trick:
```yml
keybindings:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>
```
