### DISCUSSION TITLE
when using side-by-side diff show the full file

### DISCUSSION THREAD

**Discussion by HyGy** [jesseduffield/lazygit#4202] [General]
Is there a solution to display the full files when using the side-by-side diff? Or attach the  --unified=9999999 parameter to the git diff command?

I tried with:
```
gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side
git:
  paging:
    colorArg: never
    pager: ydiff -p cat -s --wrap --width={{columnWidth}}
```

and with delta:
```
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
```

**Comment by mattbarlow-sg** [comment]
I would like this too. To work around this I configured a custom command that shows the git diff in neovim.

```yaml
promptToReturnFromSubprocess: false
customCommands:
  - key: 'v'
    command: 'nvim {{.SelectedFile.Name}} -c "lua require(\"gitsigns\").toggle_deleted()"'
    context: 'files'
    description: 'Open in Neovim and show diff'
    output: terminal
```

Requires [gitsigns](https://github.com/lewis6991/gitsigns.nvim) to be installed.
