### DISCUSSION TITLE
Is it possible to change the hex value of default colors?

### DISCUSSION THREAD

**Discussion by GP4cK** [jesseduffield/lazygit#4294] [Q&A] [answered]
For example, the `blue` doesn't stand out very much in my terminal because of the background...

**Comment by mark2185** [comment]
You can specify your own colors instead ([docs](https://github.com/jesseduffield/lazygit/blob/56c9d5abeb3544619451f0cf85823b1f179c6157/docs/Config.md?plain=1#L763-L773)):
``` 
gui:
  theme:
    selectedLineBgColor:
      - '#ff00ff'
````
