### DISCUSSION TITLE
Lazygit hanging due to Commitizen

### DISCUSSION THREAD

**Discussion by jaredmcateer** [jesseduffield/lazygit#4344] [Q&A]
A bunch of repos in our org have `prepare-commit-msg` hooks (via husky) that enforce conventional commits via commitizen, whenever this is triggered LazyGit will hang. This is sort of fixed by using <kbd>Shift</kbd>+<kbd>c</kbd> when committing but is still broken on rebase & merge actions. 

I end up having to kill the process and then fix it in via command line. I'm often in vim when this happens so it also creates a mess of my workspace if I have unsaved files open. It's driving me bonkers.

Right now I have a custom command for merging

```
customCommands:
  - key: "m"
    context: "localBranches"
    command: "HUSKY=0 git merge --no-edit --ff {{.SelectedLocalBranch.Name}}"
    description: "Merge without husky"
```
I'd rather not have to override a repos hook rules as there can be other things its doing that I still want to run (lint, tests, etc). Additionally I don't get the other merge options unless I manually rewrite all the menus for merge/rebase. Before I do so is there a way to make LazyGit and CZ play nice with each other?
