### DISCUSSION TITLE
Quit from custom commands

### DISCUSSION THREAD

**Discussion by noahfraiture** [jesseduffield/lazygit#4399] [Q&A]
Hello,
I don't see anything in the custom commands to quit lazygit. I want to integrate lazygit in helix like it can be done in yazi https://github.com/sxyazi/yazi/pull/2461 and thus I have the following lazygit command
```
          key = "o";
          context = "files";
          command = "echo {{ .SelectedFile.Name }} > /tmp/lazygit-path; exit";
          description = "Write the path in tmp file to be open with helix";
```

And this helix command
```
            "l" = [
              ":sh rm -f /tmp/lazygit-path"
              ":write-all"
              ":new"
              ":insert-output lazygit"
              '':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty''
              ":buffer-close!"
              ":open %sh{cat /tmp/lazygit-path}"
              ":redraw"
              ":reload-all"
              ":set mouse false"
              ":set mouse true"
            ];
```

However the `exit` in the command doesn't work obviously because under the hood it's a command bash `bash -c` and it's that process that exit. A solution is to use a signal with something like `...; kill $PPID` but it's probably not the best way as generate an error. 
Is there another solution or is there a good signal to use ? 

This is a little bit of topic but I ask here if someone know, after doing this helix trick, the terminal is buggy and pressing the escape command in lazygit doesn't exist a menu, but print `[27u`. Do you know where that comes from ?

**Comment by pandalec** [comment]
I use this in my helix/config.toml:

```toml
g = [
  ":sh rm -f /tmp/lazygit-path",
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":buffer-close!",
  ":open %sh{cat /tmp/lazygit-path}",
  ":redraw",
  ":reload-all",
  ":set mouse false",
  ":set mouse true",
]
```

and my lazygit config.yml:

```yaml
os:
  # Command for editing a file. Should contain "{{filename}}".
  edit: "echo {{filename}} > /tmp/lazygit-path; kill -TERM $(pidof lazygit)"

  # Command for editing a file at a given line number. Should contain
  # "{{filename}}", and may optionally contain "{{line}}".
  editAtLine: "echo {{filename}}:{{line}} > /tmp/lazygit-path; kill -TERM $(pidof lazygit)"
```

Works so far :)
