### DISCUSSION TITLE
Is there any way to customize "open" or "editAtLine" and pass a commit hash?

### DISCUSSION THREAD

**Discussion by Blankeos** [jesseduffield/lazygit#4471] [Q&A]
Currently, Zed just released https://x.com/zeddotdev/status/1910053786787430745 v0.181.5 - Supports viewing Files in Zed from an old commit hash.

Though I'm not aware of any CLI args to open diffs via a commandline with Zed (yet) (i.e. `zed {{filename}} --diff "{{hash}}..{{hash}}"`. I do think that once it's possible, I was thinking it would be super convenient if Lazygit can integrate with it by also passing a `{{commit_hash}}` in the `os.open` and `os.editAtLine` and `os.editAtLineAndWait` so it can integrate with Zed better.

Currently this is what is possible with Lazygit + Zed:
```
os:
  open: "zed {{filename}}"
  edit: "zed {{filename}}"
  editAtLine: "zed {{filename}}:{{line}}"
  editAtLineAndWait: "zed {{filename}}:{{line}} --wait"
  openDirInEditor: "zed {{filename}}"
```

Maybe in the future, this might be possible too:
```
os:
  open: "zed {{filename}} --diff {{commit_hash..HEAD}}"
  editAtLine: "zed {{filename}} --diff {{commit_hash..HEAD}}"
```

I was reading the [Configuration guide](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) but I couldn't really find anything on passing the commit_hash (if it was possible).

Thanks in advance guys!
