### DISCUSSION TITLE
Alt key not working correctly on macOS/iTerm (specifically <a-enter>)

### DISCUSSION THREAD

**Discussion by itsonlyjames** [jesseduffield/lazygit#4576] [Q&A] [answered]
For some reason when lazygit is open, my alt key does not get recognised whether by `alt + backspace` to whole delete words, or `alt + enter` to commit from the commit description (`<a-enter>`). Weirdly, `alt + left/right` does work correctly and moves the cursor around whole words. 

I've checked iTerm settings and confirmed that alt does work correctly, as in when outside of lazygit I can `alt + backspace` to delete words and `alt + left/right` to traverse whole words. 

```yml
os:
  editPreset: "nvim"

gui:
  theme:
    activeBorderColor:
      - "#f38ba8"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f38ba8"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
```

Thanks for any help!
