### DISCUSSION TITLE
Start a commit without needing to focus the files pane?

### DISCUSSION THREAD

**Discussion by NextMerge** [jesseduffield/lazygit#4670] [Q&A]
I'd like to be able to always start a commit without needing to focus the files pane specifically. Often I forget I'm in the branches pane and only realize I opened the wrong modal after typing out a commit message.

Doesn't seem like I can set a bind for it outside the files pane:

```
keybinding:
  universal:
    commitChanges: c
  branches:
    commitChanges: c
```
