### ISSUE TITLE
Can I have a full screen mode to view diff?

### ISSUE THREAD

**Issue by xaljer** [jesseduffield/lazygit#1113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jesseduffield** [comment]
if you go shift+`+` couple times after pressing enter on a file it should go full screen. Does that satisfy your use case?

**Comment by xaljer** [comment]
@jesseduffield I didn't get the full screen effect follow your description~

**Comment by dakyskye** [comment]
Yup, it never lets you focus on "diff" window, so you can't make it go fullscreen. Would be cool if we had that.

**Comment by jesseduffield** [comment]
pressing enter on a file takes you to the diff window. Admittedly there isn't a generic way to focus the main window though

**Comment by AbeerVaishnav13** [comment]
Yes, the ability to focus on the diff window and making it larger would be very helpful indeed!!

**Comment by mbhutton** [comment]
I'm using this in my lazygit config file as a workaround, which makes `ctrl-f` show the selected commit in a subprocess, then press `ENTER` to exit back to lazygit. 

```
customCommands:
  - key: '<c-f>'  # Ctrl-f (think "full screen") to show selected commit
    context: 'commits'
    command: "git show {{.SelectedLocalCommit.Sha}}"
    subprocess: true
    description: "Show selected commit"
    stream: true
```

**Comment by nikbrunner** [comment]
Is this somehow possible now?

**Comment by konosubakonoakua** [comment]
when using `difft`, I found that if we focus the patch window, the diff tool fallback to default `diff`.
the keymap does no help to keep `difft` too. https://github.com/jesseduffield/lazygit/issues/1113#issuecomment-1879886174

**Comment by nikbrunner** [comment]
> when using `difft`, I found that if we focus the patch window, the diff tool fallback to default `diff`. the keymap does no help to keep `difft` too. [#1113 (comment)](https://github.com/jesseduffield/lazygit/issues/1113#issuecomment-1879886174)

Thank you this is helpful! I scoped it to files though, because what I would really like to achieve is to have the diff in full view and step through the diff and be able to stage hunks. But this is an improvement. :) I hope this there will be a possibility for this in the future.

**Comment by wenjoy** [comment]
This issue should get high votes

**Comment by jan-swiecki** [comment]
> pressing enter on a file takes you to the diff window. Admittedly there isn't a generic way to focus the main window though

This is not enough if you want to scroll through full diff of a commit. This is useful to quickly check what does given commit change (basically what `git show` does).

**Comment by kostyafarber-az** [comment]
+1 this would be a major reason for me not to use the tool, as a have to do a gloss through before pushing and the wrapped lines make it hard to scan the changes.

**Comment by nasxisbest** [comment]
+1

**Comment by madhur** [comment]
This one is really needed

**Comment by partiallyordered** [comment]
> I'm using this in my lazygit config file as a workaround, which makes `ctrl-f` show the selected commit in a subprocess, then press `ENTER` to exit back to lazygit.
> 
> ```
> customCommands:
>   - key: '<c-f>'  # Ctrl-f (think "full screen") to show selected commit
>     context: 'commits'
>     command: "git show {{.SelectedLocalCommit.Sha}}"
>     subprocess: true
>     description: "Show selected commit"
>     stream: true
> ```

Using delta, I had to set `--paging=always`. Command config:
```yaml
customCommands:
- command: git -c core.pager="delta
    --syntax-theme gruvbox-dark --dark --side-by-side --paging=always" diff {{.SelectedLocalCommit.Sha}}^
    {{.SelectedLocalCommit.Sha}}
  context: commits
  description: full-screen diff of selected commit
  key: <c-f>
  stream: true
  subprocess: true
```
