### ISSUE TITLE
Doesn't show all colors that pager can support

### ISSUE THREAD

**Issue by theblazehen** [jesseduffield/lazygit#1136]
**Describe the bug**

Color when running delta as a pager doesn't match the color shown inside lazygit when line-numbers is enabled for git-delta

**To Reproduce**
Configure your git pager as 
```
[core]
	pager = delta --dark --24-bit-color=never
[delta]
    features = line-numbers
```
Then run `git log` in a repository.

Then configure lazygit as
```
git:
  paging:
    # colorArg: always # I have tried with and without this value
    pager: delta --dark --paging=never --24-bit-color=never
```
And it looks different.

**Expected behavior**
The output should look the same.

**Screenshots**
Screenshot of `git log -p` output:
![image](https://user-images.githubusercontent.com/3276410/103636325-7abc3780-4f52-11eb-86dd-7832cdfbe425.png)

Screenshot of lazygit output:
![image](https://user-images.githubusercontent.com/3276410/103636407-96bfd900-4f52-11eb-964b-9afeeb8fb5d6.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Lazygit Version: 0.24.2
