### ISSUE TITLE
log with more details

### ISSUE THREAD

**Issue by c02y** [jesseduffield/lazygit#1165]
**Is your feature request related to a problem? Please describe.**

I need some log list like `git log --graph --all --color=always --decorate --date=relative  --pretty=medium --stat` which lists log with commit+files+extra-info of all commits inside lazygit, so I add some command like 
``````
customCommands:
  - key: 'L'
    command: "git log --graph --all --color=always --decorate --date=relative  --pretty=medium --stat"
    context: 'global'
    subprocess: true
    description: 'full log'
``````
But the result of the command cannot interact with lazygit such as Enter the point to view the exact changes of the commit(I miss tig about this feature)

Is this able to be done with lazygit? Or it would better if it is a builtin tab into "Commits -- Reflog" section. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
