### ISSUE TITLE
ydiff not working - 0.25.1

### ISSUE THREAD

**Issue by cmario92** [jesseduffield/lazygit#1176]
**Describe the bug**
Following the instructions on https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md, I can not get ydiff to work.

**To Reproduce**
1. Go to lazygit
2. Switch to the 'Files' section
3. See that the changes are showing as xdiff not ydiff

**Expected behavior**
After adding the below configuration as instructed on docs, I should be able to see the diff in y-scale.
```yml
gui:
    paging:
       colorArg: always
       pager: ydiff -p cat -s --wrap --width={{columnWidth}}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Lazygit Version - 0.25.1
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
Please advice if there is something extra that needs to be added in the config.yml file
