### ISSUE TITLE
New `showFileTree` option not working

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#1251]
**Describe the bug**
I saw in the release notes about new `showFileTree` option. I wanted to give it a try, but it doesn't seem to work

**To Reproduce**
1. Use this config:
```yml
gui:
  theme:
    lightTheme: true
    activeBorderColor:
    - cyan
    - bold
    inactiveBorderColor:
    - default
  showFileTree: true
```
2. Open lazygit
3. Go to files panel, try pressing tilde, nothing happens

**Expected behavior**
Expected to get the tree view. I saw it initially in the PR you mentioned me on screenshot and wanted to give it a try
https://user-images.githubusercontent.com/8456633/114300325-1d142a00-9b03-11eb-824b-a747b1f64e0c.png

**Screenshots**
![screenshot](https://i.imgur.com/seiuvWw.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Lazygit Version - Latest master, commit 069c7c9d3583c15aea34c08ff7c8be299c94f60d
