### ISSUE TITLE
Key bindings for `checkoutCommit` don't seem to work?

### ISSUE THREAD

**Issue by garymh** [jesseduffield/lazygit#1278]
**Describe the bug**
Key bindings don't seem to be remappable for the commit section, namely: `checkoutCommit` and `goInto`. I'm trying to swap so <enter> checks out the branch and space examines the commits.

**To Reproduce**
1. Using the following config file:
```yaml
keybinding:
  status:
    files:
      branches:
        commits:
          checkoutCommit: '<enter>'
          goInto: '<space>'
```
2. Open lazygit
3. Go to commits section
4. Press <enter>
5. List of commits

**Expected behavior**
I would expect to checkout the branch with the yaml provided

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version 0.27.4

Hopefully I'm just missing something obvious 😅

**Comment by ChrisMcD1** [comment]
/close

This issue is super stale, so I'm closing. 

The question seems a bit fractured between talking about behavior I expect out of the "Local Branches" tab, and behavior I expect out of the "Commits" tab. (Although this might of been how LazyGit behaved 4 years ago, I wasn't using it then)

`goInto` is behavior from the "Local Branches" tab, which is only configured via the global `goInto` keymap, so if you wanted that to behave with `<space>` you would do.

```yaml
keybinding:
  universal:
    goInto: '<space>'
```

`checkoutCommit` is only available via the "Commits" tab and would then be configured via:
```yaml
keybinding:
  commits:
    checkoutCommit: '<enter>'
```

If what you actually desire is for checking out in the "Local Braches" tab, that is controlled via the global `select` keybinding, so you could configure it via

```yaml
keybinding:
  universal:
    select: '<enter>''
```

which I just tested on LazyGit `0.48.0`. There are no plans to do separate keybindings for these actions for the branch menu, so global is the way to go!
