### ISSUE TITLE
Commit tab blinking commit hash & file names

### ISSUE THREAD

**Issue by justisGipson** [jesseduffield/lazygit#1302]
**Topic**
Is there a way to toggle the blinking? In the `commit` tab, there's a box around the commit hash that blinks, and each file name in the commit tab blinks.

On: 
- 2020 intel mbp
- big sur 11.3
- lazygit v0.28.1

**Your thoughts**
Just started using lazygit yesterday, and I love it. Except for the blinking. I dug through the readme and config docs, couldn't find anything to trigger this. Also saw a couple issues where folks had a blinking issue and an upgrade resolved it. This is why I opened a `discussion`, wasn't sure if this was a bug or config error.

and my lazygit config:
```yaml
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

if needed I can grab a video or something.

**Comment by justisGipson** [comment]
I was able to turn this off in iTerm2 settings -> profile -> text -> toggle blinking text. I didn't realize that was on, but lazygit is also the only thing I've seen trigger the blinking text.

If this isn't worth a discussion, I can close. If it's an actual bug/feature that needs worked on, I could try to figure it out.

**Comment by geins** [comment]
Same issue and same solution here. But also a strange problem where the colors of diff-so-fancy _emulation_ of delta are waaaay off.

How it looks in lazygit (blinking off by iTerm)
![delta](https://i.imgur.com/gq7Nggi.png)

while git diff shows it right:
![delta2](https://i.imgur.com/kzfoGnX.png)

config.yml is
```
  paging:
    colorArg: always
    useConfig: false
    pager: delta --paging=never
```

.gitconfig is
```
[core]
  pager = delta
[interactive]
  diffFilter = delta --color-only
[delta]
  features = line-numbers diff-so-fancy
```

Thank You so much!
