### ISSUE TITLE
customCommand keybinding misinterpreted

### ISSUE THREAD

**Issue by kiesel** [jesseduffield/lazygit#1319]
**Describe the bug**
I have the following custom command:

```yaml
        - key: '<c-m>'
          command: 'lab mr create --remove-source-branch --assignee adandrea --squash --draft'
          context: 'files'
          subprocess: true
```

However, when I'm in the files pane and display help, it shows up as `enter   lab mr create ...`, and also triggers when pressing enter (which is actually supposed to bring me into the diff view).

Pressing Ctrl-m does also invoke my custom command, so it somehow works.

**To Reproduce**
Put custom command into config, go to files, press Enter.

**Expected behavior**
Should bring me to diff view.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Lazygit Version `commit=v0.28.1, build date=2021-04-26T21:39:48Z, build source=binaryRelease, version=0.28.1, os=linux, arch=amd64`
