### ISSUE TITLE
How can i change color of the filename in Unstaged Changes area?

### ISSUE THREAD

**Issue by RakshithNM** [jesseduffield/lazygit#1342]
**Topic**
It is hard to read the file name in the unstaged area and i am not sure how to change the color there

**Your thoughts**
My ~/.gitconfig for color is this
```
[color]
    ui = auto
[color "branch"]
    current = yellow reverse
    local = yellow
    remote = green
[color "diff"]
    meta = yellow bold
    frag = magenta bold
    old = red bold
    new = green bold
[color "status"]
    added = yellow
    changed = green
    untracked = cyan
```
Not really sure what sets the color of th file name in the unstaged changes area, i am including a screenshot of lazygit. 
(Not really sure if this qualifies to be discussion but i was wondering if there is a way to change the color, please suggest)

Thank you

![Screenshot 2021-05-29 at 3 37 56 PM](https://user-images.githubusercontent.com/10560321/120066415-d8812580-c093-11eb-84bf-a2a094b2847a.png)

**Comment by RakshithNM** [comment]
I managed to load the ~/.gitconfig by using `useConfig: true` option, now the text seems to be visible becuase it picks the color from the config, but it is a bit slow, but i can work with that

**Comment by RakshithNM** [comment]
actually no, it gets slower as the size of the file increases. Is there something i am missing. Can this be made more performant?

**Comment by mjarkk** [comment]
@RakshithNM can you share your lazygit config?

**Comment by RakshithNM** [comment]
@mjarkk i have been using diff-so-fancy and the issue is not there anymore. i forgot to update here.

```
startuppopupversion: 1
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
gui:
  theme:
    optionsTextColor:
      - yellow
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
```
