### ISSUE TITLE
Support for quering refs in custom commands!

### ISSUE THREAD

**Issue by FoamScience** [jesseduffield/lazygit#1388]
First of all, thanks for building such a useful piece of software; been using lazygit for a while and I really like it!

## Is there a way to (dynamically) generate menu entries out of remote branches for example

I have this custom command in my config:
```
  - key : 'r'
    description: 'Checkout a remote ref as FETCH_HEAD'
    command: "git fetch {{index .PromptResponses 0}} {{index .PromptResponses 1}} && git checkout FETCH_HEAD"
    context: 'remotes'
    prompts:
      - type: 'input'
        title: 'Fork:'
        initialValue: "{{index .SelectedRemote.Name }}"
      - type: 'input'
        title: 'Remote branch on fork:'
```
Which actually fetches some branch from a remote and then checks out the head of that branch (Useful in evaluating PRs
before merging outside Github world).
I was wondering if I can (instead of using input prompts) generate a menu prompt where options are populated
by running a command (say `git branches` for example) instead of explicitly listing them in the config section.

I'm looking for something like this:
```
  - key : 'r'
    description: 'Checkout a remote ref as FETCH_HEAD'
    command: "git fetch {{index .PromptResponses 0}} {{index .PromptResponses 1}} && git checkout FETCH_HEAD"
    context: 'remotes'
    prompts:
      - type: 'input'
        title: 'Fork:'
        initialValue: "{{index .SelectedRemote.Name }}"
      - type: 'menu'
        title: 'Remote branch on fork:'
        optionsFromCommand: 'git branch  -r --list {{index .PromptResponses 0}}/*'
```

[Line 112 from custom_commands.go](https://github.com/jesseduffield/lazygit/blob/06a8eb115c100816e3ceccff875010a84416beee/pkg/gui/custom_commands.go#L112) kind of says i can't do this unless I add a new case in there.

So, how to capture the output of `gui.OSCommand.PrepareShellSubProcess(cmdStr)` as a string?
