### ISSUE TITLE
How to execute some Git commands via lazygit

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#1424]
**Topic**
How to execute the following Git commands via lazygit? Does lazygit support?
`git commit --amend --author="Author Name <email@address.com>"`
`git fetch someoneRemote branchName:myBranchName`

**Comment by Liberatys** [comment]
Hey @Tim-Cao! Have a look at https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium. This should give you all the information you need to implement the commands yourself :D

**Comment by Tim-Cao** [comment]
```
customCommands:
  - key: '<c-f>'
    description: 'fetch a remote branch as a new local branch'
    command: "git fetch {{index .SelectedRemote.Name }} {{index .PromptResponses 0}}:{{index .PromptResponses 1}}"
    context: 'remotes'
    prompts:
      - type: 'input'
        title: 'Remote Branch Name'
        initialValue: ''
      - type: 'input'
        title: 'New Local Branch Name'
        initialValue: ''
    loadingText: 'fetching branch'
  - key: '<c-c>'
    description: 'commit as non-default author'
    command: 'git commit -m "{{index .PromptResponses 0}}" --author="{{index .PromptResponses 1}} <{{index .PromptResponses 2}}>"'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Commit Message'
        initialValue: ''
      - type: 'input'
        title: 'Author Name'
        initialValue: ''
      - type: 'input'
        title: 'Email Address'
        initialValue: ''
    loadingText: 'commiting'
  - key: '<c-a>'
    description: 'amend the author of last commit'
    command: 'git commit --amend --author="{{index .PromptResponses 0}} <{{index .PromptResponses 1}}>"'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Author Name'
        initialValue: ''
      - type: 'input'
        title: 'Email Address'
        initialValue: ''
    subprocess: true
```

Thanks @Liberatys
The above custom commands I implement work in **ubuntu** while the second and third don't work in **windows**.
It will throw the following error
![image](https://user-images.githubusercontent.com/52661397/147341821-8c986f10-8f49-437e-a43c-fb9447e611ab.png)
Do you have any idea?
