### ISSUE TITLE
Commit prefix is removed after clicking any key

### ISSUE THREAD

**Issue by ecosse3** [jesseduffield/lazygit#1544]
**Describe the bug**
After last update of 0.30 when I use commit prefixes in Lazygit, each time I try to fill commit message it removes my prefix after clicking any key. Also second time it duplicated previous typed message when I click arrow key

**To Reproduce**
1. Set commit prefix
2. Make commit message and click any key

**Expected behavior**
It should not clear the input for a commit message. I would like to use my arrow keys to move to the end of line and fill message.

**Screenshots**

https://user-images.githubusercontent.com/17691791/138663383-8b7fa3c8-804e-4a97-87ca-e13a01a2b7a8.mp4

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7, os=darwin, arch=amd64
 - Lazygit Version: 0.30
 - The last commit id if you built project from sources: 3eb124c732326d3680465c864fe6d0c1422d07bd

**Additional context**
My commit prefix config:
```
 commitPrefixes:
      project: # This is repository folder name
        pattern: "^\\w+\\/(\\w+)"
        replace: "#$1 "
```
