### ISSUE TITLE
Side by Side diffs

### ISSUE THREAD

**Issue by hipstersmoothie** [jesseduffield/lazygit#155]
**Is your feature request related to a problem? Please describe.**

I'm way better at reading side by side diffs

**Describe the solution you'd like**

LazyGit can be configured to show side by side diffs

**Comment by jesseduffield** [comment]
see https://github.com/jesseduffield/lazygit/pull/161

**Comment by jesseduffield** [comment]
This has now been implemented. See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md

If anybody would like to see changes to the feature, let me know :) closing

**Comment by haydenflinner** [comment]
Is there a minimal example of how to get side by side diffs from this custom pager support? from the pictures it looks like ydiff will do the trick, is that the best option?

**Comment by iklobato** [comment]
For those who are new at lazygit

1. Open the configuration file
```
Linux: ~/.config/lazygit/config.yml
MacOS: ~/Library/Application\ Support/lazygit/config.yml
Windows: %LOCALAPPDATA%\lazygit\config.yml (default location, but it will also be found in %APPDATA%\lazygit\config.yml
```
```
Linux: ~/.config/jesseduffield/lazygit/config.yml
MacOS: ~/Library/Application\ Support/jesseduffield/lazygit/config.yml
Windows: %APPDATA%\jesseduffield\lazygit\config.yml
```
2. Add the snipper from @haydenflinner 
```
git: 
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme base16-256 -s
```
3. Close and reopen lazygit

**Comment by dhupee** [comment]
For those who used NixOS, you can use example from my dotfiles https://github.com/dhupee/dotfiles/blob/master/private_dot_nix-configs/modules/home-manager/git.nix

I reference @ iklobato comment and applied that in NixOS, great job

**Comment by hk0i** [comment]
@iklobato what about when we go into a single file to stage changes? mine doesn't appear to be using the custom pager for that.
I mainly want the syntax highlighting from `delta`:

<img width="1636" alt="Image" src="https://github.com/user-attachments/assets/5529b70f-4aa8-441b-9a89-7f00016e7362" />

**Comment by hk0i** [comment]
never mind looks like that's not possible, according to https://github.com/jesseduffield/lazygit/discussions/1335#discussioncomment-818032

**Comment by stefanhaller** [comment]
@hk0i Some work on this has been started in https://github.com/jesseduffield/lazygit/pull/4332, but it is nowhere near finished.

**Comment by 0qln** [comment]
> For those who used NixOS, you can use example from my dotfiles https://github.com/dhupee/dotfiles/blob/master/private_dot_nix-configs/modules/home-manager/git.nix
> 
> I reference @ iklobato comment and applied that in NixOS, great job

Much love, but the link is broken. FYI, github has a feature called 'perma links'. they don't break and can be viewed any time, even if the file is removed in later commits (*°∀°)=3

**Comment by Blankeos** [comment]
Thanks for the step by step @iklobato , this is super great for me already.

Any chance this can be interactive as well or is it just purely for viewing? I basically kinda wanna copy either the entire left side or right side.

**Comment by iklobato** [comment]
Hi @Blankeos,
In this configuration, I haven’t found a way to enable editing on both sides. However, when we press `e`, it opens the most recent change so we can work on that file but only on the right side.

https://github.com/user-attachments/assets/139acfb2-fcd9-4152-a782-eb9441523c90

**Comment by Blankeos** [comment]
@iklobato Cool, I did something clever which is to make my own "copy" because `y` already almost fulfills this actually. Unfortunately, I cannot pass `context: "files"` into this customCommand, so it's just literally a global menu [(referencing this doc)](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md#menus-of-custom-commands). But you can at least add contexts in the commandMenu items.

It's this command that copies the left side of the diff:
```sh
git show HEAD:{{.SelectedFile.Name | quote}} | pbcopy
```

These were the extra configs I added:
```
customCommands:
  - key: "Y"
    description: "Custom copy: old content"
    commandMenu:
      - key: "o"
        command: "git show HEAD:{{.SelectedFile.Name}} | pbcopy"
        context: "files"
        description: "Old file content (HEAD) (left diff)"
      - key: "o"
        command: "git show {{.SelectedCommit.Sha}}^:{{.SelectedCommitFile.Name}} | pbcopy"
        context: "commitFiles"
        description: "Copy old file content (left diff)"
      - key: "c"
        command: "git show {{.SelectedCommit.Sha}}:{{.SelectedCommitFile.Name}} | pbcopy"
        context: "commitFiles"
        description: "Copy file content from this commit (right diff)"
  - key: "O"
    description: "Custom open: git show to temp and zed"
    commandMenu:
      - key: "o"
        command: 'open_dest="/tmp/lazy/{{.SelectedCommit.Sha}}_{{.SelectedFile.Name}}" && mkdir -p "$(dirname "$open_dest")" && git show HEAD:{{.SelectedFile.Name}} > "$open_dest" && zed --wait "$open_dest"'
        context: "files"
        description: "Open old file content in zed (HEAD) (left diff)"
      - key: "o"
        command: 'open_dest="/tmp/lazy/{{.SelectedCommit.Sha}}_{{.SelectedCommitFile.Name}}" && mkdir -p "$(dirname "$open_dest")" && git show {{.SelectedCommit.Sha}}^:{{.SelectedCommitFile.Name}} > "$open_dest" && zed --wait "$open_dest"'
        context: "commitFiles"
        description: "Open old file content in zed (left diff)"
      - key: "c"
        command: 'open_dest="/tmp/lazy/{{.SelectedCommit.Sha}}_{{.SelectedCommitFile.Name}}" && mkdir -p "$(dirname "$open_dest")" && git show {{.SelectedCommit.Sha}}:{{.SelectedCommitFile.Name}} > "$open_dest" && zed --wait "$open_dest"'
        context: "commitFiles"
        description: "Open file content from this commit in zed (right diff)"
      - key: "h"
        command: 'open_dest="/tmp/lazy/{{.SelectedCommit.Sha}}_{{.SelectedCommitFile.Name}}" && mkdir -p "$(dirname "$open_dest")" && git show {{.SelectedCommit.Sha}}:{{.SelectedCommitFile.Name}} > "$open_dest" && zed --diff "$open_dest" "{{.SelectedCommitFile.Name}}"'
        context: "commitFiles"
        description: "Compare file content with HEAD in zed (Note: only works if same name)"
```

This is actually perfect. Works for both viewing older commits, and just the current files.
