### ISSUE TITLE
Delta as pager with side-by-side is no longer rendering full width

### ISSUE THREAD

**Issue by simonvizzini** [jesseduffield/lazygit#1582]
**Describe the bug**
I _think_ this issue was introduced with the latest lazygit version, or maybe it is an issue with Delta itself, I'm not really sure, let me know what you think.

I have configured Delta as pager according to the documentation but now the diff is not taking up the full width as can be seen in the screenshot below.

This only happens when using Delta's "side-by-side" feature.

**To Reproduce**
1. Setup Delta as pager in lazygits config.yml:

````
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never
````

2. Check diff within lazygit and notice that its not full width anymore, see screenshot.

**Expected behavior**
Diff output should take up all the available width, like before.

**Screenshots**
Delta side by side:
![image](https://user-images.githubusercontent.com/10862380/142009005-d4bddfa0-6258-4d57-b319-f75beed80ef2.png)
Delta default:
![image](https://user-images.githubusercontent.com/10862380/142009686-7ebdecd7-c002-4129-9cf0-5e482d3bb12e.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Lazygit Version v0.31.3
 - Delta Version 0.9.2
