### ISSUE TITLE
Cannot close/confirm custom command input field

### ISSUE THREAD

**Issue by ecosse3** [jesseduffield/lazygit#1676]
**Describe the bug**
After last update of Lazygit (v...) custom command input fields doesn't recognize ESC/Enter after I type something. When it displays by first time I can close it with ESC but I cannot confirm already added initial value by Enter. If I type something, then I cannot close the input menu or confirm it. Only <Ctrl-C> terminates lazygit in terminal.

Happens only with inputs as I was able to check. Doesn't work even without initial value.

**To Reproduce**
Custom command:

```
  - key: 'A'
    description: 'Create pull request to Azure Devops'
    prompts:
      - type: 'menuFromCommand'
        title: 'Title'
        command: 'git log --walk-reflogs --no-merges {{ .SelectedLocalBranch.Name }} --pretty=%B'
        filter: '(?P<commit_message>.*)'
        valueFormat: '{{ .commit_message }}'
        labelFormat: '{{ .commit_message | yellow }}'
      - type: 'input'
        title: 'Description'
        initialValue: "{{ if .SelectedLocalBranch.Name }}Committed: #{{ .SelectedLocalBranch.Name }}{{end}}"
      - type: 'menu'
        title: 'Draft Mode'
        options:
          - name: 'no'
            value: 'false'
          - name: 'yes'
            value: 'true'
      - type: 'input'
        title: 'Work Items'
        initialValue: "{{ .SelectedLocalBranch.Name }}"
    context: 'localBranches'
    command: 'az repos pr create --delete-source-branch true --title "{{index .PromptResponses 0}}" --description "{{index .PromptResponses 1}}" --draft {{index .PromptResponses 2}} --detect true --reviewers "TEAM FE" -s "{{ .SelectedLocalBranch.Name }}" -t "staging-dev" --work-items {{index .PromptResponses 3}} --transition-work-items --open'
    loadingText: 'Creating Pull Request...'

```

**Expected behavior**
Custom commands menu should close/approve input correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/17691791/149519936-18f3e734-4d60-4e8d-89d2-574e7c9b448d.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Lazygit Version: commit=4744b39f038d9e197455dc81a55277e1b1fe0586, build date=2022-01-13T22:01:27Z, build source=binaryRelease, version=0.32, os=darwin, arch=amd64

**Additional context**
Didn't test with Lazygit 0.32 on Arch because it's not available in pacman yet.
