### ISSUE TITLE
Cannot set selectedRangeBgColor to a hex value

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#1749]
**Describe the bug**
One cannot set `selectedRangeBgColor` to a hex value.

**To Reproduce**
1. This config
```
gui:
  theme:
    selectedLineBgColor:
      - '#65321'
    selectedRangeBgColor:
      - '#654321'
```
2. The `selectedRangeBgColor` will be black.

**Expected behavior**
Both the `selectedLineBgColor` and the `selectedRangeBgColor` should be whatever `#654321` is.

**Desktop (please complete the following information):**
 - OS: archlinux latest
 - Lazygit Version: master
 - The last commit id if you built project from sources: `15ca38ba2e8cb17b342ff0273a2882d0228554a1`

**Additional context**
Jesse confirmed it on `slack`. I tried debugging, but got nowhere so I'm opening this to see what the issue was when someone else solves it (or when I finally solve it).
