### ISSUE TITLE
Assigning 'enter' key as appendNewLine does not work

### ISSUE THREAD

**Issue by birgersp** [jesseduffield/lazygit#1755]
**Describe the bug**

I am trying to assign the 'enter' key as the command to add a new line in the commit message editor. But this appears to not work, hitting 'enter' in the commit message editor does not append a new line (it seems to do nothing).

**To Reproduce**

1. Use this config:
```
# C:\Users\birge\AppData\Roaming\lazygit\config.yml
keybinding:
  universal:
    submitEditorText: '<c-k>'
    appendNewLine: '<enter>'
```
2. Open lazygit in some repo. Stage something, and hit 'c' to open the commit message editor
3. Press 'enter' to append a new line (as specified in the config)
4. Observe that nothing happens (no new line is inserted)

**Expected behavior**

A new line should be appended to the commit message text

**Desktop (please complete the following information):**
 - OS: Windows 11 (lazygit running in cmd.exe)
 - Lazygit Version 0.32.2

**Additional context**

Related(?):
https://github.com/jesseduffield/lazygit/issues/1700
https://github.com/jesseduffield/lazygit/issues/1312
