### ISSUE TITLE
[Feature Request] Turn off commit numbers or toggle side panels to make more room for side by side diff

### ISSUE THREAD

**Issue by David-Else** [jesseduffield/lazygit#1760]
I am sorry if this is already possible, but I am new to lazygit, and it is amazing!

I am using delta side by side view and have reduced the width of the side panel. I do want to know the names of the commits, but have no interest in the numbers, that is just noise. How can I remove the numbers so I have space to read the names? Maybe I could toggle the entire side panel on and off?
```
gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

![Screenshot from 2022-02-04 10-29-40](https://user-images.githubusercontent.com/12832280/152514763-1c8f819b-0d52-423c-ad4e-61ad8f954489.png)
