### ISSUE TITLE
Does not display change log of submodule with delta as custom pager

### ISSUE THREAD

**Issue by gbcwbz** [jesseduffield/lazygit#1771]
**Describe the bug**
I set delta as the pager, with following config, it will not display log of submodule
```yml
gui:
  theme:
    selectedLineBgColor:
    - reverse
git:
  paging:
      colorArg: always
      pager: delta --dark --paging=never
```
If I change the config to
```yml
gui:
  theme:
    selectedLineBgColor:
    - reverse
git:
  paging:
      colorArg: always
      pager: diff-so-fancy
```
It will display log of submodule correctly.

**To Reproduce**
1. set config `pager: delta --dark --paging=never`
2. open a git repo with submodule

**Expected behavior**
Display submodule history when submodule changes

**Screenshots**
with diff-so-fancy as custom pager, or use default pager
![image](https://user-images.githubusercontent.com/13453334/153972073-b8d80303-261d-4368-9949-89731a7bfed4.png)
with delta as custom pager
![image](https://user-images.githubusercontent.com/13453334/153972420-14dd2763-096d-45f7-8885-45334ef8b00c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Lazygit Version: 0.32
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
lazygit from ubuntu ppa
`commit=4744b39f038d9e197455dc81a55277e1b1fe0586, build date=2022-01-13T22:01:27Z, build source=binaryRelease, version=0.32, os=linux, arch=amd64`
delta version 0.4.3
