### ISSUE TITLE
Additional caret symbol is added before angle symbol on win OS

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#1772]
**Describe the bug**
If command contains angle symbol, there will be a caret symbol added before angle symbol after execute via lazygit

**To Reproduce**
1. Go to %APPDATA%\lazygit\config.yml
2. Add the following codes
```
customCommands:
  - key: '<c-a>'
    description: 'amend the author of last commit'
    command: 'git commit --amend --author="{{index .PromptResponses 0}} <{{index .PromptResponses 1}}>"'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Author Name'
        initialValue: ''
      - type: 'input'
        title: 'Email Address'
        initialValue: ''
    subprocess: true
```
3. Restart lazygit
4. Go to commits panel > Select the last commit
7. Press Ctrl + a
8. Enter Author Name
9. Enter Author email address

**Expected behavior**
Author:    Yang Cao <yang.cao@liferay.com>

**Actual behavior**
![image](https://user-images.githubusercontent.com/52661397/153989199-f747d70b-2141-4816-ac6d-31cef575f5e0.png)
It is invalid

**Desktop:**
 - OS: Windows
 - Lazygit Version [e.g. v0.32.2]
