### ISSUE TITLE
Could we make .SelectedLocalCommit.Sha support index?

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#1773]
**Is your feature request related to a problem?
I'm afraid the .SelectedLocalCommit.Sha doesn't support index.

**Describe the solution you'd like**
I tried to add a custom command **git diff --name-only sha1^..sha2**
However, .SelectedLocalCommit.Sha doesn't support index like {{index .PromptResponses 0}}
I have to use an alter solution
Here is my snippets:
```
customCommands:
  - key: '<c-f>'
    description: 'list files changed from parent commit'
    command: "git diff --name-only {{.SelectedLocalCommit.Sha}}^"
    context: 'commits'
    subprocess: true
```
