### ISSUE TITLE
Support for a custom branch name prefix when creating a new branch

### ISSUE THREAD

**Issue by moha-gh** [jesseduffield/lazygit#1810]
**Is your feature request related to a problem? Please describe.**

In most of the projects I'm working on, we use branch name prefixes so every developer has a separate "scope". If my name is 'Foo Bar', all branches I create might start with `fb/`:

```
fb/fix-this-bug
fb/add-a-new-feature
[...]
```
**Describe the solution you'd like**

I'd be great if lazygit could pre-populate the prompt that is shown when creating a new branch with this prefix automatically. For me personally, a simple, static prefix that can be configured (via an entry in the 'git' section of the config file for example), would suffice. But a more complex, per-repo solution (similar to the 'commit prefixes') would also work.

**Describe alternatives you've considered**

n/a (I've tinkered around with modifying `handleNewBranchOffCurrentItem()` to just hard-code my prefix there but that's hardly an alternative :grimacing:)

**Additional context**

n/a

**Comment by ecosse3** [comment]
You can achieve this by adding custom commands to your lazygit config. I have it already for long time and it's working great:

I can click `b` on branch from which I want to checkout to new one and I have a menu:

![image](https://user-images.githubusercontent.com/17691791/159096315-144801eb-f30a-4338-a5c3-5d29f04c76a3.png)

Then I'm providing name of branch and it's creating me `prefix/name` branch.

Add to lazygit config:

```yml
customCommands:
  - key: 'b'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it? (from {{ index .SelectedLocalBranch.Name }})'
        options:
          - name: 'bug'
            value: 'bug'
          - name: 'feature'
            value: 'feature'
          - name: 'hotfix'
            value: 'hotfix'
            description: 'If there is a need to fix a blocker, do a temporary patch, apply a critical framework or configuration change that should be handled immediately.'
          - name: 'experimental'
            value: 'experimental'
            description: 'Any new feature or idea that is not part of a release or a sprint. A branch for playing around.'
      - type: 'input'
        title: 'What is the {{index .PromptResponses 0}} name?'
        initialValue: ''
    command: "git checkout -b {{index .PromptResponses 0}}/{{index .PromptResponses 1}}"
    context: 'localBranches'
    loadingText: 'creating branch'
```
