### ISSUE TITLE
Range highlighting with custom colour specification doesn't seem to work

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1884]
With custom colour:

```yaml
gui:
  # stuff relating to the UI
  scrollHeight: 4 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
  commitLength:
    show: true
  mouseEvents: true
  skipUnstageLineWarning: true
  showFileTree: true
  showCommandLog: false
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - '#413660'
    selectedRangeBgColor:
      - '#413660'
```

![iTerm2 2022-04-19 at 02 40 33](https://user-images.githubusercontent.com/191335/163909544-e9e0aa1b-d9f3-49d0-8b08-828d0ce14797.gif)

With default colour:

```yaml
gui:
  # stuff relating to the UI
  scrollHeight: 4 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
  commitLength:
    show: true
  mouseEvents: true
  skipUnstageLineWarning: true
  showFileTree: true
  showCommandLog: false
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - '#413660'
    # selectedRangeBgColor:
    #   - '#413660'
```

![iTerm2 2022-04-19 at 02 41 41](https://user-images.githubusercontent.com/191335/163909632-c5860079-9341-44e9-9038-ee89b272ec34.gif)

Note that with a custom specification, the selected *line* seems to work, but range does not.

Tested on latest master (8b103b16bd3a06d0e661e507832459fae7ec1198).

(Also I don't think the config reload behaviour is working. I seem to still need to restart lazygit for config changes to stick)
