### ISSUE TITLE
Custom Command Keybindings - PlaceHolderValues: SelectedFile exists -> add SelectedDir

### ISSUE THREAD

**Issue by alexn-s** [jesseduffield/lazygit#2003]
## **Is your feature request related to a problem? Please describe.**
I am using a pnpm monorepo and have some automatic pipelines with conventional commit (eg. using the name from the project in the git repo in the commit). In order for that to work I must automatically navigate/ cd into the project and run the pipeline from there. Currently it only works with SelectedFile.name to get the path and proceed with it.

## **Describe the solution you'd like**
Add SelectedDir to the PlaceHolderValues so it is not required to select a file

## Examples
**example CURRENT command**
config.yml
```yml
customCommands
  - key: "y"
    command: "powershell.exe -noProfile C:/Users/.../AppData/Roaming/lazygit/scripts/git-cz.ps1 {{.SelectedFile.Name}}"
    context: "files"
    loadingText: "..."
    subprocess: true
```

**example PREFERRED command**
config.yml
```yml
customCommands
  - key: "y"
    command: "powershell.exe -noProfile C:/Users/.../AppData/Roaming/lazygit/scripts/git-cz.ps1 {{.SelectedDir.Name}}"
    context: "files"
    loadingText: "..."
    subprocess: true
```
