### ISSUE TITLE
Can't remap openStatusFilter

### ISSUE THREAD

**Issue by oblitzitate** [jesseduffield/lazygit#2029]
It stays as `<c-b>` even if I remap it.

**Desktop:**
 - Arch Linux
 - Lazygit v0.34

**Comment by mark2185** [comment]
Could you please post your config?

**Comment by oblitzitate** [comment]
Pre-remap:

```yml
gui:
  authorColors: {}
  branchColors: {}
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  language: auto
  theme:
    lightTheme: false
    activeBorderColor:
    - green
    - bold
    inactiveBorderColor:
    - white
    optionsTextColor:
    - blue
    selectedLineBgColor:
    - default
    selectedRangeBgColor:
    - blue
    cherryPickedCommitBgColor:
    - blue
    cherryPickedCommitFgColor:
    - cyan
    unstagedChangesColor:
    - red
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
  showListFooter: true
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  commandLogSize: 8
git:
  paging:
    colorArg: always
    pager: ""
    useConfig: false
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""
  skipHookPrefix: WIP
  autoFetch: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative
    --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate
    --date=relative  --pretty=medium
  overrideGpg: false
  disableForcePushing: false
  commitPrefixes: {}
  parseEmoji: false
  log:
    order: topo-order
    showGraph: when-maximised
  diffContextSize: 3
update:
  method: prompt
  days: 14
refresher:
  refreshInterval: 10
  fetchInterval: 60
reporting: undetermined
splashUpdatesIndex: 0
confirmOnQuit: false
quitOnTopLevelReturn: false
keybinding:
  universal:
    quit: q
    quit-alt1: <c-q>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: <c-u>
    nextPage: <c-d>
    scrollLeft: h
    scrollRight: l
    gotoTop: g
    gotoBottom: G
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: H
    nextBlock-alt: L
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    jumpToBlock:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    optionMenu: '?'
    #optionMenu-alt1: <c-h>
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirm-alt1: "y"
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: ','
    scrollDownMain-alt2: .
    executeCustomCommand: ':'
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: ']'
    prevTab: '['
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    appendNewline: <a-enter>
    extrasMenu: '@'
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  status:
    checkForUpdate: U
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: '`'
    openMergeTool: M
    openStatusFilter: <c-b>
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    viewGitFlowOptions: i
    fastForward: f
    pushTag: P
    setUpstream: U
    fetchRemote: f
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: u
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <c-j>
    moveUpCommit: <c-k>
    amendToCommit: A
    pickCommit: p
    revertCommit: t
    cherryPickCopy: c
    cherryPickCopyRange: C
    pasteCommits: v
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitMessageToClipboard: <c-y>
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
  stash:
    popStash: p
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleDragSelect: v
    toggleDragSelect-alt: V
    toggleSelectHunk: a
    pickBothHunks: b
  submodules:
    init: i
    update: U
    bulkMenu: b
os:
  editCommandTemplate: '{{editor}} {{filename}}'
  openCommand: xdg-open {{filename}} >/dev/null
  openLinkCommand: xdg-open {{link}} >/dev/null
disableStartupPopups: false
customCommands: []
services: {}
notARepository: prompt
promptToReturnFromSubprocess: true
```
