### ISSUE TITLE
Use C-d and C-u to scroll half page up / down

### ISSUE THREAD

**Issue by otavioschwanck** [jesseduffield/lazygit#2032]
**Is your feature request related to a problem? Please describe.**
Some keyboards doesn't have pagup and pagdown

**Describe the solution you'd like**
C-d and C-u to go half page up / down

**Comment by mark2185** [comment]
Do these alternatives not work?
```
keybinding:
  universal:
    scrollUpMain: '<pgup>' # main panel scroll up
    scrollDownMain: '<pgdown>' # main panel scroll down
    scrollUpMain-alt1: 'K' # main panel scroll up
    scrollDownMain-alt1: 'J' # main panel scroll down
    scrollUpMain-alt2: '<c-u>' # main panel scroll up
    scrollDownMain-alt2: '<c-d>' # main panel scroll down
```
