### ISSUE TITLE
ignoreFile keyblinding doesn't work

### ISSUE THREAD

**Issue by mosqu1t0** [jesseduffield/lazygit#2054]
**Describe the bug**
ignoreFile keyblinding doesn't work.
After upgrading lazygit to 0.35, i found that `ignoreFile` keyblinding is conflicted with `nextBlock-alt`.

**To Reproduce**
1. map ignoreFile keyblinding to `u`
2. map nextBlock-alt keyblinding to `i`
3. scroll to files block
4. press `i`
5. then it start to ignore files

**Expected behavior**
ignoreFile keyblinding works

**Screenshots**
![image](https://user-images.githubusercontent.com/94043894/180816676-07ddd38e-d577-45fa-b244-4fe28381def6.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Lazygit Version : v0.35
 - keyboardLayout: colemak

**Additional context**
here is my config 
```yml
gui:
  showIcons: true
keybinding:
  universal:
    prevItem-alt: 'e'
    nextItem-alt: 'n'
    prevBlock-alt: 'h'
    nextBlock-alt: 'i'
    nextMatch: '='
    prevMatch: '-'
    new: 'k'
    edit: 'o'
    openFile: 'O'
    scrollUpMain-alt1: 'U'
    scrollDownMain-alt1: 'E'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-e>'
    undo: 'l'
    redo: '<c-r>'
    diffingMenu: 'M'
    filteringMenu: '<c-f>'
  files:
    ignoreFile: 'u'
  commits:
    moveDownCommit: '<c-e>'
    moveUpCommit: '<c-u>'
  branches:
    viewGitFlowOptions: 'I'
    setUpstream: 'U'
```
