### ISSUE TITLE
Automatically push root git repository on submodule push

### ISSUE THREAD

**Issue by Hrle97** [jesseduffield/lazygit#2095]
**Is your feature request related to a problem? Please describe.**
I have a repository that has a submodule and a lot of the time I'm just commiting and pushing the submodule which is okay but then I have to commit and push the changes to the root repository manually. It would be nice if I could somehow do this without manual intervention. I don't know if this is already supported or if `lazygit` is the right way to go about this but it would be nice if I could make it work this way.

**Describe the solution you'd like**
After I push the submodule repository I'd like to be prompted for a commit message for the root repository and then the root repository gets pushed as well. The commit for the root repository would only include the changes in the submodule repository.

**Describe alternatives you've considered**
I guess I could just position myself in the root repository and it would automatically push the submodule repository whenever I try to push the root, but that's also a hassle because I have to switch working directories. A shell function would help but then I'd have to commit in the submodule repository, exit `lazygit`, do the shell function which positions me to the root repository, opens `lazygit` so I can commit and push there, and returns me back to the submodule repository.

**Additional context**
I guess that's it.

**Comment by mark2185** [comment]
> but that's also a hassle because I have to switch working directories.

Well you can enter the submodule by pressing `Enter` on it and exit by pressing `Escape`, does that help?

> A shell function would help but then I'd have to commit in the submodule repository, exit lazygit, do the shell function which positions me to the root repository, opens lazygit so I can commit and push there, and returns me back to the submodule repository

Have you tried running it from within `lazygit` by pressing `:`?

**Comment by jesseduffield** [comment]
This could also be a good candidate for a pre-set custom command. See https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium

It's much easier to implement features if a user has created a custom command for it first, because it's clearer what the expected behaviour is

**Comment by Hrle97** [comment]
@mark2185 those features sound cool, but it like something really automatic like @jesseduffield is proposing i think

ill keep you updated here whether i manage to do what i need to with custom commands

PS forgive my ignorance - im still new to `lazygit`

**Comment by mark2185** [comment]
@Hrle97 we're talking about the same thing 😅 

When you do manage to create a custom command, we'll add it to the compendium for other users to use.

**Comment by Hrle97** [comment]
Seems like it is working:
```yaml
customCommands:
  - key: '<c-c>'
    description: 'commit with supermodules'
    prompts:
      - type: 'input'
        title: 'Message'
    command: 'git commit -m "{{index .PromptResponses 0}}" && wd="$(pwd)" && cd .. && cd "$(git rev-parse --show-toplevel)" && git add "$wd" && git commit -m "update module $wd" && cd "$wd"'
    subprocess: true
    context: 'global'

  - key: '<c-p>'
    description: 'push with supermodules'
    command: 'git push && wd="$(pwd)" && cd .. && cd "$(git rev-parse --show-toplevel)" && git push && cd "$wd"'
    subprocess: true
    context: 'global'
```
