### ISSUE TITLE
{{index .PromptResponses 0 }} on second prompt doesn't work

### ISSUE THREAD

**Issue by amine2233** [jesseduffield/lazygit#2102]
**Describe the bug**

I added this custom command
```yml
- key : '<c-n>'
    description: 'Checkout a remote branch as FETCH_HEAD'
    command: "git fetch {{ index .PromptResponses 0 }} {{ index .PromptResponses 1 }} && git switch {{ index .PromptResponses 1 }}"
    context: 'localBranches'
    prompts:
      - type: 'input'
        title: 'Remote:'
        initialValue: "{{index .SelectedRemote.Name }}"
      - type: 'menuFromCommand'
        title: 'Remote branch:'
        command: "git branch  -r --list {{index .PromptResponses 0 }}/*"
        filter: "{{index .PromptResponses 0 }}/(?P<branch>.*)"
        valueFormat: '{{ .branch }}'
        labelFormat: '{{ .branch | green }}'
```

but I have noting in `{{index .PromptResponses 0 }}` on the second prompt command I see only this

<img width="503" alt="Capture d’écran 2022-08-08 à 21 07 29" src="https://user-images.githubusercontent.com/404449/183494969-158fd747-3de2-416f-9ad8-5707a11df9c8.png">

**To Reproduce**

1. create a config file on macOS
2. add a custom command
3. open a fresh lazygit using iTerm2
4. I run `<c-n>`
5. i have a popup with `origin`
6. I use `enter` with my keyboard
7. I saw the picture in the log
8. I saw a popup with empty `branch` and just the cancel button    

**Expected behavior**
need to have `origin` in the command logged
`git branch -r --list origin/*`

**Screenshots**

<img width="460" alt="Capture d’écran 2022-08-08 à 21 11 47" src="https://user-images.githubusercontent.com/404449/183495669-4bf50e59-3dbf-4ae6-af8c-6d26ae29befa.png">

**Version info:**
_commit=, build date=, build source=homebrew, version=0.35, os=darwin, arch=amd64_
_git version 2.37.1_

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
