### ISSUE TITLE
Allow fzf or similar interface for custom commands

### ISSUE THREAD

**Issue by PrayagS** [jesseduffield/lazygit#2120]
**Is your feature request related to a problem? Please describe.**

Custom commands allow us to execute arbitrary commands, filter their output, and present them in a list for the user. The user then chooses one option out of the list. An example command can be seen below,

```
- key: '<c-p>'
  description: "Pull from a specific remote repository"
  context: 'global'
  loadingText: 'Pulling ...'
  prompts:
    - type: 'menuFromCommand'
      title: 'Which branch to pull from?'
      command: bash -c "git branch -r"
      filter: '(?P<remote>[a-z0-9-]*)/(?P<branch>[a-z0-9-/]*)\s?.*'
      valueFormat: '{{ .remote }} {{ .branch }}'
      labelFormat: '{{ .remote | bold | cyan }}/{{ .branch | cyan }}'
  command: "git pull {{ index .PromptResponses 0 }}"
```

The above command lists all remote branches and allows me to pull from the branch I choose.

Such a list of options can get really long and some kind of fuzzy searching will go a long way.

**Describe the solution you'd like**

Modify popups to support fzf or integrate an internal fuzzy search solution ([currently used to filter paths](https://github.com/jesseduffield/lazygit/pull/1526)).

**Describe alternatives you've considered**

None.

**Additional context**

If the maintainers can suggest a compatible approach, then I'd be happy to send a PR for this.

**Comment by jesseduffield** [comment]
You can now filter a menu's contents using '/', although it's not a fuzzy search.

You can also add suggestions to an input prompt so your above command could be rewritten like so:
```yml
    - key: '<c-p>'
      description: "Pull from a specific remote repository"
      context: 'files'
      loadingText: 'Pulling ...'
      command: git pull {{ .Form.Remote }} {{ .Form.RemoteBranch }}
      prompts:
        - type: 'input'
          key: 'Remote'
          title: "Remote:"
          suggestions:
            preset: 'remotes'
        - type: 'input'
          key: 'RemoteBranch'
          title: "Remote branch:"
          suggestions:
            command: "git branch --remote --list '{{.Form.Remote}}/*' --format='%(refname:short)' | sed 's/{{.Form.Remote}}\\///'"
```
