### ISSUE TITLE
Open files of commit with lazy git

### ISSUE THREAD

**Issue by lauccode** [jesseduffield/lazygit#2187]
I'm looking to open automatically files of commit.
From that I can see it is only possible to open one file at a time.

It should be very nice to open all files of commit (or do selection) with lazygit in the editor ?
It could help for all editor which have not yet project management ... (I think it should be a must have feature that I can not manage with git or tools when I search on the web)
Rather than open each files one by one each time we open the directory (neovim, helix ....)

**Comment by mark2185** [comment]
Can't you use the editor to open whatever you want after you open a file?

E.g. `:edit .` from `neovim`?

Or open `lazygit` from within `neovim`? Or in a separate terminal?

**Comment by Ryooooooga** [comment]
@lauccode You can do with [custom commands](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md).

```yaml
customCommands:
  - key: O
    context: commits
    description: open files in commit
    command: git diff -z --name-only {{.SelectedLocalCommit.Sha}}~ {{.SelectedLocalCommit.Sha}} | xargs -0 code --
    subprocess: true
```
