### ISSUE TITLE
Rename stash messages

### ISSUE THREAD

**Issue by strboul** [jesseduffield/lazygit#2189]
**Is your feature request related to a problem? Please describe.**
Stashes cannot be renamed after they are created. I sometimes want to re-organize my stashes and I cannot rename the existing ones that are stored unnamed.

**Describe the solution you'd like**
Use `r` command to select the stash to rename and rename it (Maybe, it conflicts with the current stash `R (refresh)`.)

**Additional context**

Sadly, `git` doesn't have a command to rename them. The common approach is to drop & apply the stash with a different name. For instance:

```sh
mkdir -p /tmp/test-rename-stash
cd /tmp/test-rename-stash
git init
touch file1 file2
git add -A && git commit -m 'Initial commit'
echo 'Hello, world!' >> file1
git stash
# Saved working directory and index state WIP on master: 43862fe Initial commit
echo 'Ehlo!' >> file2
git stash push -m 'My precious stash message.'
# Saved working directory and index state On master: My precious stash message.
git stash list
# stash@{0}: On master: My precious stash message.
# stash@{1}: WIP on master: 43862fe Initial commit
```

Now drop the stash entry I want to rename and add it again with a new message by using the SHA of commit returned on drop:

```sh
git stash drop stash@{1}
# Dropped stash@{1} (64186436b85770cdfffbcaa50e65536f8e723e68)
git stash store -m 'This is also a precious stash now.' 64186436b85770cdfffbcaa50e65536f8e723e68
git stash list
# stash@{0}: This is also a precious stash now.
# stash@{1}: On master: My precious stash message.
```

Solution is adapted from [this](https://stackoverflow.com/a/35549615) SOF answer.

**Comment by Ryooooooga** [comment]
```yaml
customCommands:
  - key: r
    prompts:
      - type: 'input'
        title: 'Rename stash'
    command: "git stash drop {{.SelectedStashEntry.RefName}} | sed -E 's/.*\\(([0-9a-f]+)\\).*/\\1/' | xargs git stash store -m '{{index .PromptResponses 0}}'"
    context: stash
```
