### ISSUE TITLE
Merge error by arg `-e`

### ISSUE THREAD

**Issue by jerviscui** [jesseduffield/lazygit#2190]
**Describe the bug**

When I was using args `-e` for git merge, the program died.

**To Reproduce**

1. Setting `config.yml`:

	```
	git:
	  merging:
	    # extra args passed to `git merge`, e.g. --no-ff
	    args: '-e'
	```

2. Then merge by lazygit,
3. lazygit will hang by this
![image](https://user-images.githubusercontent.com/6396748/193020933-9a7c3c9b-591e-4e46-81ad-088c20f971fa.png)

**Expected behavior**

I'm just trying. I don't have a good plan.

**Version info:**

commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=windows, arch=amd64
git version 2.35.1.windows.2

**Comment by mark2185** [comment]
Could you please fill out the entire template?

**Comment by jerviscui** [comment]
I have updated the report.

**Comment by mark2185** [comment]
Ah, that hangs because it tries invoking `$EDITOR`.

Could you try setting the flags to `--no-commit` and then commit from within `lazygit`? If you wish to open the editor to do that, go to the `Files` panel `(2)` and press `C` (uppercase). That should do the same as you are trying to do now.

**Comment by Ryooooooga** [comment]
One solution is to override a merge action with a custom command.

```yaml
customCommands:
  - key: M
    command: git merge -e {{.SelectedLocalBranch.FullRefName}}
    context: localBranches
    subprocess: true
    prompts:
      - type: confirm
        title: Merge
        body: Are you sure you want to merge '{{.SelectedLocalBranch.Name}}' into '{{.CheckedOutBranch.Name}}'?
```
