### ISSUE TITLE
The background color of lighttheme is still black on ubuntu 22.04

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#2256]
**Describe the bug**
The background color of lighttheme is still black on ubuntu 22.04

**To Reproduce**

1. Add the following settings into config file
```
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - default
```
2. Launch lazygit

**Expected behavior**
The background color should be light.

**Actual Results**
The backgound color is still black.
![Theme](https://user-images.githubusercontent.com/52661397/200997127-d3e6ce95-f081-4782-a1ed-f2dbf3268a96.png)

**Version info:**
lazygit version 0.35
git version 2.34.1
Terminal: Terminator and Terminal
