### ISSUE TITLE
v0.35 and v0.36 break some remaps

### ISSUE THREAD

**Issue by Alex23rodriguez** [jesseduffield/lazygit#2317]
**Describe the bug**
in version 0.34 I had the following remap (among others):
```yaml
keybinding:
  universal:
    nextBlock-alt: "i" # goto the next block / panel   ## default l
  files:
    ignoreFile: "h" ## default i
```
and it worked fine. But I upgraded to the new versions (tested both) and me remap gets ignored, so now `i` still goes to ignore file!

**To Reproduce**
- try to remap `ignoreFile` to something else and `nextBlock-alt` to `i`.
- press `i` while on the files sectino
- notice `ignoreFile` still gets called

**Expected behavior**
My remap should be successful

**Version info:**
`commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=linux, arch=arm64`
or
`commit=d1a8b05401ccda1e52215203139a252eb3be3b79, build date=2022-11-14T09:22:31Z, build source=binaryRelease, version=0.36.0, os=linux, arch=arm64, git version=2.30.2`

`git version 2.30.2`
