### ISSUE TITLE
change external merge tool keybinding

### ISSUE THREAD

**Issue by uloco** [jesseduffield/lazygit#2355]
I'd like to change the _external merge tool_ keybinding which is bound to 'M' in the files menu, but I could not find any default / property in the config documentation.
Is there a way to override this, maybe the documentation is just missing?

**Comment by Ryooooooga** [comment]
```yaml
keybinding:
  files:
    openMergeTool: 'M'
```

just missing from Config.md.
