### ISSUE TITLE
Allow templating in prompt text to use values from previous prompts

### ISSUE THREAD

**Issue by rickyelopez** [jesseduffield/lazygit#2391]
It would be super useful if we could use responses from previous prompts, as well as other templated information, in other prompts.

For example, if the first prompt is a menu where you can choose from various values, and the second prompt is a user input, it would be really cool if I could set the default text in the input to include the response from the previous prompt. Is this something that's doable?

eg.
```yaml
prompts:
  - type: 'menu'
    title: 'Branch prefix'
    options:
      - value: 'develop'
      - value: 'feature'
      ...
  - type: 'input'
    title: 'branch name'
    initialValue: '{{index .PromptResponses 0}}/'
```
so that if I choose `develop` in the first prompt, the second prompt would have an initial value of `develop/` and let you type in the rest.

edit: looks like support for this already works in some fields, but apparently not the `initialValue` field? At least not from my testing, maybe I did something wrong though.
