### ISSUE TITLE
How can I execute `git checkout --ours XXX` with lazygit

### ISSUE THREAD

**Issue by xclidongbo** [jesseduffield/lazygit#2461]
**Topic**
How can I execute `git checkout --ours XXX` with lazygit

**Your thoughts**
execute `git checkout --ours XXX` with lazygit

**Comment by mark2185** [comment]
Currently only through running a custom command, i.e. pressing `:` and typing in the command you wish to run.

Where have you needed this use case?

**Comment by xclidongbo** [comment]
Resolve a lot of conflicts in one file. for example, one hundred of conflictes.

**Comment by Ryooooooga** [comment]
```yaml
customCommands:
  - key: H
    command: git restore --ours {{.SelectedFile.Name | quote}}
    context: mergeConflicts
    subprocess: true
  - key: L
    command: git restore --theirs {{.SelectedFile.Name | quote}}
    context: mergeConflicts
    subprocess: true
```
