### ISSUE TITLE
[Feature request] interactive rebase onto another branch

### ISSUE THREAD

**Issue by joihn** [jesseduffield/lazygit#2517]
Thanks for this tool !

I would like `interactive rebase onto another branch` function

**usecase**
Usefull if you have the folowing state
```
     commit C
     ┌─┐       ┌─┐     ┌─┐          
─────┼┼┼───────┼┼┼─────┼┼┼─────────►branch A
     └─┘       └─┘     └┼┘
                        │        ┌─┐     ┌─┐
                        └────────┼┼┼─────┼┼┼─────────────►branch B
                                 └─┘     └─┘
```
Then, on `branch A`, you delete `commit c` (because it was a bad feature).
Then when you rebase `B` onto `A`, `C` will reappear (ghost commit). 
If I had  `interactive rebase onto another branch`, I could drop B on the fly

**Describe alternatives you've considered**
A current workaround is to do it in 2 steps:
- use interactive rebase of a branch on itself (already in lazygit under the name "edit commit") on `branch B` to drop `commit c`, 
- then use normal rebase on to branch. 

It would be nice to have it in one step because if something goes wrong, user can just "abort" and left will be left untouched.

**Comment by joihn** [comment]
Actually the command lazygit run is :
`git rebase --interactive --autostash --keep-empty --empty=keep --no-autosquash <branch_to_rebase_onto>`
1) When I run manually in my terminal, it does pop an interactive GUI of which commit I want to pick.
2) When I run it via lazygit shortcut `r`, everything happends ine one step, like if it wasn't even an interactive rebase

it's weird that they have both different behavior. I wish lazygit would behave as 1)

**Comment by joihn** [comment]
This issue is actually a duplicate of :
https://github.com/jesseduffield/lazygit/issues/733
https://github.com/jesseduffield/lazygit/pull/2370
Therefore I'm closing it.

FYI, an clumsy workaround for the desired feature is the following:
Add the following custom command to your config (whose short is the key `0`):
```
customCommands:
  - key: '0'
    command: "git rebase --interactive --autostash --keep-empty --empty=keep --no-autosquash {{.SelectedLocalBranch.Name}}"
    context: 'localBranches'
    subprocess: true
```
then in lazgit:
1) go to local branch, press 0
2) your text editor comes up, edit the topmost commit to `edit`, save and quit
3) enjoy the rest of your interactive rebase within lazygit

**Comment by stefanhaller** [comment]
> the drawback is that if you want to drop the N first commit, it has to be done in the todo file with the text editor, It can't be done via lazygit

Instead of changing the first line to "edit", insert a "break" line before the first todo line. That will make this possible.

**Comment by joihn** [comment]
thank you !
Here is a fully automated custom command achieving the desired feature.
add it to your `~/.config/lazygit/config.yml`
```
customCommands:
  - key: 'R'
    command: "GIT_EDITOR=\"sed -i '1s/^/break \\n /'\" git rebase --interactive --autostash --keep-empty --empty=keep --no-autosquash {{.SelectedLocalBranch.Name}}"
    context: 'localBranches'
```
How to use:
go to local branch, press `R`

How it works under the hood:
it call a classic git interactive rebase with a special editor to edit the "git TODO" file.
the special editor prepend `break` to the file

**Comment by rcdailey** [comment]
I wanted to piggy-back on @joihn's excellent workaround by sharing my version which also includes starting an interactive rebase from a remote branch:

```yml
- key: I
  command: "GIT_EDITOR=\"sed -i '1s/^/break \\\\n /'\" git rebase --interactive --autostash --keep-empty --empty=keep --no-autosquash {{.SelectedLocalBranch.Name}}"
  context: localBranches
  description: Interactive rebase with lazygit control
- key: I
  command: "GIT_EDITOR=\"sed -i '1s/^/break \\\\n /'\" git rebase --interactive --autostash --keep-empty --empty=keep --no-autosquash {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}"
  context: remoteBranches
  description: Interactive rebase with lazygit control
```

Hopefully this gets first-class support in the future, though!
