### ISSUE TITLE
CustomCommands variable for all changed files.

### ISSUE THREAD

**Issue by Zaxiure** [jesseduffield/lazygit#2540]
**Is your feature request related to a problem? Please describe.**
I created a custom command so I could format files from the staged/unstaged changes using JetBrains format.sh, so I can format the code I create since I'm using neovim in combination with lazygit. Since sometimes I don't want to format all files in a specific directory it creates the problem where I'll have to go over each file individually taking up a lot of time.

**Describe the solution you'd like**
It would help a lot of there would be a way to get all paths/files like with {{.SelectedFile}} or {{.SelectedPath}} but for all files currently changed, staged or unstaged. Something like {{.ChangedFiles}}

**Describe alternatives you've considered**
I've tried getting neovim to work with the custom code format of JetBrains products, I have however not found a solution for this.

**Additional context**
Here you can see the current config I've created
```
customCommands:
  - key: '<c-f>'
    context: 'files'
    prompts:
      - type: 'menu'
        title: 'Select IDE'
        options:
          - name: 'PhpStorm'
            description: 'Use phpstorm code formatter'
            value: 'phpstorm'
          - name: 'WebStorm'
            description: 'Use webstorm code formatter'
            value: 'webstorm'
      - type: 'confirm'
        title: "Confirm:"
        body: "Formatting: \n\nPath: {{.SelectedPath}}\nIDE: {{index .PromptResponses 0}}\n\nAre you sure?"
    command: '
      {{$response := index .PromptResponses 0}}
      {{if eq "phpstorm" $response}}
      /Applications/PhpStorm.app/Contents/bin/format.sh -s /Volumes/Dev/Work/standards/code_style/phpstorm.xml -r "{{.SelectedPath}}"
      {{end}}
      {{if eq "webstorm" $response}}
      /Applications/WebStorm.app/Contents/bin/format.sh -s /Volumes/Dev/Work/standards/code_style/webstorm.xml -r "{{.SelectedPath}}"
      {{end}}
      '
    stream: true
    description: "Run JetBrains code format"
    loadingText: 'Running formatter...'
```
