### ISSUE TITLE
Add confirmation prompt before push/pull

### ISSUE THREAD

**Issue by oyarsa** [jesseduffield/lazygit#2543]
**Is your feature request related to a problem? Please describe.**
I'd like a confirmation prompt before push/pull.

**Describe the solution you'd like**
The option to add a confirmation prompt before pushing or pulling.

**Describe alternatives you've considered**
I searched the issues for something similar but couldn't find anything.

I considered a custom command, but those are hidden behind `o`, and my problem is that I press `p` on accident, so that wouldn't help.

**Comment by mark2185** [comment]
> I considered a custom command, but those are hidden behind o, and my problem is that I press p on accident

Behind `o`? Running a command prompt is behind `:`, but nothing is mapped at `o` by default.

You could overwrite the default `p` mapping through a custom command.
```
customCommands:
  - key: 'p'
    command: 'git push {{  .SelectedLocalBranch.Name }}'
    context: 'localBranches'
    description: 'Push current branch'
    stream: true
    prompts:
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to push '{{.SelectedLocalBranch.Name}} '?"
```

More info [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md).
