### ISSUE TITLE
Configuration of file editing does not behave as expected

### ISSUE THREAD

**Issue by ghidalgo93** [jesseduffield/lazygit#2570]
**Describe the bug**
changing the configuration of the file editing behavior in lazygit's os configuration does not have any effect. Neither directly changing the configuration file at the current config location (verified with `lazygit -cd`) nor passing in the `--use-config-file` flag change the edit command that is used by lazygit.

**To Reproduce**

On a mac, provide the following configs to `~/Library/Application Support/lazygit/config.yml`:
```
os:
  editPreset: 'nano'
```

or 

```
os:
  edit: 'myeditor {{filename}}'
  editAtLine: 'myeditor --line={{line}} {{filename}}'
  editAtLineAndWait: 'myeditor --block --line={{line}} {{filename}}'
  editInTerminal: true
```
*where I replaced `myeditor` with a number of editors including nvim, nano, vscode...

1. Open lazygit (either directly in a terminal or within nvim)
   a. use `--use-config-file` if directly invoking a custom config file
2. Go to any file in the "Files" window
3. use the "e" keybound edit key
4.  file is loaded in with vi
5. exit
6. view command log which provides the following: `bash -c "vi +1 -- "path/to/file.txt"`

**Expected behavior**
Depending on the editor provided in the lazygit configs, a change in how/what the edit command was called.

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=, build date=, build source=homebrew, version=0.37.0, os=darwin, arch=arm64, git version=2.39.2 (Apple Git-143)
_Run `git --version` and paste the result here_
git version 2.39.2 (Apple Git-143)

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
