### ISSUE TITLE
Bring back y to confirm dialogs

### ISSUE THREAD

**Issue by J053Fabi0** [jesseduffield/lazygit#2611]
**Topic**
Some releases ago the option to confirm dialogs with `y` was removed and I think it should come back.

**Your thoughts**
This issue is to raise awareness to the problem and see how many people upvote it, meaning they agree with me.
While the `enter` key is a fairly universal way of confirming something, the `y` key is also widely spread.

Right now there's no way to enable the use of `y`. The following configuration mucks up the input windows
```yml
keybinding:
  universal:
    confirm: 'y'
```
and something like this one is not possible
```yml
keybinding:
  universal:
    confirm: ['enter' ,'y']
```
