### ISSUE TITLE
v0.38.2 - commitPrefixes do not work

### ISSUE THREAD

**Issue by tsjk** [jesseduffield/lazygit#2613]
**Describe the bug**
After having upgraded from v0.37 to v0.38.2, commitPrefixes no longer work. That is, the prefix neither appears in the commit message dialog (I'm guessing it should appear in the summary), neither in the final message.

**My config**
```
% yq . < ~/Library/Application\ Support/lazygit/config.yml
git:
  commitPrefixes:
    repo: # This is repository folder name
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '$1: '
services:
  'gitlab.domain.se': 'gitlab:gitlab.domain.se'
gui:
  mouseEvents: false
```
