### ISSUE TITLE
Is it possible to delete remote tags?

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2635]
### Discussed in https://github.com/jesseduffield/lazygit/discussions/2633

<div type='discussions-op-text'>

<sup>Originally posted by **AndrewSav** May 17, 2023</sup>
I was able to figure out how to create local tags and push them, but I don't seem to be able to push a deleted local tag. Is this possible?

Also it seems deleting tags locally is futile anyway, they come back from the remote in a minute anyway... Is it possible to make it stick?</div>

P.S. currently achieved through a custom command (eyeballed it):
```
  - key: 'D'
    command: "git push --delete {{ .SelectedTag.FullRefName }}"
    context: 'tags'
    stream: true
    prompts:
      - type: 'confirm'
        title: "Confirm:"
        body: "Are you sure you want to delete the tag {{.SelectedTag}}?"
```
