### ISSUE TITLE
Need comment about my custom commad

### ISSUE THREAD

**Issue by jittapont** [jesseduffield/lazygit#2733]
**Topic**
I just created a custom command to rebase my current branch to a remote branch by adding this command in lazygit config
```
  - key : 'B'
    description: 'Rebase current branch to selected branch'
    prompts:
      - type: 'input'
        title: 'What is the new branch name that you want to rebase?'
        key: 'BranchName'
        initialValue: 'master'
    command: "git fetch -p && git rebase origin/{{ .Form.BranchName }}"
    loadingText: 'Rebasing branch'
    context: 'global'
```
After I ran this command, I got this error
![image](https://github.com/jesseduffield/lazygit/assets/56988998/53018925-f60e-416b-9520-9c3aa94b8b1f)

Please provide any feed back or recommendation about my custom command 🙏

**Comment by mark2185** [comment]
Based on [the instructions](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md#placeholder-values), you probably want `SelectedLocalBranch` instead of `.Form.BranchName`.

**Comment by jittapont** [comment]
I want to input branch name instead of using selected local branch e.g. I want to rebase my feature branch with origin/master

**Comment by mark2185** [comment]
Ah, then you're interested in the [input](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md#input) part of the docs.

Take a look at [this example](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#pushing-to-a-specific-remote-branch) of a custom command:
```
customCommands:
  - key: '<c-p>'
    context: 'global'
    loadingText: 'pushing'
    prompts:
      - type: 'input'
        title: 'which branch do you want to push to?'
    command: "git push origin {{index .PromptResponses 0}}"
```
