### ISSUE TITLE
Allow gpgsigning of commits retroactively

### ISSUE THREAD

**Issue by PlexSheep** [jesseduffield/lazygit#2783]
**Is your feature request related to a problem? Please describe.**
I want to sign commits with my gpg key, that is protected with a passphrase. Besides the cache of my gpg-agent, I need to enter my password with each commit if I enable signing by default. 
If I disable it by default, my pushed commits will be unsigned, as I don't have an option to just sign a commit from lazygit.

I'd like to just make unsigned commits, then squash them together before pushing, sign the resulting commit, and then push this signed commit.

**Describe the solution you'd like**
Be able to select a commit, press `S` (or some other hotkey) and have it signed. This way I can commit all I want, then squash and only sign the final commit that would be pushed. This could be implemented by adding the custom command I've formulated into the default ones.

**Describe alternatives you've considered**
As a workaround to the option missing from lazygit, I am using the following custom command to sign the commit retroactively:
`git commit --ammend --gpg-sign`
I do this by opening the custom command panel with `:` and then selecting my command / typing it in.

As I made this issue, I was made aware of the custom command feature. I've formulated this simple custom command that does what I need.

**Additional context**
A custom command that does what I want. Note that this will only sign the last commit, as I haven't found a way to sign the selected commit retroactively.

```yml
customCommands:
  - key: '<c-s>'
    context: 'commits'
    command: 'git commit --amend --gpg-sign --no-edit --signoff'
    description: "retroactively sign the last commit with your GPG key and sign it off (add a message stating that it has been signed)."
    loadingText: 'waiting for gpg to sign your commit'
```

**Comment by jorgheymans** [comment]
Signing a specific commit worked like this for me (courtesy of our AI overlords)

```
The command git commit --amend --gpg-sign --no-edit --signoff can only be used on the most recent commit. 
To amend a specific, non-recent commit with GPG signature and signoff, you'll need to use interactive rebase:

    git rebase -i [commit's parent hash]
    Change pick to edit for the commit you want to amend.
    Save and exit the editor.
    Run git commit --amend --gpg-sign --no-edit --signoff
    git rebase --continue 
```

**Comment by DrummyFloyd** [comment]
found something that will may handle your case

```yaml
customCommands:
  - key: "<c-s>"
    command: "git rebase --exec 'git commit --amend --gpg-sign --no-edit' HEAD~{{.Form.numberCommits}}"
    context: "commits"
    description: "GPGSign previous commits"
    prompts:
      - type: "input"
        title: "Number of commits to sign"
        key: numberCommits
        initialValue: "1"
```
