### ISSUE TITLE
Open existing PR/MR or open repo in browser

### ISSUE THREAD

**Issue by bryan-lott** [jesseduffield/lazygit#2788]
**Is your feature request related to a problem? Please describe.**
I *love* the "create pull request" feature, however, once the pull request is created there isn't an easy way to get back to it from lazygit. I.e., I open a draft PR to show a colleague something, they provide feedback, I update changes, push to the PR, but have to jump back to my browser, find the (probably closed) tab, to interact with the PR.

**Describe the solution you'd like**
Either:
1. A command to open the existing PR in the browser (preferably).
2. A command to open the repo in the browser (if number 1 is too much of a pain).

(side note: thanks for creating such an awesome tool, having used magit in emacs, gitkraken, vscode's git plugins, etc, lazygit is easily at the top of the pack!!)

**Comment by bryan-lott** [comment]
Unfortunately I'm on gitlab, though gitlab does have a CLI tool, wonder if I can leverage that somehow? I'll dig in and post here if I come up with a solution.

Really appreciate your config to work from, thanks!

**Comment by bryan-lott** [comment]
Very similar... just need the gitlab cli client: `brew install glab`

```yml
customCommands:
  - key: "G"
    command: "glab mr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Go to MR in gitlab"
    stream: true
```
