### ISSUE TITLE
Setting bindings to `null` doesn't disable it

### ISSUE THREAD

**Issue by uyha** [jesseduffield/lazygit#2820]
**Describe the bug**
After updating to v0.39 (not sure which patch version), I cannot map the keys "H" and "L" anymore.

**To Reproduce**

1. Have the following snippet in the config file
```yaml
keybinding:
  universal:
    scrollLeft: null
    scrollRight: null
    nextTab: "L"
    prevTab: "H"
```
2. Use "L" and "H" when using lazygit

**Expected behavior**
When pressing "L" and "H", the tab should be changed. Instead, the current tab's view is scroll left and right.

**Version info:**
- commit=, build date=, build source=homebrew, version=0.39.3, os=linux, arch=amd64, git version=2.41.0
- git version 2.41.0

**Comment by mark2185** [comment]
Do the versions before `v0.39` allow you to remap that? I.e. is this a regression?

**Comment by hatredholder** [comment]
Can't reproduce this on the latest version from Homebrew, the same keybindings work for me.
Are you sure you've changed these keybindings first?
```
scrollLeft: 'H' # change from H to another key
scrollRight: 'L' # change from L to another key
```
Cause they might override keys you wanna bind

**Comment by uyha** [comment]
I didn’t touch those settings, I will have a look

**Comment by uyha** [comment]
```yaml
keybinding:
  universal:
    scrollLeft: null
    scrollRight: null
    scrollUpMain-alt1: null
    scrollDownMain-alt1: null
    nextBlock-alt: null
    prevBlock-alt: null
    nextBlock: "J"
    prevBlock: "K"
    nextTab: "L"
    prevTab: "H"
```
With this config, it still doesn't work
