### ISSUE TITLE
Make Bulk Submodule actions recursive

### ISSUE THREAD

**Issue by tkuraku** [jesseduffield/lazygit#2930]
**Topic**
I propose that the bulk submodule actions are all set to recursive.

**Your thoughts**

I think that doing things from the bulk menu often implies that you want everything updated, initialized, sync'd. I would propose that these actions are performed recursively by default. Not sure why someone would want to do a bulk update, but not do it recursively.

This would address   #1371

This proposed change would only be a small change. I don't really see any downside, but I could be wrong!

It would just be adding the --recursive flag to update, init bulk commands. If this sounds good I would be happy to make a pull request. Thanks for your time!

**Comment by tkuraku** [comment]
Learning about custom commands I can see that this is sufficient. It would be nice to have a submodules context option.

```yml
# recursive submodule commands
customCommands:
  - key: 'U'
    command: 'git submodule update --recursive'
    context: 'files'
    description: 'Update submodules'
    stream: true
  - key: 'I'
    command: 'git submodule update --init --recursive'
    context: 'files'
    description: 'Initialize submodules'
    stream: true
  - key: 'S'
    command: 'git submodule sync --recursive'
    context: 'files'
    description: 'Sync submodules'
    stream: true
```
