### ISSUE TITLE
'yaml: control characters are not allowed' error when starting lazygit

### ISSUE THREAD

**Issue by arouault-til** [jesseduffield/lazygit#3023]
**Describe the bug**
When I want to start `lazygit` in my terminal on Windows I have this error:

`yaml: control characters are not allowed`

**To Reproduce**
I just start `lazygit` in my terminal.

I run : `$ lazygit`

**Expected behavior**
I want `lazygit` to start normally.

**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/139747549/bb79f098-63fa-4153-806f-7c92ceb213e8)

**Version info:**
_Run `lazygit --version` and paste the result here_

commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=windows, arch=amd64, git version=2.40.1.windows.1

_Run `git --version` and paste the result here_

git version 2.40.1.windows.1

**Additional context**
I tried to uninstall and reinstall lazygit using choco on Windows but the issue is still here.

It happens one day, I don't know why and the error doesn't help.

I'm sorry I don't have much context or a clear way to reproduce.

It might be a windows error but I don't have any clue on how to solve this or where to ask for answers.

**Comment by mark2185** [comment]
Could you post your `config.yml`?


It's in the folder indicated by `./lazygit -cd`. On windows it should be in `%APPDATA%\lazygit\config.yml`.

**Comment by arouault-til** [comment]
Sure!

`cat config.yml`

```
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
```
