### ISSUE TITLE
Adding a command to copy current selected diff to clipboard

### ISSUE THREAD

**Issue by guildem** [jesseduffield/lazygit#3079]
**Is your feature request related to a problem? Please describe.**
On some client projects i'm working on, I have no rights to push anything, but I may test fixes and enhancements, and suggest them to the lead. My current behavior for small diff is to `git diff folder_or_file | wl-copy` et paste it into a chat, or by mail (they don't use git mail), or on a specific app.

**Describe the solution you'd like**
It would be nice to have a shortcut to copy "what we are seeing on lazygit diff panel", which depends on what file/folder is selected on the left panel.

**Describe alternatives you've considered**
Writing selected diff into a file could be an alternative but I doubt this would be a easier solution, clipboard management being already implemented into lazygit.

**Additional context**
Here is a custom command that can do that, but is limited to the given clipboard manager and won't work between systems. Also it won't handle the context lines number currently in lazygit, I didn't find how to get it into a custom command. A more integrated command would be better I think.

```yaml
customCommands:
  - key: "X"
    command: "git diff {{ .SelectedPath }} | wl-copy"
    context: "files"
    description: "copy current diff to clipboard"
    subprocess: false
```

I would like to contribute, but I know nothing about Go and don't have much time to learn it, so if someone is motivated to make a PR of that, it could be great !
