### ISSUE TITLE
lazygit not using delta"s colors

### ISSUE THREAD

**Issue by xeros-and-ones** [jesseduffield/lazygit#3096]
Lazygit suddenly not respecting or using delta's colours

this is how delta looks like in the terminal as a pager:
![Screenshot_20231028_092740](https://github.com/jesseduffield/lazygit/assets/24499824/7201dfaa-58d0-4c4c-b090-431acb197322)

And this is how delta looks in lazygit:
![Screenshot_20231028_092838](https://github.com/jesseduffield/lazygit/assets/24499824/ae297d7f-3e7e-45a0-924c-566c820d1f0e)

commit=v0.40.2,
build source=binaryRelease,
version=0.40.2, 
os=linux, 
arch=amd64, 
git version=2.42.0

Here's My config:
lazygit ▼▼▼▼
```yaml
# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: '3'
  border: 'rounded'
  theme:
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - green
      - bold
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

git ▼▼▼▼
```gitconfig
[core]
    editor = nvim
    pager = delta
[interactive]
    diffFilter = delta --color-only
[delta]
    navigate = true    # use n and N to move between diff sections
    light = false      # set to true if you're in a terminal w/ a light background color (e.g. the default macOS terminal)
    side-by-side = false
    line-numbers = true
    syntax-theme = gruvbox-dark
[merge]
    conflictstyle = diff3
[diff]
    colorMoved = default
```

**Comment by HoffsMH** [comment]
Did you ever resolve this?

**Comment by xyven1** [comment]
Also seeing this issue, using the Visual Studio Dark+ theme.

**Comment by V4G4X** [comment]
I have this issue as well.

Delta config:
```
git:
  log:
    showGraph: always
    showWholeGraph: false
  paging:
    pager: delta --dark --paging=never
gui:
  nerdFontsVersion: '3'
  showFileTree: false
```

Version:
```
❯ lazygit --version
commit=, build date=, build source=nix, version=0.43.1, os=darwin, arch=arm64, git version=2.45.2
❯ delta --version
delta 0.18.0
```
