### ISSUE TITLE
I want to become more lazy by implementing AI generated commit messages.

### ISSUE THREAD

**Issue by n3m** [jesseduffield/lazygit#3212]
**Is your feature request related to a problem? Please describe.**
Using this tool has been a time saver since I discovered it, but I've always struggled with commit messages, so the idea of autogenerating it seems more feasible.
Context of idea: VSCode already has implemented something like this, they literally put a button on the terminal that allows you to get a commit message based on your staging context

**Describe the solution you'd like**
- A way to configure an OpenAI or your favorite LLM provider token/key
- An option to either autogenerate the commit message or manually typing it when attempting to commit. (I'm imagining the feature where the regular commit message box appears, but if you have your key configured, you can press "X" or something, and have it autogenerate it.)

**Describe alternatives you've considered**
Current alternatives are doing stuff outside Lazygit, which defeats the whole point here.

**Additional context**

**_I want to know if the capabilities of Lazygit would even allow such complex solution_**, if it does, then **_I'm happy to start working on it myself._**

**Comment by chhoumann** [comment]
Hey @n3m,

I was looking for this myself. Decided to just build it.

https://github.com/chhoumann/bunnai

Hope you find it useful :)

**Comment by n3m** [comment]
@chhoumann, can't thank you enough dude.

I really wanted to have a go at it, but I didn't really had time to build it since I opened this issue because of other projects I have going on, but man, thank you for going through it.

**Comment by deepanchal** [comment]
Here's my custom command with aichat (https://github.com/sigoden/aichat)

```yaml
customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: 'aichat "Please suggest 10 commit messages, given the following diff:


      \`\`\`diff

      $(git diff --cached)

      \`\`\`


      **Criteria:**


      1. **Format:** Each commit message must follow the conventional commits format,
      which is \`<type>(<scope>): <description>\`.

      2. **Relevance:** Avoid mentioning a module name unless it\''s directly relevant
      to the change.

      3. **Enumeration:** List the commit messages from 1 to 10.

      4. **Clarity and Conciseness:** Each message should clearly and concisely convey
      the change made.


      **Commit Message Examples:**


      - fix(app): add password regex pattern

      - test(unit): add new test cases

      - style: remove unused imports

      - refactor(pages): extract common code to \`utils/wait.ts\`


      **Recent Commits on Repo for Reference:**


      \`\`\`

      $(git log -n 10 --pretty=format:''%h %s'')

      \`\`\`


      **Output Template**


      Follow this output template and ONLY output raw commit messages without spacing,
      numbers or other decorations.


      fix(app): add password regex pattern

      test(unit): add new test cases

      style: remove unused imports

      refactor(pages): extract common code to \`utils/wait.ts\`



      **Instructions:**


      - Take a moment to understand the changes made in the diff.

      - Think about the impact of these changes on the project (e.g., bug fixes, new
      features, performance improvements, code refactoring, documentation updates).
      It\''s critical to my career you abstract the changes to a higher level and not
      just describe the code changes.

      - Generate commit messages that accurately describe these changes, ensuring they
      are helpful to someone reading the project\''s history.

      - Remember, a well-crafted commit message can significantly aid in the maintenance
      and understanding of the project over time.

      - If multiple changes are present, make sure you capture them all in each commit
      message.


      Keep in mind you will suggest 10 commit messages. Only 1 will be used. It\''s
      better to push yourself (esp to synthesize to a higher level) and maybe wrong
      about some of the 10 commits because only one needs to be good. I\''m looking
      for your best commit, not the best average commit. It\''s better to cover more
      scenarios than include a lot of overlap.


      Write your 10 commit messages below in the format shown in Output Template section
      above." | fzf --height 40% --border --ansi --preview "echo {}" --preview-window=up:wrap
      | xargs -I {} bash -c "echo \"{}\" > .git/COMMIT_EDITMSG && vim .git/COMMIT_EDITMSG
      && [ -s .git/COMMIT_EDITMSG ] && git commit -F .git/COMMIT_EDITMSG || echo \"Commit
      message is empty, commit aborted.\""

      '
    context: files
    subprocess: true
```

Usage:

Trigger with `Ctrl + A` after staging files in `lazygit`

![Peek 2024-06-11 14-05](https://github.com/jesseduffield/lazygit/assets/46167867/dfd61610-f641-49fa-8f75-1c98ca94369e)

**Comment by joshuadanpeterson** [comment]
Thank you @deepanchal, this is exactly what I was looking for. Quick question: Whenever I select a commit generated by the prompt, I get a 'VIM: Warning input is not from a terminal' message. What should I do about that?

**Comment by deepanchal** [comment]
@joshuadanpeterson I am not sure what's causing that warning for you. I am using [wezterm](https://wezfurlong.org/wezterm/index.html) with [AstroNvim](https://astronvim.com/) and I am not getting this warning. Maybe try these solutions:
- https://unix.stackexchange.com/questions/732092/vim-warning-input-is-not-from-a-terminal
- https://superuser.com/questions/336016/invoking-vi-through-find-xargs-breaks-my-terminal-why

**Comment by joshuadanpeterson** [comment]
> @joshuadanpeterson I am not sure what's causing that warning for you. I am using [wezterm](https://wezfurlong.org/wezterm/index.html) with [AstroNvim](https://astronvim.com/) and I am not getting this warning. Maybe try these solutions:
> 
> * https://unix.stackexchange.com/questions/732092/vim-warning-input-is-not-from-a-terminal
> * https://superuser.com/questions/336016/invoking-vi-through-find-xargs-breaks-my-terminal-why

Cool, thank you. I'll look these over this weekend and see what I can't come up with.

**Comment by joshuadanpeterson** [comment]
@deepanchal Turns out all I had to do was switch the editor from vim to nvim and the error went away. Not sure why. Maybe it's because I don't have a .vimrc so it doesn't know how to read certain files? Either way, it's fixed.

**Comment by deepanchal** [comment]
> @deepanchal Turns out all I had to do was switch the editor from vim to nvim and the error went away. Not sure why. Maybe it's because I don't have a .vimrc so it doesn't know how to read certain files? Either way, it's fixed.

I am glad that worked for you. I just realized that I have alias set for vi, vim to nvim, that's why it was working for me. I will update the snippet with a better command using the $EDITOR env var to edit commit message soon.

**Comment by deepanchal** [comment]
I have updated the snippet (in my original comment) to use $EDITOR env var and made it a little cleaner.
Here's the new command:
```sh
aichat "Please suggest 10 commit messages, given the following diff:

      \`\`\`diff
      $(git diff --cached)
      \`\`\`

      **Criteria:**

      1. **Format:** Each commit message must follow the conventional commits format,
      which is \`<type>(<scope>): <description>\`.
      2. **Relevance:** Avoid mentioning a module name unless it\''s directly relevant
      to the change.
      3. **Enumeration:** List the commit messages from 1 to 10.
      4. **Clarity and Conciseness:** Each message should clearly and concisely convey
      the change made.

      **Commit Message Examples:**

      - fix(app): add password regex pattern
      - test(unit): add new test cases
      - style: remove unused imports
      - refactor(pages): extract common code to \`utils/wait.ts\`

      **Recent Commits on Repo for Reference:**

      \`\`\`
      $(git log -n 10 --pretty=format:'%h %s')
      \`\`\`

      **Output Template**

      Follow this output template and ONLY output raw commit messages without spacing,
      numbers or other decorations.

      fix(app): add password regex pattern
      test(unit): add new test cases
      style: remove unused imports
      refactor(pages): extract common code to \`utils/wait.ts\`

      **Instructions:**

      - Take a moment to understand the changes made in the diff.

      - Think about the impact of these changes on the project (e.g., bug fixes, new
      features, performance improvements, code refactoring, documentation updates).
      It\''s critical to my career you abstract the changes to a higher level and not
      just describe the code changes.

      - Generate commit messages that accurately describe these changes, ensuring they
      are helpful to someone reading the project\''s history.

      - Remember, a well-crafted commit message can significantly aid in the maintenance
      and understanding of the project over time.

      - If multiple changes are present, make sure you capture them all in each commit
      message.

      Keep in mind you will suggest 10 commit messages. Only 1 will be used. It\''s
      better to push yourself (esp to synthesize to a higher level) and maybe wrong
      about some of the 10 commits because only one needs to be good. I\''m looking
      for your best commit, not the best average commit. It\''s better to cover more
      scenarios than include a lot of overlap.

      Write your 10 commit messages below in the format shown in Output Template section above." \
        | fzf --height 40% --border --ansi --preview "echo {}" --preview-window=up:wrap \
        | xargs -I {} bash -c '
            COMMIT_MSG_FILE=$(mktemp)
            echo "{}" > "$COMMIT_MSG_FILE"
            ${EDITOR:-nano} "$COMMIT_MSG_FILE"
            if [ -s "$COMMIT_MSG_FILE" ]; then
                git commit -F "$COMMIT_MSG_FILE"
            else
                echo "Commit message is empty, commit aborted."
            fi
            rm -f "$COMMIT_MSG_FILE"'
```

**Comment by joshuadanpeterson** [comment]
Is that EDITOR or nano, EDITOR as nano, or EDITOR excluding nano?

**Comment by deepanchal** [comment]
> ```yaml
>               ${EDITOR:-vim} "$COMMIT_MSG_FILE"
> ```

It defaults to vim if `$EDITOR` env var is not set. You can change it to whatever you like :)

**Comment by cloudpresser** [comment]
If you already use [aicommit2](https://github.com/tak-bro/aicommit2), you can do:
```
customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: aicommit2
    context: files
    subprocess: true
    showOutput: true
  - key: <c-n>
    description: Pick AI commit (no verify)
    command: aicommit2 --no-verify
    context: files
    subprocess: true
```

**Comment by BANG88** [comment]
@cloudpresser  Thank you, it's quite useful.

**Comment by kjvdven** [comment]
> If you already use [aicommit2](https://github.com/tak-bro/aicommit2), you can do:
> 
> ```
> customCommands:
>   - key: <c-a>
>     description: Pick AI commit
>     command: aicommit2
>     context: files
>     subprocess: true
>     showOutput: true
>   - key: <c-n>
>     description: Pick AI commit (no verify)
>     command: aicommit2 --no-verify
>     context: files
>     subprocess: true
> ```

I ran into an issue with an old version of node (14), `aicommit2` wanted to use the local projects node version. 

I use Mise as my version manager, so I prefixed the command with `mise x node@20 --` to run it with a specific node version.

```
customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: mise x node@20 -- aicommit2
    context: files
    subprocess: true
    showOutput: true
```

**Comment by tamas-torjek** [comment]
Hi, I have my own script to call ollama and generate a commit message and a longer description (separated by a blank line).
What I want to achieve is to have both (message and description) populated from the script's output, so it would look like the default commit dialog. And if I want to, I can modify the generated output in the dialog before committing.

Can someone give me some directions on how to get this done?

**Comment by kjvdven** [comment]
> ```
> customCommands:
>   - key: <c-a>
>     description: Pick AI commit
>     command: mise x node@20 -- aicommit2
>     context: files
>     subprocess: true
>     showOutput: true
> ```

I have updated my command to paste the aicommit2 message in the LazyGit pending commit message.
Because I often want to edit the commit message.

```
customCommands:
  - key: <c-a>
    description: Pick AI commit (copy)
    command: mise x node@20 -- aicommit2 -c && pbpaste > .git/LAZYGIT_PENDING_COMMIT
    context: files
    subprocess: true
    showOutput: true
```

**Comment by rxtsel** [comment]
> Here's my custom command with aichat (https://github.com/sigoden/aichat) using modified template from https://github.com/chhoumann/bunnai/blob/af4b78efa24dce6940bb6576ad3f9f579f995111/src/template.ts
> 


I’ve been trying to integrate it with lazygit and this is what I’ve come up with with the help of AI. For now, I haven’t added a spinner or loader to give feedback while the commit suggestions are being generated. Using AIs like GitHub models such as gpt-4o-mini, it generates pretty quickly and gets good results. With local models, it takes a bit longer and the results are somewhat lacking.

[Here’s the custom keybinding](https://github.com/rxtsel/dot/tree/main/.config/lazygit). It still needs a lot of improvement.

---

https://github.com/user-attachments/assets/59133be1-4c36-4ee3-b575-41bfbd256836

**Comment by agrinfauzi** [comment]
> > Here's my custom command with aichat (https://github.com/sigoden/aichat) using modified template from https://github.com/chhoumann/bunnai/blob/af4b78efa24dce6940bb6576ad3f9f579f995111/src/template.ts
> 
> I’ve been trying to integrate it with lazygit and this is what I’ve come up with with the help of AI. For now, I haven’t added a spinner or loader to give feedback while the commit suggestions are being generated. Using AIs like GitHub models such as gpt-4o-mini, it generates pretty quickly and gets good results. With local models, it takes a bit longer and the results are somewhat lacking.
> 
> [Here’s the custom keybinding](https://github.com/rxtsel/dot/tree/main/.config/lazygit). It still needs a lot of improvement.
> 
>  2025-03-23.12-54-46.mp4


Thank you for the reference! I added a few options to make it more concise.

```yaml
customCommands:
  - key: <c-a>
    description: AI-powered conventional commit
    context: global
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "AI defined"
            description: "Let AI analyze and determine the best commit type"
            value: "ai-defined"
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
      - type: menuFromCommand
        title: "AI Generated Commit Messages"
        key: CommitMsg
        command: |
          bash -c "
          # Check for staged changes
          diff=\$(git diff --cached | head -n 10)
          if [ -z \"\$diff\" ]; then
            echo \"No changes in staging. Add changes first.\"
            exit 1
          fi

          SELECTED_TYPE=\"{{.Form.Type}}\"
          COMMITS_TO_SUGGEST=8

          aichat \"

          You are an expert at writing Git commits. Your job is to write commit messages that follow the Conventional Commits format.

          The user has selected: \$SELECTED_TYPE

          Your task is to:
          1. Analyze the code changes
          2. Determine the most appropriate commit type (if user selected 'ai-defined')
          3. Determine an appropriate scope (component/area affected)
          4. Decide if this is a breaking change
          5. Write clear, concise commit messages

          Available commit types:
          - feat: A new feature
          - fix: A bug fix
          - docs: Documentation only changes
          - style: Changes that do not affect the meaning of the code
          - refactor: A code change that neither fixes a bug nor adds a feature
          - perf: A code change that improves performance
          - test: Adding missing tests or correcting existing tests
          - build: Changes that affect the build system or external dependencies
          - ci: Changes to CI configuration files and scripts
          - chore: Other changes that don't modify src or test files
          - revert: Reverts a previous commit

          Follow these guidelines:
          - Structure: <type>(<scope>): <description>
          - If user selected 'ai-defined', analyze the changes and pick the most suitable type
          - If user selected a specific type, use that type: \$SELECTED_TYPE
          - Add scope in parentheses if applicable (e.g., auth, api, ui, config)
          - Use exclamation mark (!) after type/scope for breaking changes: type(scope)!: description
          - Use lowercase for description (except proper nouns)
          - Use imperative mood (\\\"add\\\", not \\\"added\\\")
          - Keep description under 50 characters when possible
          - No period at the end of subject line

          Examples:
          - feat(auth): add OAuth login support
          - fix(api): handle null response in user endpoint
          - docs(readme): update installation instructions
          - style(ui): improve button spacing consistency
          - refactor(database): simplify query builder logic
          - test(auth): add unit tests for login flow
          - build(deps): upgrade React to version 18
          - ci(github): fix deployment workflow
          - chore(config): update ESLint rules
          - perf(api)!: optimize database queries

          IMPORTANT:
          - Generate exactly \$COMMITS_TO_SUGGEST different commit message options
          - If user selected 'ai-defined', you can use different types for different options
          - If user selected a specific type, all messages must use that type
          - Only return commit messages, no explanations
          - Do not use markdown code blocks
          - One message per line

          Previous commits for context:
          \$(git log --oneline -10)

          Changes to analyze:
          \$(git diff --cached --stat)
          \$(git diff --cached)
          \"
          "
    command: "git commit -m \"{{.Form.CommitMsg}}\""
    loadingText: "Generating commit messages..."
```
<video src="https://github.com/user-attachments/assets/1248ec77-3d93-4311-9eb3-eec0f2cea1ce" width="180" controls></video>

<video src="https://github.com/user-attachments/assets/464a1536-3e3f-461f-9fb5-a4157eb15928" width="180" controls></video>

**Comment by Blankeos** [comment]
These solutions are great but I wish there was more of a human-in-the-loop UX where I just press:
`c` to commit. And maybe press a hotkey to generate a message for me.
Then confirm or modify as needed.

---

## Edit (Mar 29, 2026): I ended up vibing my own "lazygit" btw, in Rust. (lazygitrs)

It's probably not 1:1, but I've already completely replaced lazygit with it w/ the features I use daily. Still improving. so far... I've added:
- AI commit messages (that you can edit before submitting)
- Better diff viewer (Side-by-side diff viewer w/ syntax highlighting out of the box) and a built-in compare tool
- Interactive rebasing UI
- Theme selection inspired by opencode

Repo: https://github.com/blankeos/lazygitrs

https://github.com/user-attachments/assets/4d207a8a-1568-463f-b00b-fced92ab480c

**Comment by codevogel** [comment]
> These solutions are great but I wish there was more of a human-in-the-loop UX where I just press: `c` to commit. And maybe press a hotkey to generate a message for me. Then confirm or modify as needed.

I felt the exact same. I got inspired after @deepanchal 's reply here, but felt it was missing some interaction and review steps. @tamas-torjek I think this is also a perfect fit for you.

That's why I built [commit for me](https://github.com/codevogel/commit-for-me)!
It generates some candidates, and then opens the commit message in your `$EDITOR` for review.
If you then save the file, you commit. If you leave it untouched or empty, you abort.

Demo: 

![main demo](https://raw.githubusercontent.com/codevogel/commit-for-me/main/demo/demo.gif)

Lazygit use demo:

![lazygit demo](https://raw.githubusercontent.com/codevogel/commit-for-me/main/demo/lazygit-demo.gif)

It's a simple bash script that you can use standalone, or with lazygit integration using this custom command:

```yaml
customCommands:
  - key: "<c-a>"
    description: "generate message candidates and commit using cfme"
    command: "cfme"
    context: "files"
    loadingText: "Generating commit message with cfme..."
    subprocess: true
```

It uses the `conventional-commits` standard by default, but it's also [_VERY_ easy to customize](https://github.com/codevogel/commit-for-me?tab=readme-ov-file#customization) to your own needs. 

You just write a prompt file in `markdown` using template strings `<__IN_THIS_FORMAT__>`, and supply a variables file in `YAML`, which swaps out the template strings from **A)** literal string values from your YAML file, or **B)** command (sequences) defined in your YAML file.

For example, the simplest promp file could look like this:
```
Generate a commit message for the following changes:
<__GIT_DIFF__>
<__RESPONSE__REQUIREMENTS__>
```

or a more complex prompt file:
```
You are an expert software developer who writes clear and concise commit messages.
Your task is to generate a commit message based on the following instructions,
if present:
<__INSTRUCTIONS__>
The commit message should follow these guidelines:
<__COMMIT_MESSAGE_GUIDELINES__>
Here are the changes that need to be committed:
<__GIT_DIFF__>
Generate <__NUM_COMMIT_MESSAGES__> commit message candidates that adheres to the
above guidelines.
Here are the test results for the changes:
<__TEST_RESULTS__>
<__RESPONSE__REQUIREMENTS__>
```

With corresponding variable file:
```
vars:
  - template_string: "<__COMMIT_MESSAGE_GUIDELINES__>"
    value: |
      - Use the imperative mood in the subject line.
      - Limit the subject line to 50 characters.
      - Wrap the body at 72 characters.
      - Use the body to explain what and why vs. how.
  - template_string: "<__NUM_COMMIT_MESSAGES__>"
    value: "3"
  - template_string: "<__TEST_RESULTS__>"
    value_from: "pnpm test:unit --reporter=summary"
```

**Comment by rakotomandimby** [comment]
Well, 

I made a one-file BASH script that would be a replacement of `aichat` in the precise context of this issue.
Explanations in https://mihamina.rktmb.org/2025/11/lazygit-ai-commit-message.html or https://github.com/rakotomandimby/lgaicm for the direct link to the tool.

Thank you all.

**Comment by alanfzf** [comment]
If anyones using the new `github-copilot-cli` here's a small script i made:

```bash

# Allowed choices are
# - claude-sonnet-4.5
# - claude-haiku-4.5
# - claude-opus-4.5
# - claude-sonnet-4
# - gpt-5
# - gpt-5.1
# - gpt-5.1-codex-mini
# - gpt-5.1-codex
# - gpt-5-mini
# - gpt-4.1
# - gemini-3-pro-preview.

model="gpt-4.1"
diff_output="$(git diff --cached)"
diff_unstaged="$(git diff)"

if [ -z "$diff_output" ]; then
  echo "Error: No staged changes."
  exit 1
fi

if [ -n "$diff_unstaged" ]; then
  echo "Error: There are unstaged changes. Please stage or stash them first."
  exit 1
fi


prompt="
You are an expert at writing Git commits. Your job is to write commit messages that follow the Conventional Commits format.

Your task is to:
1. Analyze the code changes
2. Determine the most appropriate commit type
3. Determine an appropriate scope (component/area affected)
4. Decide if this is a breaking change
5. Write clear, concise commit messages
6. Write exactly 10 different commit proposals

**Instructions**:
1. Please respond only with the suggested commit messages, with no additional explanations.
2. Structure: <type>(<scope>): <description>
3. Allowed types:
  - feat: new feature implemented
  - fix: bug fix
  - docs: documentation changes, README, etc.
  - style: changes that do not affect code meaning (whitespace, formatters, etc.)
  - refactor: code change that neither fixes a bug nor adds a feature
  - perf: code change that improves performance
  - test: add missing tests or fix existing tests
  - chore: maintenance tasks that do not affect source code or tests
  - build: changes that affect the build system or external dependencies (e.g., pnpm, composer, etc.)
  - ci: changes in CI configuration files or scripts (e.g., GitHub Actions, etc.)
  - revert: revert a previous commit
4. A scope must be added in parentheses if the changes affect a specific area of the code (e.g., auth, api, ui, etc.). If not applicable, it may be omitted.
5. If the change is breaking, add an exclamation mark '!' immediately after the scope or after the type if there is no scope.
6. Description: must be a brief and concise summary of the changes made, written in present tense and without a period. If there are multiple related changes, they must all be included in the same message.

**Examples**:
1. build!: update Webpack configuration to support ES modules
2. feat(products): add advanced search filter to products view
3. fix: fix issue preventing saving users without a secondary email
4. chore: clean unused dependencies in package.json
5. ci: adjust GitHub Actions workflow to run tests on Node 20
6. docs: update installation guide with new system requirements
7. perf: optimize SQL query to reduce dashboard load time
8. refactor: reorganize components to improve code readability
9. revert: revert 'feat: add OTP authentication'
10. style: apply standard formatting according to prettier
11. test: add unit tests for form validation module


**Previous commits for context**:
$(git log --oneline -10)


**Changes to analyze**:
$(git diff --cached --stat)

\`\`\`diff
$diff_output
\`\`\`
"

msg="$(
  copilot --model "$model" -s -p "$prompt" \
    | grep -v '^$' \
    | fzf --ansi \
    | cat
)"

if [ -z "$msg" ]; then
  echo "Error: commit message is empty. Aborting."
  exit 1
fi

git commit -m "$msg"
```

**Comment by dimaportenko** [comment]
My solution with **claude code** - 
```yaml
  customCommands:
    - key: "C"
      context: "files"
      description: "Generate commit message with Claude Code"
      command: "git diff --staged | /PATH/TO/claude -p 'Generate a concise git com
mit message for these staged changes. Output ONLY the raw commit message with no m
arkdown, no code blocks, no backticks, no explanations. Use conventional commit fo
rmat.' --model haiku --output-format text > /tmp/commit_msg && GIT_EDITOR=vim git 
commit -e -F /tmp/commit_msg"
      output: terminal
```
More details in reddit post - https://www.reddit.com/r/ClaudeCode/comments/1ps6wk6/lazygit_claude_code_aigenerated_commit_messages/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by Keshav-writes-code** [comment]
@alanfzf how to use your script in config.toml?

**Comment by alanfzf** [comment]
> [@alanfzf](https://github.com/alanfzf) how to use your script in config.toml?

hello you create the script under ~/.local/bin to be globally available to your user and adjust lazygit config like [this](https://github.com/alanfzf/.dotfiles/blob/fe9b92a0755ac6660bf124e54bc607917573469d/config/lazygit/config.yml#L18C1-L23C21)

**Comment by phuchoang2603** [comment]
thanks to @dimaportenko , i can also implement this with opencode. i use nix but you can copy the command and replace it with your config file.

```nix
  programs.lazygit = {
    enable = true;
    settings = {
      git = {
        commit = {
          signOff = true;
        };
      };
      customCommands = [
        {
          key = "C";
          command = ''
            git diff --staged | /etc/profiles/per-user/felix/bin/opencode run --attach http://localhost:4096 --model github-copilot/gpt-5.4-mini 'Generate a concise git commit message for these staged changes. Output ONLY the raw commit message with no markdown, no code blocks, no backticks, no explanations. Use conventional commit format.' > /tmp/commit_msg && git commit -e -F /tmp/commit_msg
          '';
          description = "Generate commit message with Opencode";
          context = "files";
          output = "terminal";
        }
      ];
    };
  };

```

**Comment by FeernandoOFF** [comment]
For anyone using OpenCode, here's my configuration :D 

https://github.com/user-attachments/assets/24a391d7-12bc-4597-87f1-aa9b1d7989bd

```yaml
customCommands:
  - key: "<c-a>"
    description: "AI-powered conventional commit"
    context: "global"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "AI defined"
            description: "Let AI analyze and determine the best commit type"
            value: "ai-defined"
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
      - type: "menuFromCommand"
        title: "AI Generated Commit Messages"
        key: "CommitMsg"
        command: |
          bash -lc '
          diff=$(git diff --cached)
          if [ -z "$diff" ]; then
            echo "No changes in staging. Add changes first."
            exit 1
          fi

          SELECTED_TYPE="{{.Form.Type}}"
          COMMITS_TO_SUGGEST=4

          opencode run --format json --model=openai/gpt-5.5 --variant=none "
          You are an expert at writing Git commits. Your job is to write commit messages that follow the Conventional Commits format.

          The user has selected: $SELECTED_TYPE

          Your task is to:
          1. Analyze the code changes
          2. Determine the most appropriate commit type if user selected ai-defined
          3. Determine an appropriate scope, component, or area affected
          4. Decide if this is a breaking change
          5. Write clear, concise commit messages

          Available commit types:
          - feat: A new feature
          - fix: A bug fix
          - docs: Documentation only changes
          - style: Changes that do not affect the meaning of the code
          - refactor: A code change that neither fixes a bug nor adds a feature
          - perf: A code change that improves performance
          - test: Adding missing tests or correcting existing tests
          - build: Changes that affect the build system or external dependencies
          - ci: Changes to CI configuration files and scripts
          - chore: Other changes that do not modify src or test files
          - revert: Reverts a previous commit

          Follow these guidelines:
          - Structure: <type>(<scope>): <description>
          - If user selected ai-defined, analyze the changes and pick the most suitable type
          - If user selected a specific type, use that type: $SELECTED_TYPE
          - Add scope in parentheses if applicable, for example auth, api, ui, config
          - Use exclamation mark after type or scope for breaking changes: type(scope)!: description
          - Use lowercase for description except proper nouns
          - Use imperative mood: add, not added
          - Keep description under 50 characters when possible
          - No period at the end of subject line

          IMPORTANT:
          - Generate exactly $COMMITS_TO_SUGGEST different commit message options
          - If user selected ai-defined, you can use different types for different options
          - If user selected a specific type, all messages must use that type
          - Only return commit messages, no explanations
          - Do not use markdown code blocks
          - One message per line

          Previous commits for context:
          $(git log --oneline -10)

          Changes to analyze:
          $(git diff --cached --stat)
          $diff
          " | JQ_TEXT=text jq -r "select(.type == env.JQ_TEXT) | .part.text? // empty"
          '
    command: "git commit -m \"{{.Form.CommitMsg}}\""
    loadingText: "Generating commit messages..."

```
