### ISSUE TITLE
$PAGER is overwriting git.paging.pager

### ISSUE THREAD

**Issue by joshmedeski** [jesseduffield/lazygit#3235]
**Describe the bug**
I setup a custom pager in the lazygit config and my PAGER environmental variable is overwriting it.

**To Reproduce**

1. Set the following paging configuration in the lazygit `config.yml`:
```yml
git:
  paging:
    useConfig: true
    colorArg: always
    pager: delta --color-only --side-by-side
```
2. Set $PAGER in your shell (I use fish)
```sh
set -U PAGER "~/.local/bin/nvimpager"
```
3. View lazygit diffs

**Expected behavior**
I expect "delta" to be prioritized because of the lazygit config value

**Version info:**
commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=arm64, git version=2.43.0
git version 2.43.0

**Additional context**
I can confirm that delta works again when I unset the PAGER env variable
