### ISSUE TITLE
Support abs file path

### ISSUE THREAD

**Issue by konosubakonoakua** [jesseduffield/lazygit#3253]
**Is your feature request related to a problem? Please describe.**
Currently I'm using key mapping below to open file in neovim:
```yaml
  - key: 'o'
    command: 'nvim --server $NVIM --remote-tab "$(git -C $(dirname {{.SelectedFile.Name}}) rev-parse --show-toplevel)/{{.SelectedFile.Name}}"'
    context: 'files'
    subprocess: true
    description: 'Open file in Neovim'

```
It is kind of ugly workaround, can we have a more elegant method?

**Describe the solution you'd like**
It would be nice if we can use `abspath`:
```yaml
  - key: 'o'
    command: 'nvim --server $NVIM --remote-tab {{.SelectedFile.abspath}}"'
```

**Related**
https://github.com/jesseduffield/lazygit/discussions/3160
