### ISSUE TITLE
Search by commit hash in Remotes / Local Branches / Tags

### ISSUE THREAD

**Issue by all500234765** [jesseduffield/lazygit#3265]
**Is your feature request related to a problem? Please describe.**
When reviewing someone I ask for commit hash or branch name.
Some times there will be a branch with multiple commits and i'd need to find a specific one.

**Describe the solution you'd like**
1. Go into Remotes tab
2. Select and enter to the specific remote to search in
4. Press / to start search
5. Paste commit hash
6. Search results should show branches with relevant commits

**Describe alternatives you've considered**
1. Using tortoise git to search for specific commit by hash
2. Ctrl + o on random commit in Commits window, then replacing hash in the link, looking at the branch and then going into Remotes/origin search for the branch.
3. Always ask for the branch name (sometimes will require to ask for the specific commit i should review too). Still good, but could be improved

**Additional context**
Quick google search revials that git can do this very easily.
``git branch -r --contains <commit hash>``

This command lists all remote branches that have specified commit.

Searching by partial commit name would be good, like searching by specific ticket number, since sometimes you can end up with a branch that has multiple different commits with different tickets they relate to.

**Comment by TheLazyLemur** [comment]
Hey everyone.  

Would you be happy if I worked on this issue?

**Comment by abourget** [comment]
`gitk` displays all the branches that "include" a commit, I find it massively useful, when I'm looking at a commit (say in the Commits panel), and can see if that commit is in `master`, `develop`, or just in my feature branch.

Indeed, `git branch --contains` does the trick, what's the best way to integrate it? Perhaps with a custom shortcut?

**Comment by stefanhaller** [comment]
> and can see if that commit is in `master`, `develop`, or just in my feature branch.

You can easily tell this by the color of the commit hash; if it's green, it is contained in master or develop, if it's yellow or red it isn't. This assumes that you configured your `git.mainBranches` config appropriately.

If you don't remember whether your current branch is based on master or on develop, you can find out by selecting it in the branches view and typing `u`; the second entry in that menu ("View divergence from base branch") tells you which branch is your base branch.

> Indeed, `git branch --contains` does the trick, what's the best way to integrate it? Perhaps with a custom shortcut?

This is easy to do with a custom command:
```yml
customCommands:
  - key: <whatever>
    command: git branch -a --contains {{.SelectedCommit.Hash}}
    context: commits,subCommits
    description: Show branches containing commit
    output: popup
```

This doesn't address the need of the OP; for that, you'd need a command such as
```yml
customCommands:
  - key: <whatever>
    prompts:
      - type: input
        title: Commit hash to search for
        key: Hash
    command: git branch -a --contains {{.Form.Hash}}
    context: global
    description: Show branches containing commit
    output: popup
```
