### ISSUE TITLE
Wrong colours when selecting line/hunk

### ISSUE THREAD

**Issue by sho-87** [jesseduffield/lazygit#3327]
**Describe the bug**
When looking at a diff, the text, green, and red colours look correct as per my terminal settings (wezterm), but when I highlight a line or a hunk the red and green colours change slightly and the regular text colour completely inverts

**Screenshots**
From the screenshots you can see the red has almost gone back to ff0000, green is now 00ff00, the cyan(?) is a lot brighter and the whiteish text has turned to black. unsure if this colour adjustment under selection is intended or if its a bug

Unselected:

![image](https://github.com/jesseduffield/lazygit/assets/5199715/d4a5d86d-cf12-4e17-82bb-f95fb3033743)

Selected:

![image](https://github.com/jesseduffield/lazygit/assets/5199715/df274b45-45b6-4ec9-b092-ccfe3b256967)

**Version info:**
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=windows, arch=amd64, git version=2.43.0.windows.1

**Additional context**
colour section of my config:

```
theme:
    activeBorderColor:
      - '#a292a3'
      - bold
    inactiveBorderColor:
      - '#DCD7BA'
    searchingActiveBorderColor:
      - '#a292a3'
      - bold
    optionsTextColor:
      - '#658594'
    selectedLineBgColor:
      - '#2A2A37'
    selectedRangeBgColor:
      - '#4e6773'
    cherryPickedCommitBgColor:
      - '#8ea4a2'
    cherryPickedCommitFgColor:
      - '#658594'
    unstagedChangesColor:
      - '#b98d7b'
    defaultFgColor:
      - default
 ```

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

(unsure how to switch to master when installed via scoop)
