### ISSUE TITLE
`commitPrefix` options doesn't work

### ISSUE THREAD

**Issue by zeromask1337** [jesseduffield/lazygit#3556]
**Describe the bug**
`commitPrefix` option simply doesn't work. However if I replace it with `commitPrefixes` with same options as first one, then it works.

This works
```yaml
git:
  commitPrefixes:
    my_project:
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: "[$1] "
```

This doesn't
```yaml
git:
  commitPrefix:
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: "[$1] "
```

**To Reproduce**

1. Go to your config file, `.config/lazygit/config.yml` in my case
2. Paste and save 
```yaml
git:
  commitPrefix:
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: "[$1] "
```
4. Restart lazygit
5. Try to commit and see no prefix

**Expected behavior**
Prefix is present in commit message

**Version info:**
_Run `lazygit --version` and paste the result here_ `commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=arm64, git version=2.39.3 (Apple Git-145)
`
_Run `git --version` and paste the result here_ `git version 2.39.3 (Apple Git-145)`
