### ISSUE TITLE
Feature request: Allow defining custom popup title when using `showOutput`

### ISSUE THREAD

**Issue by kgrhartlage** [jesseduffield/lazygit#3576]
**Is your feature request related to a problem? Please describe.**

When using the `showOutput` option to display the output of non-trivial commands, the popup title is no longer descriptive in the sense that it's too verbose. Even if one would like to see the full command, this very quickly is no longer possible since it gets cut off. Here is an example:

<img width="847" alt="CleanShot 2024-05-19 at 11 06 29@2x" src="https://github.com/jesseduffield/lazygit/assets/42832087/5b15d2a4-f28a-4462-b083-82c788e2d7b0">

**Describe the solution you'd like**

I would like to define a custom title. Static strings would work for my use cases. For the above example I might want to have _"Jira Issue Details"_ as the title.

The schema could support both a "shorthand" boolean value and object configuration like this:

```yaml
command: 'jira issue view $(printf %s {{.SelectedLocalBranch.Name}} | grep -o "CUB-[0-9]*") --comments 5'
showOutput:
  title: Jira Issue Details
```

Being able to use templates would be the cherry on the top.

**Describe alternatives you've considered**

One could extract the command in a script that results in a command with a very short path. That added step is very undesirable for me personally and the result would only be mildly better.

**Additional context**

Thank you so much creating this wonderful tool and considering my humble request 🤗
