### ISSUE TITLE
Keybindings for Custom Command's Prompt menus

### ISSUE THREAD

**Issue by rtalexk** [jesseduffield/lazygit#3626]
I'm creating a custom command with a menu prompt, similar to the "Reset to [commit hash]" menu.

<img width="980" alt="image" src="https://github.com/jesseduffield/lazygit/assets/16341644/d23d4ae4-4a16-4d8c-95e2-051b19ef57be">

Mine looks like this:

<img width="964" alt="image" src="https://github.com/jesseduffield/lazygit/assets/16341644/b1a281aa-2e82-4b1f-ad61-e4f53fcde6f9">

<details>
<summary>Configuration</summary>

In summary, what this does is allowing me to edit a file by reusing an existing $EDITOR instance in a Tmux window. Or, I can also choose to edit the file in the current window, or in a new $EDITOR instance (that's handled by the `lazygit_edit_cmd` script).

```yml
customCommands:
  - name: "edit"
    context: "files"
    key: "e"
    prompts:
      - type: "menu"
        title: "Editor instance"
        key: "WinChoise"
        options:
          - value: "reuse"
            description: "Search for a Window with an EDITOR instance"
            key: "r" # <-- This is what I want
          - value: "current"
            description: "Edit the file in the current window"
            key: "c" # <-- This is what I want
          - value: "new"
            description: "Edit the file in a new window"
            key: "n" # <-- This is what I want
    command: "lazygit_edit_cmd -w {{.Form.WinChoise}} {{.SelectedFile.Name}}"
    subprocess: true
```

</details>

**Describe the solution you'd like**
What I would like to have is mapping some keybinding to options in the prompt menu, just as in the Reset menu with `m` for `Mixed`, `s` for `Soft` and `h` for `Hard` reset.

Right now I mostly use the "Reuse" option (that's why it is the first one), and that's my workaround, but it would be cool if that's something that can be configured.

I read the [Custom Commands docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) and I didn't see any way to set bindings, if I missed that part please let me know.
