### ISSUE TITLE
Allow replacing close event to custom commands

### ISSUE THREAD

**Issue by xzbdmw** [jesseduffield/lazygit#3699]
**Is your feature request related to a problem? Please describe.**
In neovim, I use floating terminal to open lazygit, and it makes perfect sense if close event is translated into a custom command such as `nvim --remote --send-keys "<Cmd>close<cr>"' which hide the terminal window, so next time lazygit does not need to restart.

**Describe the solution you'd like**
Adds a new keymap to trigger custom commands everytime layzgit is about to close itself, and keep a keymap to actually close lazygit when needed.

**Describe alternatives you've considered**
I can bind a key in neovim to toggle terminal, but it is not intuitive to use because return at top level is very useful but can not be achieved in neovim side(I'm so used to press esc so many time I just unexpected close lazygit).
**Additional context**

**Comment by stefanhaller** [comment]
You should be able to do this already using a config like this:
```yaml
customCommands:
  - key: "q"
    command: 'nvim --remote --send-keys "close"'
    context: "global"
    description: "Quit"
keybinding:
  universal:
    quit: <disabled>
```

Let me know if this works!
