### ISSUE TITLE
Support multiple contexts for a custom command

### ISSUE THREAD

**Issue by yam-liu** [jesseduffield/lazygit#3759]
**Is your feature request related to a problem? Please describe.**
I want to add a 'N' for "creating branch without checking it out".
I added this command. 
```
  - key: "N"
    description: 'Create a new branch without checking it out'
    command: "git branch {{index .PromptResponses 0}} {{.SelectedLocalCommit.Sha}}"
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'New branch name (no checkout)'
        initialValue: ''
```
But I want to add it to all commit-related tabs.

**Describe the solution you'd like**
Propose a solution with a context array like this:
```
  - key: "N"
    description: 'Create a new branch without checking it out'
    command: "git branch {{index .PromptResponses 0}} {{.SelectedLocalCommit.Sha}}"
    context: 
      - 'commits'
      - 'subCommits'
      - 'reflogCommits'
      - 'localBranches'  
    // should be compatible with the original single-value string format.
    // or '1,2,3' format is also okay for me.
    prompts:
      - type: 'input'
        title: 'New branch name (no checkout)'
        initialValue: ''
```

**Describe alternatives you've considered**
no.

**Additional context**
'global' is not always working to create branch off a commit.
