### ISSUE TITLE
implement github release

### ISSUE THREAD

**Issue by bckelley** [jesseduffield/lazygit#3822]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to create releases using lazy git which can be accomplished with github cli command `gh release create [<tag>] [<files>...] ` [Source](https://cli.github.com/manual/gh_release_create)

**Describe alternatives you've considered**
No alternatives in LazyGit user has to run aforementioned GitHub cli command as well

**Additional context**

**Comment by ghost-in-the-zsh** [comment]
Might just be me, but it doesn't seem like a good idea to couple LazyGit to anything other than Git itself. Platforms like GitHub, GitLab, <you-name-it>, seem like things beyond the scope of what LG should be focusing on.

**Comment by alexandre-croteau** [comment]
I use the custom command `:` for this kind of stuff. Works like a charm !

**Comment by bckelley** [comment]
> Might just be me, but it doesn't seem like a good idea to couple LazyGit to anything other than Git itself. Platforms like GitHub, GitLab, you-name-it, seem like things beyond the scope of what LG should be focusing on.

Yea I see your point ... git is bigger then anyone platform, and should be kept that way!

**Comment by bckelley** [comment]
I think as for now I will close this as not wont fix/not planned

**Comment by alexandre-croteau** [comment]
> I'm gonna give this a shot you have any examples you might share?

Here is something to start with. See [Custom Command Keybindings](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) and [Custom Commands Compendium](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium) for more details.

```yaml
  - key: "<c-c>"
    context: "tags"
    description: "GitHub Create Release"
    prompts:
      - type: "input"
        title: "Version"
        key: "Tag"
        suggestions:
          preset: "tags"
      - type: "confirm"
        title: "Create GitHub Release"
        key: "confirm"
        body: "Ready to create {{ .Form.Tag }} ?"
    command: "gh release create {{ .Form.Tag }} --generate-notes --latest"
    loadingText: "Creating GitHub release..."
```
