### ISSUE TITLE
Interacting with Custom Command Output (Git-Town)

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [jesseduffield/lazygit#3841]
**Is your feature request related to a problem? Please describe.**
Some shell commands prompt for information during execution. Currently, custom commands are not interactable. For example, some `git-town` commands have built-in prompts: 
``` 
Please select the parent of branch "lakjflkjalfjk" or enter its number.
Most of the time this is the main branch (main).


0   <none> (perennial branch)
1 > main


  ↑/k up   ↓/j down   ←/u page up   →/d page down   0-9 jump   enter/o accept   q/esc/ctrl-c abort
```

**Describe the solution you'd like**
Allow custom commands to be interactable through a popup window.

**Describe alternatives you've considered**
Advanced custom command scripting has been considered. Changing how and when the custom program prompts for information is currently being considered. 

**Additional context**
[Git-Town](https://github.com/git-town/git-town) has many amazing commands that I have been attempting to fit into lazygit with custom commands. The limitation is when git-town occasionally needs user input during the middle of running a command. This will block the program from running and lock lazygit. I have created an [issue](https://github.com/git-town/git-town/issues/3869) to discuss this further on git-towns side. The following is the current state of the custom bindings for anyone interested in combining git-town and lazygit:

``` yaml
customCommands:
  - key: 'Y'
    context: 'global'
    description: 'Git-Town sYnc'
    command: 'git-town sync --all'
    stream: true
    loadingText: 'Syncing'
  - key: 'U'
    context: 'global'
    description: 'Git-Town Undo (undo the last git-town command)'
    command: 'git-town undo'
    prompts:
    - type: 'confirm'
      title: 'Undo Last Command'
      body: 'Are you sure you want to Undo the last git-town command?'
    stream: true
    loadingText: 'Undoing Git-Town Command'
  - key: '!'
    context: 'global'
    description: 'Git-Town Repo (opens the repo link)'
    command: 'git-town repo'
    stream: true
    loadingText: 'Opening Repo Link'
  - key: 'a'
    context: 'localBranches'
    description: "Git-Town Append"
    prompts:
      - type: 'input'
        title: "Enter name of new child branch. Branches off of '{{.CheckedOutBranch.Name}}'"
        key: 'BranchName'
    command: 'git-town append {{.Form.BranchName}}'
    stream: true
    loadingText: 'Appending'
  - key: 'h'
    context: 'localBranches'
    description: 'Git-Town Hack (creates a new branch)'
    prompts:
      - type: 'input'
        title: "Enter name of new branch. Branches off of 'Main'"
        key: 'BranchName'
    command: 'git-town hack {{.Form.BranchName}}'
    stream: true
    loadingText: 'Hacking'
  - key: 'K'
    context: 'localBranches'
    description: 'Git-Town Kill (deletes the current feature branch and sYnc)'
    command: 'git-town kill'
    prompts:
    - type: 'confirm'
      title: 'Delete current feature branch'
      body: 'Are you sure you want to delete the current feature branch?'
    stream: true
    loadingText: 'Killing Feature Branch'
  - key: 'p'
    context: 'localBranches'
    description: 'Git-Town Propose (creates a pull request)'
    command: 'git-town propose'
    stream: true
    loadingText: 'Creating pull request'
  - key: 'P'
    context: 'localBranches'
    description: "Git-Town Prepend (creates a branch between the curent branch and its parent)"
    prompts:
      - type: 'input'
        title: "Enter name of the for child branch between '{{.CheckedOutBranch.Name}}' and its parent"
        key: 'BranchName'
    command: 'git-town prepend {{.Form.BranchName}}'
    stream: true
    loadingText: 'Prepending'
  - key: 'S'
    context: 'localBranches'
    description: 'Git-Town Skip (skip branch with merge conflicts when syncing)'
    command: 'git-town skip'
    stream: true
    loadingText: 'Skiping'
  - key: 'G'
    context: 'files'
    description: 'Git-Town GO aka:continue (continue after resolving merge conflicts)'
    command: 'git-town continue'
    stream: true
    loadingText: 'Continuing'
```

**How to reproduce**
1. First, download git-town. 
2. Include the above custom commands in your lazygit `config.yaml`.  
3. Create a branch in the 'localbranches' tab using `h`.
4. Make an arbitrary change in the branch.
5. Without committing the change, attempt to delete the branch using `K` in the 'localbranches'
6. Git-town will prompt for input in the shell, which is inaccesible and will catch lazygit in a loop.
