### ISSUE TITLE
Mouse hover follows delta Hyperlinks

### ISSUE THREAD

**Issue by mayorbyrne** [jesseduffield/lazygit#3928]
**Describe the bug**
I'm seeing some unintended behavior with regards to hyperlinks in delta. They work as expected on first click, but after that it appears to follow every link by simply hovering over the hyperlink.

**To Reproduce**
1. I click a hyperlink in a diff, which opens the file in the editor (neovim)
2. close the file
3. Now simply hovering over a link in the diff opens the file again
4. This behavior appears to resolve itself after the terminal window loses focus

**Expected behavior**
Hyperlinks should only be followed on an actual mouse click.

**Screenshots**

**Version info:**
`commit=, build date=, build source=homebrew, version=0.44.1, os=darwin, arch=arm64, git version=2.39.5 (Apple Git-154)`
`git version 2.39.5 (Apple Git-154)`

**Additional context**
I'm using the suggested config
```
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
```

**Screen Recording of the issue**

![lazygit](https://github.com/user-attachments/assets/e3af5fde-8eba-4009-b8ea-f2ebabeb2815)
