### ISSUE TITLE
Title in custom command doesn't work

### ISSUE THREAD

**Issue by andyl** [jesseduffield/lazygit#4005]
**Describe the bug**

I have a custom command that sets the 'title' property.  The titles doesn't show in the popup window.  Instead the command text is displayed.

**To Reproduce**

```
customCommands:
  - key: 'h'
    command: 'echo HELLO WORLD'
    context: 'global'
    title: 'Message of the Day'
    showOutput: true
```

**Version info:**

Lazygit 0.44.1 

**Additional context**

I'm a huge fan of Lazygit!
