### ISSUE TITLE
Changing the default commit string

### ISSUE THREAD

**Issue by Eloquencere** [jesseduffield/lazygit#4038]
**Describe the solution you'd like**
I don't prefer having the default commit message as 'main'; having a default commit string in the config.yaml would be an amazing addition. Maybe even piping it into another command that can generate the commit string based on the `cwd` or something can be considered.

**Describe alternatives you've considered**
None

**Additional context**
None

```
customCommands:
  - key: '<c-c>'
    description: 'commit as non-default author'
    command: 'git commit -m "{{index .PromptResponses 0}}" --author="{{index .PromptResponses 1}} <{{index .PromptResponses 2}}>"'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Commit Message'
        initialValue: ''
      - type: 'input'
        title: 'Author Name'
        initialValue: ''
      - type: 'input'
        title: 'Email Address'
        initialValue: ''
    loadingText: 'commiting'
```
