### ISSUE TITLE
Make custom command interactive

### ISSUE THREAD

**Issue by felixschndr** [jesseduffield/lazygit#4047]
**Is your feature request related to a problem? Please describe.**
When a custom command is specified in the config it runs it with `bash -c "<command>"`. I'd like this shell to be interactive to be able to run shell aliases which lie in my `.bashrc`.

**Describe the solution you'd like**
Run `bash -ic "<command">`

**Describe alternatives you've considered**
Currently I am adding a layer of bash:
```yaml
  - key: <c-d>
    context: "localBranches, remoteBranches"
    command: bash -ic "git_delete_old_branches"
    stream: true
```
which runs `bash -c bash -ic "git_delete_old_branches"`

**Additional context**
Maybe make this a config variable?

I tried to go through the source code to check where the `bash -c` (without `-i`) is invoked but was a bit overwhelmed by the search results. If someone could show me where this is done I'd take a crack at creating a PR.
