### ISSUE TITLE
Commitizen integration

### ISSUE THREAD

**Issue by jukefr** [jesseduffield/lazygit#41]
It would be nice to have commitizen integration, or a similar feature that allows you to use predefined commit messages.

For reference :
- https://github.com/commitizen/cz-cli
- https://github.com/commitizen/cz-conventional-changelog

**Comment by jesseduffield** [comment]
I'm thinking we could have a flag in the config that, when enabled, will use `git cz` over `git commit`, and unconditionally switch to a subprocess so that you can fill out the prompt. There's work in the gocui repo to enable showing the cz prompts inside of lazygit but it might take some time to properly get that over the line

**Comment by jesseduffield** [comment]
I've added this as a custom command in the [Custom Commands Compendium](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium), as a replacement for the default `git commit` behaviour upon pressing shift+c in the files panel.

There are quite a few upvotes on this one so if anybody had something different in mind, or thinks that this should work out of the box with lazygit, do let me know!

I'll close this ticket for now :)

**Comment by ceuk** [comment]
Great solution IMO

**Comment by rogerioefonseca** [comment]
> Great solution IMO

Working nicely here, thanks @ceuk

**Comment by Cronos87** [comment]
I don't know if it's the place, but I wrote a simple command to have everything inside lazygit.

It could be enhanced; I wrote it down quickly for testing purposes 😊

Textes and style copied from vivaxy's extension (yeah, testing purposes…)

https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits

```yml
customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}: {{ .Form.Description }}"'
    description: "commit with commitizen"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat"
          - name: "Fix"
            description: "a bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "Performance Improvements"
            description: "A code change that improves performance"
            value: "perf"
          - name: "Tests"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
          - name: "Builds"
            description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
            value: "build"
          - name: "Continuous Integration"
            description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
            value: "ci"
          - name: "Chores"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "Reverts"
            description: "Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Enter the scope(s) of this change."
        key: "Scopes"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}: {{ .Form.Description }}"
```

**Comment by leikoilja** [comment]
Awesome, thank you @Cronos87 for sharing your config. 🚀 
I needed an extra input prompt to mark a commit as a breaking change or not, so a few rounds through LLM and expanded your config a bit to be:
```yml
customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{if eq .Form.Breaking `yes`}}!{{end}}: {{ .Form.Description }}"'
    description: "commit with commitizen"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "A new feature"
            value: "feat"
          - name: "Fix"
            description: "A bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "Performance Improvements"
            description: "A code change that improves performance"
            value: "perf"
          - name: "Tests"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
          - name: "Builds"
            description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
            value: "build"
          - name: "Continuous Integration"
            description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
            value: "ci"
          - name: "Chores"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "Reverts"
            description: "Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Enter the scope(s) of this change."
        key: "Scopes"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "menu"
        title: "Is this a breaking change?"
        key: "Breaking"
        options:
          - name: "No"
            description: "This change does not introduce a breaking change."
            value: "no"
          - name: "Yes"
            description: "This change introduces a breaking change."
            value: "yes"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{if eq .Form.Breaking `yes`}}!{{end}}: {{ .Form.Description }}"
```

**Comment by ndland** [comment]
These are great! But how do you deal with a longer commit message? These all seem only to have subject line, but what about body?

**Comment by leikoilja** [comment]
did anyone figure out how to make this work alongside precommit hooks? Now if a precommit hook is failed (let's say it's auto fixing some formatting), the commit description is not preserved :/

**Comment by timhagel** [comment]
Though I would share my command to make this like the VS Code Conventional Commits extension

It should be pretty easy to add the long description to this if you need it :)

(You will need to [install jq](https://github.com/jqlang/jq))

```
customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"'
    description: "conventional commit"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat"
          - name: "Fix"
            description: "a bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Styling changes (white-space, formatting, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "Refactoring code"
            value: "refactor"
          - name: "Performance Improvements"
            description: "Performance improvements"
            value: "perf"
          - name: "Tests"
            description: "Test additions or fixes"
            value: "test"
          - name: "Builds"
            description: "Build system or dependency changes"
            value: "build"
          - name: "Continuous Integration"
            description: "CI configuration changes"
            value: "ci"
          - name: "Chores"
            description: "Other non-code changes"
            value: "chore"
          - name: "Reverts"
            description: "Reverting changes"
            value: "revert"
      - type: "menu"
        title: "Choose the emoji for this commit type."
        key: "Emoji"
        options:
          - name: "🎨 Improve structure / format of the code."
            value: ":art:"
          - name: "⚡️ Improve performance."
            value: ":zap:"
          - name: "🔥 Remove code or files."
            value: ":fire:"
          - name: "🐛 Fix a bug."
            value: ":bug:"
          - name: "🚑️ Critical hotfix."
            value: ":ambulance:"
          - name: "✨ Introduce new features."
            value: ":sparkles:"
          - name: "📝 Add or update documentation."
            value: ":memo:"
          - name: "🚀 Deploy stuff."
            value: ":rocket:"
          - name: "💄 Add or update the UI and style files."
            value: ":lipstick:"
          - name: "🎉 Begin a project."
            value: ":tada:"
          - name: "✅ Add, update, or pass tests."
            value: ":white_check_mark:"
          - name: "🔒️ Fix security or privacy issues."
            value: ":lock:"
          - name: "🔐 Add or update secrets."
            value: ":closed_lock_with_key:"
          - name: "🔖 Release / Version tags."
            value: ":bookmark:"
          - name: "🚨 Fix compiler / linter warnings."
            value: ":rotating_light:"
          - name: "🚧 Work in progress."
            value: ":construction:"
          - name: "💚 Fix CI Build."
            value: ":green_heart:"
          - name: "⬇️ Downgrade dependencies."
            value: ":arrow_down:"
          - name: "⬆️ Upgrade dependencies."
            value: ":arrow_up:"
          - name: "📌 Pin dependencies to specific versions."
            value: ":pushpin:"
          - name: "👷 Add or update CI build system."
            value: ":construction_worker:"
          - name: "📈 Add or update analytics or track code."
            value: ":chart_with_upwards_trend:"
          - name: "♻️ Refactor code."
            value: ":recycle:"
          - name: "➕ Add a dependency."
            value: ":heavy_plus_sign:"
          - name: "➖ Remove a dependency."
            value: ":heavy_minus_sign:"
          - name: "🔧 Add or update configuration files."
            value: ":wrench:"
          - name: "🔨 Add or update development scripts."
            value: ":hammer:"
          - name: "🌐 Internationalization and localization."
            value: ":globe_with_meridians:"
          - name: "✏️ Fix typos."
            value: ":pencil2:"
          - name: "💩 Write bad code that needs to be improved."
            value: ":poop:"
          - name: "⏪️ Revert changes."
            value: ":rewind:"
          - name: "🔀 Merge branches."
            value: ":twisted_rightwards_arrows:"
          - name: "📦️ Add or update compiled files or packages."
            value: ":package:"
          - name: "👽️ Update code due to external API changes."
            value: ":alien:"
          - name: "🚚 Move or rename resources (e.g.: files, paths, routes)."
            value: ":truck:"
          - name: "📄 Add or update license."
            value: ":page_facing_up:"
          - name: "💥 Introduce breaking changes."
            value: ":boom:"
          - name: "🍱 Add or update assets."
            value: ":bento:"
          - name: "♿️ Improve accessibility."
            value: ":wheelchair:"
          - name: "💡 Add or update comments in source code."
            value: ":bulb:"
          - name: "🍻 Write code drunkenly."
            value: ":beers:"
          - name: "💬 Add or update text and literals."
            value: ":speech_balloon:"
          - name: "🗃️ Perform database related changes."
            value: ":card_file_box:"
          - name: "🔊 Add or update logs."
            value: ":loud_sound:"
          - name: "🔇 Remove logs."
            value: ":mute:"
          - name: "👥 Add or update contributor(s)."
            value: ":busts_in_silhouette:"
          - name: "🚸 Improve user experience / usability."
            value: ":children_crossing:"
          - name: "🏗️ Make architectural changes."
            value: ":building_construction:"
          - name: "📱 Work on responsive design."
            value: ":iphone:"
          - name: "🤡 Mock things."
            value: ":clown_face:"
          - name: "🥚 Add or update an easter egg."
            value: ":egg:"
          - name: "🙈 Add or update a .gitignore file."
            value: ":see_no_evil:"
          - name: "📸 Add or update snapshots."
            value: ":camera_flash:"
          - name: "⚗️ Perform experiments."
            value: ":alembic:"
          - name: "🔍️ Improve SEO."
            value: ":mag:"
          - name: "🏷️ Add or update types."
            value: ":label:"
          - name: "🌱 Add or update seed files."
            value: ":seedling:"
          - name: "🚩 Add, update, or remove feature flags."
            value: ":triangular_flag_on_post:"
          - name: "🥅 Catch errors."
            value: ":goal_net:"
          - name: "💫 Add or update animations and transitions."
            value: ":dizzy:"
          - name: "🗑️ Deprecate code that needs to be cleaned up."
            value: ":wastebasket:"
          - name: "🛂 Work on code related to authorization, roles and permissions."
            value: ":passport_control:"
          - name: "🩹 Simple fix for a non-critical issue."
            value: ":adhesive_bandage:"
          - name: "🧐 Data exploration/inspection."
            value: ":monocle_face:"
          - name: "⚰️ Remove dead code."
            value: ":coffin:"
          - name: "🧪 Add a failing test."
            value: ":test_tube:"
          - name: "👔 Add or update business logic."
            value: ":necktie:"
          - name: "🩺 Add or update healthcheck."
            value: ":stethoscope:"
          - name: "🧱 Infrastructure related changes."
            value: ":bricks:"
      - type: "menuFromCommand"
        title: "Select a scope:"
        command: >
          bash -c "jq -r '.\"conventionalCommits.scopes\"[]' \"$(git rev-parse --show-toplevel)/.vscode/settings.json\""
        filter: "^(.*)$"
        valueFormat: "{{ .group_0 }}"
        labelFormat: "{{ .group_0 | cyan }}"
        key: "Scope"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"

```
