### ISSUE TITLE
Force remove worktree option

### ISSUE THREAD

**Issue by elgar-groot** [jesseduffield/lazygit#4125]
It seems impossible to remove a worktree that contains submodules from within lazygit.

An option (perhaps capital D) to remove worktree with the `--force` flag.

Otherwise perhaps a prompt to force the remove when it fails without the `--force` flag.

**Comment by jstmrby** [comment]
It would be nice to have this feature implemented 🚀

However, I'd say there's no need to bind it to a key. If there's a way to determine the repo contains a submodule it could offer a `Force remove` prompt automatically.
If that's not possible/too much work a probably easier solution to offer the force prompt after a failure.

**Comment by dessalines** [comment]
I'd love to see this also. If a project has submodules, then its impossible to easily remove the worktree.

**Comment by jamescrosswell** [comment]
Would love to see this. The repo I work with on a daily basis has loads of submodules... so I have to leave lazygit and use the command line to do this currently 😢

**Comment by mark2185** [comment]
> so I have to leave lazygit and use the command line to do this currently

Would a [custom command](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) work for you?

**Comment by jamescrosswell** [comment]
> Would a [custom command](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) work for you?

Awesome... thanks @mark2185 - this did the trick:
```yml
customCommands:
  - key: 'D'
    context: 'worktrees'
    description: 'Force remove selected worktree'
    prompts:
      - type: 'confirm'
        title: 'Force Remove Worktree'
        body: 'Are you sure you want to remove this worktree and any submodules?'
    command: 'git worktree remove -f {{ .SelectedWorktree.Path | quote }}'
    loadingText: 'Removing worktree...'
    output: log
```

As an aside, I'm not a go programmer but it looks like force remove for Worktrees is already supported but it's not triggered correctly by the specific error message that shows when the worktree contains submodules:
https://github.com/jesseduffield/lazygit/blob/3f30008224970ad54997db2ec7bbb449139afaef/pkg/gui/controllers/helpers/worktree_helper.go#L190-L201

Here's the error that's showing for submodules:

<img width="1188" height="101" alt="Image" src="https://github.com/user-attachments/assets/afd0a23b-c324-4945-9b64-4b9512bb9adb" />
