### ISSUE TITLE
chaining custom command issue on Windows

### ISSUE THREAD

**Issue by KevinNitroG** [jesseduffield/lazygit#4147]
**Describe the bug**

While defining a custom command keybindings with a chaining command, it failed to run on Windows using cmd shell.

**To Reproduce**

1. Config custom command keybindings in `~/AppData\Roaming\lazygit\config.yml`
	```yaml
	 customCommands:
	  - key: 'G'
	    context: 'global'
	    command: 'git reflog expire --all --expire=now && git gc --prune=now --aggressive'
	    description: 'clean up unnecessary files, reflog, optimize'
	    prompts:
	      - type: 'confirm'
	        title: 'Cleanup'
	        body: 'Are you sure you want to unnecessary files, reflog, optimize the repo?'
	    loadingText: 'Cleaning up'
        stream: true
	```
2. Go to a repo and run G key in lazygit

**Expected behavior**

The command run successfully

**Screenshots**

![image](https://github.com/user-attachments/assets/6efe5aec-607e-459e-8631-c404bbdd3fd7)

![image](https://github.com/user-attachments/assets/adfe00dc-9ee0-42af-8b8c-622042dfde2f)

**Version info:**

commit=611fabde11d24d9acc71ee26077b9a1101f59f27, build date=2024-09-18T10:56:10Z, build source=binaryRelease, version=0.44.1, os=windows, arch=amd64, git version=2.47.0.windows.2
