### ISSUE TITLE
Allow to use builtin actions via custom command

### ISSUE THREAD

**Issue by xzbdmw** [jesseduffield/lazygit#4187]
**Is your feature request related to a problem? Please describe.**
When I'm in nvim and open lazygit in builtin terminal, press "c" to edit commit mesage by calling a lua function (achievable), but when I'm in terminal, I want to use the original "c", that is, open the dialog (non-achievable?)

The same thing applies to quit, in nvim I want to hide the terminal (calling lua function) while in terminal  I want to kill lazygit (the original q)

**Describe the solution you'd like**
Pseudo code:
```yaml
  - key: "q"
    command: "if {{nvim}} nvim --server $NVIM --remote-send  '<cmd>lua CloseFromLazygit()<CR>' else{ feedkeys(q) }""
    context: "global"
    description: "Quit"
```
the `feedkeys` emulate the builtin behavior of "q".

**Describe alternatives you've considered**
Bind "c" or "q" in nvim to a different key and write custom command for that key.

**Additional context**
