### ISSUE TITLE
Layout flashing when use custom command

### ISSUE THREAD

**Issue by xzbdmw** [jesseduffield/lazygit#4189]
**Describe the bug**
as title

**To Reproduce**
config:
```yaml
# Config relating to the Lazygit UI
gui:
    # Number from 0 to 1.0.
    sidePanelWidth: 0.33
    # If true, increase the height of the focused side window; creating an accordion effect.
    expandFocusedSidePanel: false
    showBottomLine: false
customCommands:
  - key: <c-o>
    command: 'echo "hello"'
    context: "files"
```
press `<c-o>`, layout changes as if expandFocusedSidePanel and showBottomLine are both true for a very brief moment.

**Expected behavior**
no flashing

https://github.com/user-attachments/assets/6d204977-7780-416c-87d6-f6ce8dff8558

**Screenshots**
wrong moment：

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/dd0cd06a-791d-466d-9f83-fbdb0f5f8e4f" />

**Version info:**
Latest main

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
