### ISSUE TITLE
Set git.commitPrefix as a list instead of a dict to change several branch pattern into different commit messages prefixes

### ISSUE THREAD

**Issue by ginolegigot** [jesseduffield/lazygit#4194]
**Is your feature request related to a problem? Please describe.**
Hello! Would it be possible to set commitPrefix as a list so we can change/transform several branch patterns into several commit message prefix pattern ?

**Describe the solution you'd like**
For example something like this:
```yaml
git:
  commitPrefix:
    - pattern: "^\\w+-\\w+.*"
      replace: '[JIRA $0] '
    - pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] '
```
Currently we have:
```yaml
git:
  commitPrefix:
    pattern: "^\\w+-\\w+.*"
    replace: '[JIRA $0] '
```
Thanks for your reading !
