### ISSUE TITLE
Add command to copy diff in diff mode

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#4254]
**Is your feature request related to a problem? Please describe.**
When I use lazygit's diff mode (shift+w), I often want to copy the diff. E.g. to share the result of multiple commits in a code review. There doesn't seem to be an easy way to do this within lazygit.

**Describe the solution you'd like**
A command to copy the current diff generated by diff mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stefanhaller** [comment]
Is this only for diff ranges in the commits panel? If so, I'm wondering if you know about the more ad-hoc feature of selecting a range of commits using shift-arrow, and seeing the diff for those commits immediately. I use this a lot, and I find that I very rarely use the shift-W any more since we added that.

Of course, this doesn't make a difference for your feature request, because that kind of diff isn't easily copyable either, but it's very easy to make a custom command for it:
```yaml
customCommands:
    - command: 'git diff {{.SelectedCommitRange.From}}^..{{.SelectedCommitRange.To}} | pbcopy'
      context: "commits,subCommits"
      description: "Copy diff of selected commits to clipboard"
```
(You need a master build for the `SelectedCommitRange`, it's not released yet.)
