### ISSUE TITLE
patch failed when staging hunks

### ISSUE THREAD

**Issue by teocns** [jesseduffield/lazygit#4297]
Assume I want to stage a hunk:

<img width="609" alt="Image" src="https://github.com/user-attachments/assets/2353aaf8-19c6-4779-8a99-e17af4165333" />

...pressing `Space` leads me to this error

<img width="860" alt="Image" src="https://github.com/user-attachments/assets/ca0fee23-f6b7-4bf0-a381-9a21d6428ce3" />

---

- ~/.gitconfig

```~/.gitconfig

[user]
	..

[push]
	default = current
[core]
	editor = nvim
	precomposeUnicode = true
	excludesfile = ~/.gitignore
	whitespace = fix
	autocrlf = false  # Disable line ending conversion completely
	safecrlf = warn

[delta]
    # navigate = true
    # dark = true

[include]
  path = ~/.git_configs/personal

[mergetool "nvimdiff"]
	# trustExitCode = true  # Temporarily disable

[merge]
	tool = nvimdiff
  conflictstyle = diff3 # delta

[safe]
	directory = /app

[commit]
	gpgsign = true
[gpg]
	program = /usr/local/MacGPG2/bin/gpg2
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f

[difftool]
	prompt = false

```

- ~/Library/Application Support/lazygit/config.yml

```
os:
  editPreset: "nvim-remote"
gui:
  mouseEvents: false
  mainPanelSplitMode: horizontal
  expandFocusedSidePanel: true
  
  expandedSidePanelWeight: 1.33
  nerdFontsVersion: "3"
  showIcons: true
  sidePanelWidth: 0.40
  theme:
    selectedLineBgColor:
      - reverse
promptToReturnFromSubprocess: false
git:
  autoFetch: false
  fetchAll: false
  showCommandLog: false
  disableForcePushing: false
  overrideGpg: true
  paging:
    colorArg: always
  commit:
    signOff: true
  merging:
    args: "--no-ff"

disableStartupPopups: true
``` 

```
lazygit --version

commit=91cb1ff29a01fdf643ccc38b97fd816b2a097bec, build date=2025-01-11T04:06:07Z, build source=binaryRelease, version=0.45.0, os=darwin, arch=arm64, git version=2.47.1
```
