### ISSUE TITLE
How to add a Conventional commit specification before committing

### ISSUE THREAD

**Issue by oldqin97** [jesseduffield/lazygit#4414]
I used custome command to create a Conventional commit option, but I need to create an input for the information myself, which is very bloated. I want to let this Conventional commit option box go directly to lazygit's original commit input box after selecting it, and add feat(test.js): to the front of the subject, and I will add detailed information later

![Image](https://github.com/user-attachments/assets/ab3208ef-a992-405c-a5c5-bb0f9b566cd9)

**Comment by stefanhaller** [comment]
I'm strongly opposed to adding conventional commits functionality to lazygit. Conventional commits is a misguided attempt at encouraging better commits; I think it does more harm than good. I don't want to encourage its use by adding it to lazygit.

If you need to use conventional commits because your workplace demands it, then custom commands are the way to go (instead of generating the prompts yourself as shown in your screenshot you can also run one of the many command line tools that prompt you in the console). If it's your own choice to use them, consider just not doing it.

**Comment by ChrisMcD1** [comment]
To add a differing opinion, I am a fan of conventional commits. I find it useful to indicate to future people "This should just be a clean refactor, if you find a behavioral change, I did not intend it".

But I am also not seeing any utility in a lazygit integration. The prefixes are all very short, so it's pretty easy to type. Such as `feat(cli): Added support for new thing`. If I'm imagining a perfect input form that does this, I would still need to type `fe<tab>cli<tab>Title`. `fe` needed to differentiate from `fix`, assuming some sort of fuzzy matching. This saves only 3 keystrokes from your message, which if it is a good message, probably has many more than 3 keystrokes.

Do you have some other flow that I'm not imagining that means you're seeing substantial gains from your custom command?

**Comment by itpropro** [comment]
This would be a great addition to lazygit. Conventional commit have become the defacto standard for good commit messages not only in most open source, but also commercial projects.
Beside it's broad acceptance and adoption, there is also a lot of tooling available to generate changelogs, bump versions, create stats, etc..
Therefore native support in some way would be something that the vast majority of people interacting with git would benefit from.

**Comment by stefanhaller** [comment]
I can only repeat what I said above:

> Conventional commits is a misguided attempt at encouraging better commits; I think it does more harm than good. I don't want to encourage its use by adding it to lazygit.

Now, I didn't explain why I think so. The main reasons for this opinion are:

- it encourages making commits that are too big (at least for the 'feat' category). If one of the main purposes of conventional commits is that you can generate release notes from them, then it follows that most feature PRs will have one commit that adds the feature (because you will want to have one line or bullet point per feature in the release notes). This only makes sense for really simple features; more complex features will have many, many commits that contribute to adding the feature, unless people squash all their non-refactoring changes into one. And this is really bad and should be discouraged, but conventional commits encourages it.
- it fools people into believing that they are making good commit messages just because they are using conventional commits. There are so many other aspects to a good commit message, e.g. 
  - describing _why_ you are making a change. Many people only describe _what_ they are changing, which is much less important because it can be seen from the diff.
  - mentioning an exact reproduction recipe for a bug that is being fixed
  - mentioning possible alternative implementation approaches that have been considered but rejected (and why)
  - and many more.
Are these things any more likely to happen when people aren't using conventional commits? Maybe not, but with conventional commits people think they are done providing a high quality commit message once they have picked the right prefix.

I do realize that I'm probably fighting an uphill battle though.

> I find it useful to indicate to future people "This should just be a clean refactor, if you find a behavioral change, I did not intend it".

This doesn't need emphasizing; in any sane commit history it should be a matter of course.

**Comment by itpropro** [comment]
Thanks for your explanation, I think we agree in general that conventional commits do not decrease the quality of commit messages, in the worst case, they would stay the same with some additional metadata information.
I don't think that conventional commits would encourage to make "bigger" commits, I have not seen that in any project and it cannot really be said about most OSS projects that use conventional commits, but I understand the concern.
The thing that I have seen most often with conventional commits, especially if you have predefined scopes is that people start thinking about what they actually did. 
They don't replace proper guidelines, but they can support a lot with existing guidelines and workflows that people already use. Conventional commits are just a tool and it's up to the teams or maintainers how they use the convention and how they integrate them into their processes and guardrails.

To not go off topic too much, I think they would be a valuable addition to lazygit, especially as they are so broadly adopted throughout the whole open source ecosystem. 
Lazygit should support developers and teams with their workflows, so making the assumption that people would not benefit from conventional commits just because they can be misused, despite many teams using them successfully to support their workflows is not helping the users of lazygit, it is just forcing them to integrate other tooling for a comparatively uncomplex functionality.

**Comment by ChrisMcD1** [comment]
@itpropro I hear your points about the benefits of conventional commits, but I'm still not hearing a _product oriented_ description of what is being asked to be introduced.

What could Lazygit add that would help a user of conventional commits? If @stefanhaller were to wake up tomorrow and have a fire burning inside of him to help maintain a deep integration with conventional commits (emphasis on _if_ 😆 ), what would that feature look like?

I'm still hung up on my original point:
> But I am also not seeing any utility in a lazygit integration. The prefixes are all very short, so it's pretty easy to type.

**Comment by itpropro** [comment]
@ChrisMcD1 I would see the following features as part of optional conventional commit support
- Config key to enable/disable support in the config (default off)
- Easy selection of conventional commit type (feat, chore, fix, etc.) with auto completion during typing (maybe sorted by most frequently/recently used)
- Selection of an optional scope
- Being able to define a list of scopes in the users/repo config
- Prepend the commit title with the selected "{type}({scope}): " prefix
- Support for standard footers to be able to use semver with the commits (BREAKING, BREAKING CHANGE, closes, etc.)
- Support for widely used ! syntax to mark breaking changes (fix!: Fixed foo in bar to make foo better)

The flow would basically be to select a type and scope, write a descriptive title, if needed write a description and optionally append a footer.
Integrating it natively in lazygit instead of manually typing things like "fix(order-api): Fixed order struct test field to prevent overflow" would help a lot with consistency and speed when working with conventional commits. People not only make typos in the types or scopes, they also make up scopes or types sometime, forget the correct syntax or forget to mention that it is actually a breaking change or closes an open issue.
Most of these issues can be avoided or at least be made much more unlikely to occur.

**Comment by JordanllHarper** [comment]
The only way I would like this implemented is an autocomplete behaviour where you type "fe" for feature commit and get some mandatory spots to fill in. Tabbing through menus doesn't sound good and could conflict with #4627 .

**Comment by mrt181** [comment]
```yaml
customCommands:
  - key: "C"
    context: "files"
    description: "Create new conventional commit"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
            key: "b"
          - name: "feat"
            description: "A new feature"
            value: "feat"
            key: "f"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
            key: "x"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
            key: "c"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
            key: "i"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
            key: "d"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
            key: "p"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
            key: "r"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
            key: "v"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
            key: "s"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
            key: "t"
      - type: "input"
        title: "Scope"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        key: "Breaking"
        title: "Breaking change"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "!"
            key: "y"
      - type: "input"
        title: "message"
        key: "Message"
        initialValue: ""
    command: 'git commit --message ''{{.Form.Type}}{{ if .Form.Scope }}({{ .Form.Scope }}){{ end }}{{ if eq .Form.Breaking "!" }}!{{ end }}: {{.Form.Message}}'''
    loadingText: "Creating conventional commit..."
```

**Comment by itpropro** [comment]
> customCommands:
>   - key: "C"
>     context: "files"
>     description: "Create new conventional commit"
>     prompts:
>       - type: "menu"
>         key: "Type"
>         title: "Type of change"
>         options:
>  ...

This would be much more comfortable with native support. Especially now where basically everyone working with Git and/or in open source is using AI, conventional commits have become even more essential than before. They are one of the important quality gates together with hooks and tools like `commitlint` and are one of the only ways to reliably provide consistent automatic semantic versioning and proper generated changelogs, which is essential for tools that have multiple releases per week or even per day in many cases.
I also haven't worked in a single git repository that didn't use conventional commits for years and I think it would be worth reconsidering implementing this as a native feature @stefanhaller, as it is the only "big" git related functionality that everyone is using but is not natively supported by `lazygit` and requires the installation and configuration of additional software for every project you want to use lazygit in.

**Comment by JordanllHarper** [comment]
Personally I don't see the value in adding conventional commits natively, given it's still an extension on Git. 

While it's not strictly "comfortable", it's still possible as shown above. Native support would mean less configuration, but it would impose it on users who don't want it, and create more maintenance work.

I think a plugin is a perfect use case for conventional commits.
Something optional that people can use to extend lazygit (like how conventional commits extend Git commit syntax).

Coming from a place where we use conventional commits every day at work.

**Comment by mrt181** [comment]
I use conventional commits myself but to drive semver generation.
The custom commands approach works great for me so far, with the exception for breaking changes were its just not as nice but still works.

lazygit already gave users this powerful way to get them there 90% of the way.
Would they bake it in, people will start asking for customization of that approach anyway, like use the exclamation mark on breaking changes or not etc.

It's not a universal way of formatting commit messages that everyone is using. it's popular, but the majority is not using it. lazygit is not used by tools or agents, those just use git directly. lazygit is used by developers and custom commands is flexible enough to get you to a menu driven conventional commit interface - fantastic that this emerges from that feature.
It could benefit from this to close the last 10%: https://github.com/jesseduffield/lazygit/pull/5364

I updated the config like this:
```yml
customCommands:
  - key: "C"
    context: "files"
    description: "Create new conventional commit"
    prompts:
      - type: "menuFromCommand"
        key: "type"
        title: "Select the type of change that you're committing"
        command: "sh -c \"NODE_PATH=$(npm root -g) node -e \\\"const e=require('@commitlint/config-conventional').default.prompt.questions.type.enum;for(const[k,v]of Object.entries(e)){const em=v.emoji.includes('\\\\uFE0F')?v.emoji:v.emoji+'\\\\uFE0F';console.log(em+' '+k+' '+v.description)}\\\"\""
        filter: "(?P<emoji>\\S+) (?P<value>\\S+) (?P<description>.*)"
        valueFormat: "{{ .value }}"
        labelFormat: "{{ .emoji }} {{ printf \"%-12s\" .value }} {{ .description }}"
      - type: "menu"
        key: "hasScope"
        title: "What is the scope of this change (e.g. component or file name)"
        options:
          - name: "none"
            value: "no"
            key: "n"
          - name: "specify"
            value: "yes"
            key: "y"
      - type: "input"
        title: "What is the scope of this change (e.g. component or file name)"
        key: "scope"
        condition: '{{ eq .Form.hasScope "yes" }}'
      - type: "input"
        title: "Write a short, imperative tense description of the change"
        key: "subject"
      - type: "input"
        title: "Provide a longer description of the change"
        key: "body"
      - type: "menu"
        key: "isBreaking"
        title: "Are there any breaking changes?"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "!"
            key: "y"
      - type: "input"
        title: "A BREAKING CHANGE commit requires a body. Please enter a longer description of the commit itself"
        key: "body"
        condition: '{{ and (eq .Form.isBreaking "!") (not .Form.body) }}'
      - type: "input"
        title: "Describe the breaking changes"
        key: "breaking"
        condition: '{{ eq .Form.isBreaking "!" }}'
      - type: "menu"
        key: "hasIssue"
        title: "Does this change affect any open issues?"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "yes"
            key: "y"
      - type: "input"
        title: 'Add issue references (e.g. "fix #123", "re #123".)'
        key: "issue"
        condition: '{{ eq .Form.hasIssue "yes" }}'
    command: 'git commit --message ''{{.Form.type}}{{ if .Form.scope }}({{ .Form.scope }}){{ end }}{{ if eq .Form.isBreaking "!" }}!{{ end }}: {{.Form.subject}}'' {{ if .Form.body }}--message ''{{ .Form.body }}''{{ end }}{{ if .Form.breaking }} --message ''BREAKING CHANGE: {{.Form.breaking}}''{{ end }}{{ if .Form.issue }} --message ''{{.Form.issue}}''{{ end }}'
    loadingText: "Creating conventional commit..."
```

This gives me this

<img width="818" height="242" alt="Image" src="https://github.com/user-attachments/assets/73169895-4a8a-455c-a19c-608cad5a24ba" />

<img width="834" height="102" alt="Image" src="https://github.com/user-attachments/assets/9a72b79f-6469-458f-869c-bb0aab1b6db0" />

<img width="759" height="79" alt="Image" src="https://github.com/user-attachments/assets/0de618d2-101f-4226-83d4-ec1924c4e813" />

<img width="834" height="97" alt="Image" src="https://github.com/user-attachments/assets/2986b1ad-d080-420f-982b-3604c36f6e8b" />

<img width="743" height="77" alt="Image" src="https://github.com/user-attachments/assets/1678abbd-d488-4eea-913e-0fa9c7d4c2a0" />

```
┌─────────────────────────────────────────────────────────────┐
│ 1. type (menuFromCommand)                                   │
│    Select: feat, fix, docs, style, refactor, ...            │
└──────────────────────────┬──────────────────────────────────┘
                           ▼
┌─────────────────────────────────────────────────────────────┐
│ 2. hasScope (menu)                                          │
│    [n] none  /  [y] specify                                 │
└─────────┬───────────────────────────────────┬───────────────┘
          │ no                                │ yes
          │                                   ▼
          │                  ┌────────────────────────────────┐
          │                  │ 3. scope (input)               │
          │                  │    e.g. "parser", "api"        │
          │                  └───────────────┬────────────────┘
          │                                  │
          ▼◄─────────────────────────────────┘
┌─────────────────────────────────────────────────────────────┐
│ 4. subject (input)                                          │
│    "Write a short, imperative tense description..."         │
└──────────────────────────┬──────────────────────────────────┘
                           ▼
┌─────────────────────────────────────────────────────────────┐
│ 5. body (input)                                             │
│    "Provide a longer description..." (can leave empty)      │
└──────────────────────────┬──────────────────────────────────┘
                           ▼
┌─────────────────────────────────────────────────────────────┐
│ 6. isBreaking (menu)                                        │
│    [n] no  /  [y] yes (!)                                   │
└─────────┬───────────────────────────────────┬───────────────┘
          │ no                                │ yes (!)
          │                                   ▼
          │                  ┌────────────────────────────────┐
          │                  │ body was empty?                │
          │                  └──┬─────────────────────┬───────┘
          │                 yes │                     │ no
          │                     ▼                     │
          │  ┌───────────────────────────────────┐    │
          │  │ 7. body (input, reused key)       │    │
          │  │  "A BREAKING CHANGE requires a    │    │
          │  │   body..."                        │    │
          │  └──────────────┬────────────────────┘    │
          │                 │                         │
          │                 ▼◄────────────────────────┘
          │  ┌───────────────────────────────────┐
          │  │ 8. breaking (input)               │
          │  │  "Describe the breaking changes"  │
          │  └──────────────┬────────────────────┘
          │                 │
          ▼◄────────────────┘
┌─────────────────────────────────────────────────────────────┐
│ 9. hasIssue (menu)                                          │
│    [n] no  /  [y] yes                                       │
└─────────┬───────────────────────────────────┬───────────────┘
          │ no                                │ yes
          │                                   ▼
          │                  ┌────────────────────────────────┐
          │                  │ 10. issue (input)              │
          │                  │  "fix #123", "re #123"         │
          │                  └───────────────┬────────────────┘
          │                                  │
          ▼◄─────────────────────────────────┘
┌─────────────────────────────────────────────────────────────┐
│ git commit                                                  │
│  --message '<type>[(<scope>)][!]: <subject>'                │
│  [--message '<body>']                                       │
│  [--message 'BREAKING CHANGE: <breaking>']                  │
│  [--message '<issue>']                                      │
└─────────────────────────────────────────────────────────────┘
```
