### ISSUE TITLE
Set commit author name and email

### ISSUE THREAD

**Issue by sclause2412** [jesseduffield/lazygit#4487]
**Is your feature request related to a problem? Please describe.**
If I checkout a repository and want to commit something it fails with "Author identity unknown". This is because I have NOT set an author globally. I do not want to do it globally because I sometimes want to commit with my private account and sometimes with my work account. If I set it globally I will forget to change and then I have issues solving it out.

**Describe the solution you'd like**
If there is no author given then lazygit could inform and ask for an author. Could be same dialog as for "Amend commit attribute..." command.
Another possibility is to just have a keybinding for setting an author. Example: Use similar keybinding as for "Amend commit attribute..." (e.g. Ctrl+a) but if used in Files view then it is called "Set author...".

**Describe alternatives you've considered**
Custom Commands can be used - but hey, it's a feature request, not a bug :-)

**Additional context**
Custom command version:
```yaml
customCommands:
  - key: '<c-a>'
    context: 'files'
    description: 'Set author'
    prompts:
      - type: 'input'
        title: 'What is the new author name?'
        key: 'Author'
        initialValue: ''
        suggestions:
          preset: 'authors'
    command: 'git config user.name "$(echo "{{.Form.Author}}" | sed -E "s/^(.*) <.*>$/\1/")" && git config user.email "$(echo "{{.Form.Author}}" | se>
```

**Comment by tyrellcurry** [comment]
hi @sclause2412, I can't seem to reproduce this. I have tried unsetting my git config globally and locally, and git will create a user for me automatically:

```bash
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author
```

If I unset my config globally, but set it locally, I do not get the error "Author identity unknown".

Am I missing something on the issue?

tysm!

**Comment by sclause2412** [comment]
OK. Then it seems that my computer behaves differently. If I have not set any author locally AND globally then I get the error message. Because I need to use different authors for different projects I always set them manually with git commands or with this customCommand. However, it would be nice to get an information from lazygit if there is no global AND local author set and give the option (e.g. input field) to type in author name and email instead of doing that with git commands manually.
This is the only thing I need to do with git commands currently because lazygit does not support it.

**Comment by stefanhaller** [comment]
@tyrellcurry The behavior you are describing can be disabled with `git config --global user.useConfigOnly true`, which I suppose is what @sclause2412 did (and it's a good idea to do that for his workflow).

@sclause2412 Yes, we could build this into lazygit, but I'm not sure it's worth it. Ideally it would check at startup if user name and email are set, and prompt for them if not. There are a few questions to be answered though, for example:
- sometimes we show other popups at startup, e.g. the new user popup, or a breaking changes popup after updating. We'd have to coordinate in what order we show them. Not impossible to solve, but more complexity then I'd want to deal with for this.
- we'd also have to let the user decide whether they want to store the name and email only for this repo or globally. For your workflow it would always be locally, but for users who are new to git it may make more sense to configure it globally.

Anyway, personally I think that a custom command or two is the perfect solution for a niche use case like this. I'd suggest something along these lines:
```yml
customCommands:
  - description: "Set user name and email"
    commandMenu:
      - key: w
        description: Work
        command: git config user.name "Joe Worker" && git config user.email joe@work.com
      - key: p
        description: Private
        command: git config user.name "Joe Private" && git config user.email joe@private.org
```
