### ISSUE TITLE
Allow overwriting of default icons and colors

### ISSUE THREAD

**Issue by 89iuv** [jesseduffield/lazygit#4549]
**Is your feature request related to a problem? Please describe.**
I want to change the default directory icon and color.

**Describe the solution you'd like**
Add a new option in config yaml to override the default directory icon and color:
```yaml
gui:
    customIcons:
        defaults:
            DEFAULT_DIRECTORY_ICON:
                icon: "\U000f011b"
                color: "#BC4009"
```

**Describe alternatives you've considered**
I tried the solution from here: https://github.com/jesseduffield/lazygit/issues/3863
```sh
echo -ne "\033]4;241;rgb:65/bc/ff\007" && lazygit
```
This did not work, and it seems more of a hack than a solution.

**Additional context**
I did a little investigation and it looks like the icons and colors are hardcoded here: https://github.com/jesseduffield/lazygit/blob/ef1da6f704329e977a4fcb3c4653c2a82ba6519d/pkg/gui/presentation/icons/file_icons.go#L17
It would be nice to expose all of the default icons and colors through the config file.
