### ISSUE TITLE
how to contribute to Lazygit Custom Commands Compendium?

### ISSUE THREAD

**Issue by pdicerbo** [jesseduffield/lazygit#4623]
**Describe the bug**

I wasn't able to push a commit containing a custom command in the Lazygit Wiki

**To Reproduce**

1. I cloned the wiki repo: `git clone https://github.com/jesseduffield/lazygit.wiki.git`
2. I added a new section with the command I'd like to share
3. I tried to push my commit: `git push origin master`
4. The push failed since the password authentication was removed, however I cannot push via ssh keys as well.

Sorry for the stupid question, there is for sure something basilar I'm missing.
How can I proceed?
If you prefer I can copy/paste the commit content here and you decide if include in the wiki or not :)

**Comment by mark2185** [comment]
That's because you don't have write permissions to the `master` branch in the original repository.

The usual way of proposing changes is forking the repository, creating changes in the fork, push them, and then opening a pull-request which is reviewed and discussed.

What is the command you wished to add to the wiki?

**Comment by pdicerbo** [comment]
Thank you for the rapid answer :)

If I understood correctly the Wiki is into another repository, right?
But I wasn't able to find it such that I could fork it...

I implemented a simple command to show the tag annotation in the tag panel:

```
customCommands:
  - key: 'a'
    context: 'tags'
    command: "git for-each-ref refs/tags/{{.SelectedTag.Name}} --format='%(contents)'"
    output: popup
    outputTitle: "Tag Annotation"
    description: "Show Tag Annotation"
```
For me is quite useful, maybe someone else can find this useful too.
