### ISSUE TITLE
add `skipAmendWarning` for `amendLastCommit`

### ISSUE THREAD

**Issue by vogler** [jesseduffield/lazygit#4636]
I don't see an option to disable this 'Amend last commit' warning:
<img width="778" alt="Image" src="https://github.com/user-attachments/assets/2da4bb65-4c86-49d9-9469-c50d07eb3299" />

https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default only lists
```yaml
  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: false

  # If true, do not show warning when applying/popping the stash
  skipStashWarning: false

  # If true, do not show a warning when attempting to commit without any staged files; instead stage all unstaged files.
  skipNoStagedFilesWarning: false

  # If true, do not show a warning when rewording a commit via an external editor
  skipRewordInEditorWarning: false
```
