### ISSUE TITLE
Add custom command to show tag annotation to Lazygit Wiki

### ISSUE THREAD

**Issue by pdicerbo** [jesseduffield/lazygit#4659]
I tried to the Lazygit Custom Command Compendium but I failed (see [here](https://github.com/jesseduffield/lazygit/issues/4623) for further details).

I tried to add this custom command to show the tag annotations, maybe it will be helpful to someone..

```
customCommands:
  - key: 'a'
    context: 'tags'
    command: "git for-each-ref refs/tags/{{.SelectedTag.Name}} --format='%(contents)'"
    output: popup
    outputTitle: "Tag Annotation"
    description: "Show Tag Annotation"
```

Moreover, if contributions to the Lazygit Custom Command Compendium are not accessible anymore, it could be a good idea to update the relative documentation, just to avoid waste of time by people that try to contribute..
