### ISSUE TITLE
Config file doesn't seem to work?

### ISSUE THREAD

**Issue by garymh** [jesseduffield/lazygit#631]
**Describe the bug**
I could just be missing something obvious, but the config file location at `~/.config/jesseduffield/lazygit/config.yml` doesn't seem to do anything for me.

**To Reproduce**
1. Create a file at `~/.config/jesseduffield/lazygit/config.yml`
2. Add a basic config:

```yaml
gui:
  theme:
    activeBorderColor:
      - blue
      - bold
```

**Expected behavior**
I assume this would make the border color blue when active, but it stays the default white. 

**Desktop (please complete the following information):**
 - macOS 10.15.3
- zsh 5.7.1
 - Lazygit 0.14

**Additional context**
I also notice in "15 Lazygit features" video that there is a config file at `~/Library/Application\ Support/jesseduffield/lazygit/config.yml`. Adding the basic config above doesn't work for me there either.

**Comment by jesseduffield** [comment]
if you navigate to the status panel (top left) in lazydocker and press 'o' (opens the config), what is the path of the file that opens?

**Comment by garymh** [comment]
That opens the `~/Library/Application\ Support/jesseduffield/lazygit/config.yml` one. I have in there:

```yaml
gui:
  theme:
    activeBorderColor:
      - blue
      - bold
reporting: "off"
startuppopupversion: 1
```
