### ISSUE TITLE
activebordercolor defines background of INactive border labels

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#780]
**Describe the bug**
![image](https://user-images.githubusercontent.com/596073/78772644-61ba3200-7992-11ea-8a45-27af356a83da.png)

this happens with `mate-terminal`
```
TERM=xterm-256color
COLORTERM=truecolor
```

**To Reproduce**
i'm using the following config:
```
 confirmonquit: false
 git:
   autofetch: false
   merging:
     manualcommit: false
   skiphookprefix: WIP
 gui:
   commitlength:
     show: true
   mouseevents: false
   scrollheight: 2
   scrollpastbottom: true
   theme:
     activebordercolor:
     - yellow
     lighttheme: true
 reporting: "off"
 startuppopupversion: 1
 update:
   days: 14
   method: prompt

```
