### ISSUE TITLE
Some highlighted lines are still very hard to see

### ISSUE THREAD

**Issue by ms-jpq** [jesseduffield/lazygit#802]
**Describe the bug**
Almost impossible to see selected lines in low contrast colour schemes.
Similar to the issue in https://github.com/jesseduffield/lazygit/issues/744, I think it would be best to add a background highlight

EDIT:
The bold works, what I mean is that just bolding the text by itself is probably insufficient. 

**To Reproduce**
My colours are as follows

```
gui:
  theme:
    lightTheme: True
    activeBorderColor:
      - magenta
    inactiveBorderColor:
      - black
    optionsTextColor:
      - magenta
    selectedLineBgColor:
      - reverse
      - underline
```

**Expected behavior**
The selected line should be able to standout

**Screenshots**

I have the last file selected
![pic](https://user-images.githubusercontent.com/50598611/79799369-31b64b80-830f-11ea-83e4-51ba6b3bbf4e.png)

I have the first `<<< HEAD` selected
![pic2](https://user-images.githubusercontent.com/50598611/79800531-3d0a7680-8311-11ea-947b-6c5a6a2cbcf9.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Lazygit Version: v0.20
 - From ubuntu PPA, last built 04/20/2020

**Comment by jesseduffield** [comment]
This is fixed in release v0.20.3 :) (thanks to @quantonganh for investigation). If you want things to be really visible I recommend the following config:

```
  gui:
    theme:
      selectedLineBgColor:
        - reverse
```
