### ISSUE TITLE
Invisible highlighting in kitty and alacritty terminal

### ISSUE THREAD

**Issue by benruijl** [jesseduffield/lazygit#831]
In the kitty terminal it is impossible to see the highlighting, regardless of colour scheme.

Steps to reproduce:
- Try lazygit in the kitty terminal

 - OS: Arch Linux
 - Lazygit Version 0.20.2
- Kitty version 0.17.3

**Comment by lukewang1024** [comment]
Same issue here. The selected item is not highlighted.

- lazygit 0.20.2
- Alacritty 0.4.2
- macOS

**Comment by chmln** [comment]
It's not exactly invisible, just hard to notice. The focus on screenshot below is on `Cargo.lock`:

![image](https://user-images.githubusercontent.com/11352152/83841168-52bfd980-a6ce-11ea-8f5f-e1970371b6aa.png)

It would be great if the background was highlighted instead.

**Comment by benruijl** [comment]
That is actually visible for me. This is what I am seeing:

![alacritty](https://user-images.githubusercontent.com/280089/83855260-1b761a80-a718-11ea-9000-cc8b7bbee723.png)

**Comment by a-elhag** [comment]
Had the same problem, but looking through the [docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) I found a solution. Make a config file and put the settings in it:

## Default Path
Default path for the config file:

```
Linux: ~/.config/jesseduffield/lazygit/config.yml
MacOS: ~/Library/Application Support/jesseduffield/lazygit/config.yml
Windows: %APPDATA%\jesseduffield\lazygit\config.yml
```

## And put these settings in it

```
  gui:
    theme:
      lightTheme: true
      activeBorderColor:
        - black
        - bold
      inactiveBorderColor:
        - black
      selectedLineBgColor:
        - default
```

## How the highlighting now looks
![Screenshot](https://user-images.githubusercontent.com/48454648/90217404-42fbfa00-ddcf-11ea-8e11-961a43bfdc41.png)

**Comment by mordax777** [comment]
> Had the same problem, but looking through the [docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) I found a solution. Make a config file and put the settings in it:
> 
> ## Default Path
> Default path for the config file:
> 
> ```
> Linux: ~/.config/jesseduffield/lazygit/config.yml
> MacOS: ~/Library/Application Support/jesseduffield/lazygit/config.yml
> Windows: %APPDATA%\jesseduffield\lazygit\config.yml
> ```
> 
> ## And put these settings in it
> ```
>   gui:
>     theme:
>       lightTheme: true
>       activeBorderColor:
>         - black
>         - bold
>       inactiveBorderColor:
>         - black
>       selectedLineBgColor:
>         - default
> ```
> 
> ## How the highlighting now looks
> ![Screenshot](https://user-images.githubusercontent.com/48454648/90217404-42fbfa00-ddcf-11ea-8e11-961a43bfdc41.png)

If I add the configuration it looks like this afterwards:
![image](https://user-images.githubusercontent.com/27705384/96149678-e4a3e280-0f09-11eb-8172-99d8519b0164.png)

**Comment by jesseduffield** [comment]
@mordax777 can you see how you go with:
```
      inactiveBorderColor:
        - white
```

**Comment by mordax777** [comment]
@jesseduffield sorry for the late reply. Here the result.
![image](https://user-images.githubusercontent.com/27705384/96569703-c18e7f80-12c9-11eb-9d28-c7a5611d748a.png)

**Comment by bahelms** [comment]
@mordax777 I played around with the settings and got something that worked for me. I'm using Kitty. The [docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) helped.
```
gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
      - blue
```
![image](https://user-images.githubusercontent.com/3368917/96586606-3902e580-12af-11eb-9e62-1f7601c5fb99.png)

**Comment by mordax777** [comment]
@bahelms Thanks, that fixed the problem!

**Comment by Axel-Jacobsen** [comment]
For people in the future, I will add that I had the same issue as @benruijl, and it was solved by going into my terminal settings and allowing bold fonts.

**Comment by lqiang79** [comment]
There is the same issue in windows Terminal.

**Comment by MikaelElkiaer** [comment]
Same issue here, had to do as suggested in [docs/Config](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line).

**Comment by jesseduffield** [comment]
I've added the example of
```yml
gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
      - blue
```
to the [docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line) and I've added a FAQ section in the [readme](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line) pointing at that section of the docs.

Was there anybody who still had an issue they weren't able to resolve by updating their config? If not I'm happy to close this ticket
