### ISSUE TITLE
Custom pagers not working for diff. (delta or diff-so-fancy)

### ISSUE THREAD

**Issue by lordlycastle** [jesseduffield/lazygit#907]
**Describe the bug**
I followed the instruction to add custom pager to my config and they are not working. I've tried both `delta` and `diff-so-fancy`; they work outside `lazygit` but not in it. 

I also noticed in the created `config.yml` file it says `colorargs` and not `colorArgs` that could be a typo somewhere in the code, but that's not the real issue as I set both of them.

I've tried both like so and neither render in the diff window. This is what the config looks like:

```
git:
  autofetch: true
  merging:
    args: ""
    manualcommit: false
  paging:
    colorarg: always
    #useconfig: false
    colorArg: always
    pager: diff-so-fancy
    #pager: delta --dark --paging=never --24-bit-color=never
```

**To Reproduce**
1. Add custom pagers to your config.

**Expected behavior**
It should use the custom pagers.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 
 - Lazygit Version: `commit=, build date=, build source=homebrew, version=0.20.4, os=darwin, arch=amd64`

**Comment by Cokile** [comment]
Same here

**Comment by jesseduffield** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/8456633/89996929-c5e95b80-dcce-11ea-9efe-ab4aa08909c8.png)

I'm not sure if I mention it in the docs but you will need to have the relevant pager installed (though you do mention they work outside of lazygit @lordlycastle).

Would you be able to provide your `env` values for COLORTERM, TERM, PAGER, and LESS. Here's mine:
```
COLORTERM=truecolor
TERM=xterm-256color
PAGER=less
LESS=-R
```

**Comment by Cokile** [comment]
Outside of lazygit:
<img width="227" alt="Screen Shot 2020-08-12 at 17 18 27" src="https://user-images.githubusercontent.com/8230448/89998333-f8d82300-dcbf-11ea-8a6d-978af8d22c97.png">

 Inside of lazygit:
<img width="254" alt="Screen Shot 2020-08-12 at 17 18 39" src="https://user-images.githubusercontent.com/8230448/89998336-fa095000-dcbf-11ea-8c41-537878dedcee.png">

As you can see, the `n` is highlighted from the first picture but not in the second one.

Here is my whole config file:
```
git:
  paging:
    colorarg: always
    pager: diff-so-fancy

reporting: "off"
startuppopupversion: 1
```

Here is my `env` values:
```
COLORTERM=truecolor
TERM=xterm-256color
PAGER=less
LESS=-R
```

**Comment by jesseduffield** [comment]
@Cokile your issue is a result of lazygit not supporting 24 bit colors (this is because termbox, one of its dependencies, does not support 24 bit colors). Unfortunately there is no way around this currently, unless you use delta which supports non-24 bit color terminals via the `--24-bit-color=never` flag. 

Having said all that, I believe @lordlycastle 's issue is that the pager does not work at all in lazygit.

**Comment by briandipalma** [comment]
I'm seeing something similar. It works when I use delta in the command line and I reference it in the lazygit config but not when I set lazygit to use the git pager which is set to use delta.

.gitconfig (https://github.com/briandipalma/machine-setup/blob/master/.gitconfig#L36):
```
  36   │ [diff]
  37   │   colorMoved = default
  38   │
  39   │ [core]
  40   │   pager = delta
  41   │
  42   │ [interactive]
  43   │   diffFilter = delta --color-only
  44   │
  45   │ [delta]
  46   │   side-by-side = true
  47   │   syntax-theme = Solarized (light)
```

Failing lazygit config:
```yaml
git:
  paging:
    colorArg: always
    useConfig: true
```

Successful lazygit config (https://github.com/briandipalma/machine-setup/blob/master/lazygit-config.yml#L10):
```yaml
git:
  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never
```

I get some odd characters in the Unstaged Changes output when its set to use the git pager: `[?1049h[?1h=`

![image](https://user-images.githubusercontent.com/1597820/96427377-617ad900-11f6-11eb-9d3a-533764b27014.png)
