### ISSUE TITLE
Autocomplete/suggest git commit message

### ISSUE THREAD

**Issue by pyrooka** [jesseduffield/lazygit#941]
**Is your feature request related to a problem? Please describe.**
Sometimes we (at least me) just copy messages from previous commits. For example: "Bump version...", Update X to version Y.

**Describe the solution you'd like**
Suggest a message based on the history when we are typing, like in k9s: 
<img width="162" alt="Screenshot 2020-08-19 at 12 32 17" src="https://user-images.githubusercontent.com/15990318/90624958-17d33980-e219-11ea-9a9c-e1013d59ae16.png">
I am not thinking about some highly intelligent, super fancy AI powered autocomplete engine, just a simple regex which matches from the start.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pyrooka** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/15990318/91173751-9da22980-e6de-11ea-8ddc-a8af28e3a5f6.png">

What do you think about something like this?

**Comment by ecosse3** [comment]
I would love to see that feature implemented.

Also, it would be nice to have autocompletion of [Conventional Commits](https://www.conventionalcommits.org/) like _feat, fix, refactor_ etc. as well as scope for them (based on file/directory names of staged files for example).

**Comment by jnmcfly** [comment]
using the https://github.com/lintingzhen/commitizen-go wizard would be awesome here. Use lazygit and commitizen in split terminal.

**Comment by nahtnam** [comment]
https://github.com/Nutlope/aicommits

Would be cool if we could use this

**Comment by WladyX** [comment]
Just a bug related to my workaound, if you don't issue the lazygit from the root repo path, i get:
```
2023/04/05 15:30:32 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString repository does not exist
/private/tmp/lazygit-20230201-69813-1wzwylz/lazygit-0.37.0/pkg/app/app.go:54 (0x10084acf4)
/private/tmp/lazygit-20230201-69813-1wzwylz/lazygit-0.37.0/pkg/app/entry_point.go:146 (0x10084c6d0)
/private/tmp/lazygit-20230201-69813-1wzwylz/lazygit-0.37.0/main.go:23 (0x10084e628)
/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:250 (0x10029bcec)
/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 (0x1002ca344)
```

**Comment by noahbald** [comment]
Would also like to see this work in a zsh fashion for commit and branch names. ie pressing `tab` or `->` to autofill up to a certain point in the message based on previous commits/branches

**Comment by DhruvaG2000** [comment]
++
Would love to see this feature, we can start with something as basic as auto suggest title based on the path of the file being changed.

**Comment by ALameLlama** [comment]
@WladyX did you do anything else to get the hooks workings within lazygit?

I installed it, setup my API key, installed the hook within my repo and can see it within .git/hooks but when I stage a file and press `c` it doesn't trigger it, I can manually trigger it from the cli but not within lazygit

**Comment by WladyX** [comment]
nothing else, but it must be capital c, `C`, not `c`

**Comment by codevogel** [comment]
This is why I built [commit for me](https://github.com/codevogel/commit-for-me)!

It does go a little more in-depth than in this issue, as it generates the commit messages candidates using AI, and then opens the commit message in your `$EDITOR` for review.
If you then save the file, you commit. If you leave it untouched or empty, you abort.

Demo: 

![main demo](https://raw.githubusercontent.com/codevogel/commit-for-me/main/demo/demo.gif)

Lazygit use demo:

![lazygit demo](https://raw.githubusercontent.com/codevogel/commit-for-me/main/demo/lazygit-demo.gif)

It's a simple bash script that you can use standalone, or with lazygit integration using this custom command:

```yaml
customCommands:
  - key: "<c-a>"
    description: "generate message candidates and commit using cfme"
    command: "cfme"
    context: "files"
    loadingText: "Generating commit message with cfme..."
    subprocess: true
```

It uses the `conventional-commits` standard by default ([see the prompt here](https://github.com/codevogel/commit-for-me/blob/main/defaults/prompts/conventional-commits/default.md)), but it's also [_VERY_ easy to customize](https://github.com/codevogel/commit-for-me?tab=readme-ov-file#customization) to your own needs:

You just write a prompt file in `markdown` using template strings `<__IN_THIS_FORMAT__>`, and supply a variables file in `YAML`, which swaps out the template strings from **A)** literal string values from your YAML file, or **B)** command (sequences) defined in your YAML file.

For example, the simplest promp file could look like this:
```
Generate a commit message for the following changes:
<__GIT_DIFF__>
<__RESPONSE__REQUIREMENTS__>
```

or a more complex prompt file:
```
You are an expert software developer who writes clear and concise commit messages.
Your task is to generate a commit message based on the following instructions,
if present:
<__INSTRUCTIONS__>
The commit message should follow these guidelines:
<__COMMIT_MESSAGE_GUIDELINES__>
Here are the changes that need to be committed:
<__GIT_DIFF__>
Generate <__NUM_COMMIT_MESSAGES__> commit message candidates that adheres to the
above guidelines.
Here are the test results for the changes:
<__TEST_RESULTS__>
<__RESPONSE__REQUIREMENTS__>
```

With corresponding variable file:
```
vars:
  - template_string: "<__COMMIT_MESSAGE_GUIDELINES__>"
    value: |
      - Use the imperative mood in the subject line.
      - Limit the subject line to 50 characters.
      - Wrap the body at 72 characters.
      - Use the body to explain what and why vs. how.
  - template_string: "<__NUM_COMMIT_MESSAGES__>"
    value: "3"
  - template_string: "<__TEST_RESULTS__>"
    value_from: "pnpm test:unit --reporter=summary"
```
