### ISSUE TITLE
Disable Esc as button for quit

### ISSUE THREAD

**Issue by timsofteng** [jesseduffield/lazygit#992]
Hey. Can I somehow disable Esc button for quit from lazygit? I want to disable it just for quit but not all functionality.
Thanks.

**Comment by jesseduffield** [comment]
you can go `quitOnTopLevelReturn: false` in the config :) (I do this myself and might even make it the default if people think that makes sense)

**Comment by jesseduffield** [comment]
Perhaps you're not editing the config file in the right place. If you set this as your config, do you get cyan borders?
```
gui:
  theme:
    activebordercolor:
    - cyan
    - bold
quitOnTopLevelReturn: false
reporting: "off"
startupPopupVersion: 1
```
Furthermore, with that config, does 'escape' do nothing if you've just entered the app?
