### ISSUE TITLE
commitPrefixes should add the cursor at the end of the commit message

### ISSUE THREAD

**Issue by wirtsi** [jesseduffield/lazygit#994]
**Describe the bug**
A very small nit ... but this could improve the workflow even a little more

**To Reproduce**
Config
```
git:
  commitPrefixes:
    api: # This is repository folder name
      pattern: "^\\w+\\/(\\w+-\\w+)"
      replace: "$1 - "
```
Gives me a predefined commit message with a prefix based on the branch

**Expected behavior**
I'd like that the cursor is at the end of the commit input field, not the beginning

**Screenshots**
![Bildschirmfoto 2020-09-09 um 10 05 33](https://user-images.githubusercontent.com/276751/92571935-0911fc80-f284-11ea-8d13-0a507fe4a257.png)

**Desktop (please complete the following information):**
- Any env I would assume
